// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_248_RECOMP_H
#define _DLL_248_RECOMP_H

#define dll_248_ctor __dll248_dll_248_ctor
#define dll_248_dtor __dll248_dll_248_dtor
#define dll_248_setup __dll248_dll_248_setup
#define dll_248_control __dll248_dll_248_control
#define dll_248_update __dll248_dll_248_update
#define dll_248_print __dll248_dll_248_print
#define dll_248_free __dll248_dll_248_free
#define dll_248_get_model_flags __dll248_dll_248_get_model_flags
#define dll_248_get_data_size __dll248_dll_248_get_data_size
#define dll_248_func_A5C __dll248_dll_248_func_A5C
#define _rodata_10 __dll248__rodata_10
#define _rodata_18 __dll248__rodata_18
#define _rodata_1C __dll248__rodata_1C
#define _data_0 __dll248__data_0
#define _bss_0 __dll248__bss_0

#endif //_DLL_248_RECOMP_H
