// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_252_RECOMP_H
#define _DLL_252_RECOMP_H

#define Cannon_ctor __dll252_Cannon_ctor
#define Cannon_dtor __dll252_Cannon_dtor
#define Cannon_setup __dll252_Cannon_setup
#define Cannon_control __dll252_Cannon_control
#define Cannon_update __dll252_Cannon_update
#define Cannon_print __dll252_Cannon_print
#define Cannon_free __dll252_Cannon_free
#define Cannon_get_model_flags __dll252_Cannon_get_model_flags
#define Cannon_get_data_size __dll252_Cannon_get_data_size
#define dInitialPause __dll252_dInitialPause
#define dObjectRef __dll252_dObjectRef

#endif //_DLL_252_RECOMP_H
