// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_296_RECOMP_H
#define _DLL_296_RECOMP_H

#define dll_296_ctor __dll296_dll_296_ctor
#define dll_296_dtor __dll296_dll_296_dtor
#define dll_295_setup __dll296_dll_295_setup
#define dll_295_control __dll296_dll_295_control
#define dll_295_update __dll296_dll_295_update
#define dll_295_print __dll296_dll_295_print
#define dll_295_free __dll296_dll_295_free
#define dll_296_get_model_flags __dll296_dll_296_get_model_flags
#define dll_296_get_data_size __dll296_dll_296_get_data_size
#define dll_296_func_C50 __dll296_dll_296_func_C50
#define _rodata_0 __dll296__rodata_0
#define _rodata_4 __dll296__rodata_4
#define _rodata_8 __dll296__rodata_8
#define _rodata_C __dll296__rodata_C
#define _rodata_10 __dll296__rodata_10
#define _data_0 __dll296__data_0
#define _data_4 __dll296__data_4
#define _data_8 __dll296__data_8
#define _data_20 __dll296__data_20
#define _data_2C __dll296__data_2C
#define _data_34 __dll296__data_34
#define _data_40 __dll296__data_40

#endif //_DLL_296_RECOMP_H
