// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_308_RECOMP_H
#define _DLL_308_RECOMP_H

#define UseObj_ctor __dll308_UseObj_ctor
#define UseObj_dtor __dll308_UseObj_dtor
#define UseObj_obj_Setup __dll308_UseObj_obj_Setup
#define UseObj_obj_Control __dll308_UseObj_obj_Control
#define UseObj_obj_Update __dll308_UseObj_obj_Update
#define UseObj_obj_Print __dll308_UseObj_obj_Print
#define UseObj_obj_Free __dll308_UseObj_obj_Free
#define UseObj_obj_GetModelFlags __dll308_UseObj_obj_GetModelFlags
#define UseObj_obj_GetDataSize __dll308_UseObj_obj_GetDataSize
#define UseObj_animCallback __dll308_UseObj_animCallback
#define str_0 __dll308_str_0

#endif //_DLL_308_RECOMP_H
