// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_318_RECOMP_H
#define _DLL_318_RECOMP_H

#define fish_ctor __dll318_fish_ctor
#define fish_dtor __dll318_fish_dtor
#define fish_setup __dll318_fish_setup
#define fish_func_84 __dll318_fish_func_84
#define fish_control __dll318_fish_control
#define fish_update __dll318_fish_update
#define fish_print __dll318_fish_print
#define fish_free __dll318_fish_free
#define fish_get_model_flags __dll318_fish_get_model_flags
#define fish_get_data_size __dll318_fish_get_data_size
#define fish_func_F74 __dll318_fish_func_F74
#define fish_func_10BC __dll318_fish_func_10BC
#define fish_func_11C8 __dll318_fish_func_11C8
#define fish_func_1880 __dll318_fish_func_1880
#define fish_func_1978 __dll318_fish_func_1978
#define fish_func_1EF4 __dll318_fish_func_1EF4
#define fish_func_2150 __dll318_fish_func_2150

#endif //_DLL_318_RECOMP_H
