// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_321_RECOMP_H
#define _DLL_321_RECOMP_H

#define Duster_ctor __dll321_Duster_ctor
#define Duster_dtor __dll321_Duster_dtor
#define Duster_create __dll321_Duster_create
#define Duster_update __dll321_Duster_update
#define Duster_func_754 __dll321_Duster_func_754
#define Duster_draw __dll321_Duster_draw
#define Duster_destroy __dll321_Duster_destroy
#define Duster_get_model_flags __dll321_Duster_get_model_flags
#define Duster_get_state_size __dll321_Duster_get_state_size
#define str_0 __dll321_str_0

#endif //_DLL_321_RECOMP_H
