// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_326_RECOMP_H
#define _DLL_326_RECOMP_H

#define DLL326_ctor __dll326_DLL326_ctor
#define DLL326_dtor __dll326_DLL326_dtor
#define DLL326_obj_Setup __dll326_DLL326_obj_Setup
#define DLL326_obj_Control __dll326_DLL326_obj_Control
#define DLL326_obj_Update __dll326_DLL326_obj_Update
#define DLL326_obj_Print __dll326_DLL326_obj_Print
#define DLL326_obj_Free __dll326_DLL326_obj_Free
#define DLL326_obj_GetModelFlags __dll326_DLL326_obj_GetModelFlags
#define DLL326_obj_GetDataSize __dll326_DLL326_obj_GetDataSize

#endif //_DLL_326_RECOMP_H
