// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_327_RECOMP_H
#define _DLL_327_RECOMP_H

#define DLL327_ctor __dll327_DLL327_ctor
#define DLL327_dtor __dll327_DLL327_dtor
#define DLL327_obj_Setup __dll327_DLL327_obj_Setup
#define DLL327_obj_Control __dll327_DLL327_obj_Control
#define DLL327_obj_Update __dll327_DLL327_obj_Update
#define DLL327_obj_Print __dll327_DLL327_obj_Print
#define DLL327_obj_Free __dll327_DLL327_obj_Free
#define DLL327_obj_GetModelFlags __dll327_DLL327_obj_GetModelFlags
#define DLL327_obj_GetDataSize __dll327_DLL327_obj_GetDataSize

#endif //_DLL_327_RECOMP_H
