// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_331_RECOMP_H
#define _DLL_331_RECOMP_H

#define dll_331_ctor __dll331_dll_331_ctor
#define dll_331_dtor __dll331_dll_331_dtor
#define dll_331_setup __dll331_dll_331_setup
#define dll_331_control __dll331_dll_331_control
#define dll_331_update __dll331_dll_331_update
#define dll_331_func_1D34 __dll331_dll_331_func_1D34
#define dll_331_print __dll331_dll_331_print
#define dll_331_free __dll331_dll_331_free
#define dll_331_get_model_flags __dll331_dll_331_get_model_flags
#define dll_331_get_data_size __dll331_dll_331_get_data_size
#define str_0 __dll331_str_0
#define str_10 __dll331_str_10
#define str_20 __dll331_str_20
#define str_34 __dll331_str_34
#define str_60 __dll331_str_60
#define str_70 __dll331_str_70
#define str_8C __dll331_str_8C
#define str_9C __dll331_str_9C
#define _rodata_210 __dll331__rodata_210
#define _rodata_214 __dll331__rodata_214
#define _rodata_218 __dll331__rodata_218
#define _rodata_21C __dll331__rodata_21C
#define _rodata_220 __dll331__rodata_220
#define _rodata_224 __dll331__rodata_224
#define _rodata_228 __dll331__rodata_228
#define _rodata_22C __dll331__rodata_22C
#define _rodata_230 __dll331__rodata_230
#define _rodata_234 __dll331__rodata_234
#define _data_0 __dll331__data_0
#define _data_4 __dll331__data_4

#endif //_DLL_331_RECOMP_H
