// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_346_RECOMP_H
#define _DLL_346_RECOMP_H

#define animator_ctor __dll346_animator_ctor
#define animator_dtor __dll346_animator_dtor
#define animator_setup __dll346_animator_setup
#define animator_control __dll346_animator_control
#define animator_update __dll346_animator_update
#define animator_print __dll346_animator_print
#define animator_free __dll346_animator_free
#define animator_get_model_flags __dll346_animator_get_model_flags
#define animator_get_data_size __dll346_animator_get_data_size
#define _oob_rodata_0 __dll346__oob_rodata_0

#endif //_DLL_346_RECOMP_H
