// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_372_RECOMP_H
#define _DLL_372_RECOMP_H

#define CFCrystal_ctor __dll372_CFCrystal_ctor
#define CFCrystal_dtor __dll372_CFCrystal_dtor
#define CFCrystal_obj_Setup __dll372_CFCrystal_obj_Setup
#define CFCrystal_obj_Control __dll372_CFCrystal_obj_Control
#define CFCrystal_obj_Update __dll372_CFCrystal_obj_Update
#define CFCrystal_obj_Print __dll372_CFCrystal_obj_Print
#define CFCrystal_obj_Free __dll372_CFCrystal_obj_Free
#define CFCrystal_obj_GetModelFlags __dll372_CFCrystal_obj_GetModelFlags
#define CFCrystal_obj_GetDataSize __dll372_CFCrystal_obj_GetDataSize
#define CFCrystal_func_288 __dll372_CFCrystal_func_288
#define CFCrystal_func_11B8 __dll372_CFCrystal_func_11B8
#define str_0 __dll372_str_0
#define str_14 __dll372_str_14
#define str_24 __dll372_str_24
#define rodata_34 __dll372_rodata_34
#define rodata_38 __dll372_rodata_38
#define rodata_3C __dll372_rodata_3C
#define rodata_40 __dll372_rodata_40
#define rodata_44 __dll372_rodata_44
#define data_0 __dll372_data_0
#define data_C __dll372_data_C
#define data_10 __dll372_data_10
#define bss_0 __dll372_bss_0

#endif //_DLL_372_RECOMP_H
