// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_413_RECOMP_H
#define _DLL_413_RECOMP_H

#define dll_413_ctor __dll413_dll_413_ctor
#define dll_413_dtor __dll413_dll_413_dtor
#define dll_413_setup __dll413_dll_413_setup
#define dll_413_control __dll413_dll_413_control
#define dll_413_update __dll413_dll_413_update
#define dll_413_print __dll413_dll_413_print
#define dll_413_free __dll413_dll_413_free
#define dll_413_get_model_flags __dll413_dll_413_get_model_flags
#define dll_413_get_data_size __dll413_dll_413_get_data_size
#define dll_413_func_1AC __dll413_dll_413_func_1AC
#define dll_413_func_470 __dll413_dll_413_func_470
#define dll_413_func_4A4 __dll413_dll_413_func_4A4
#define dll_413_func_4BC __dll413_dll_413_func_4BC
#define fxTransform __dll413_fxTransform
#define _bss_0 __dll413__bss_0

#endif //_DLL_413_RECOMP_H
