// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_435_RECOMP_H
#define _DLL_435_RECOMP_H

#define Spirit_ctor __dll435_Spirit_ctor
#define Spirit_dtor __dll435_Spirit_dtor
#define Spirit_setup __dll435_Spirit_setup
#define Spirit_control __dll435_Spirit_control
#define Spirit_update __dll435_Spirit_update
#define Spirit_print __dll435_Spirit_print
#define Spirit_free __dll435_Spirit_free
#define Spirit_get_model_flags __dll435_Spirit_get_model_flags
#define Spirit_get_data_size __dll435_Spirit_get_data_size
#define data_modGfx __dll435_data_modGfx
#define data_lfxEmitter __dll435_data_lfxEmitter

#endif //_DLL_435_RECOMP_H
