// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_454_RECOMP_H
#define _DLL_454_RECOMP_H

#define CCgrub_ctor __dll454_CCgrub_ctor
#define CCgrub_dtor __dll454_CCgrub_dtor
#define CCgrub_setup __dll454_CCgrub_setup
#define CCgrub_control __dll454_CCgrub_control
#define CCgrub_func_AB0 __dll454_CCgrub_func_AB0
#define CCgrub_update __dll454_CCgrub_update
#define CCgrub_print __dll454_CCgrub_print
#define CCgrub_free __dll454_CCgrub_free
#define CCgrub_get_model_flags __dll454_CCgrub_get_model_flags
#define CCgrub_get_data_size __dll454_CCgrub_get_data_size
#define CCgrub_func_BE8 __dll454_CCgrub_func_BE8
#define CCgrub_func_CEC __dll454_CCgrub_func_CEC
#define CCgrub_func_DC4 __dll454_CCgrub_func_DC4
#define CCgrub_func_104C __dll454_CCgrub_func_104C
#define str_0 __dll454_str_0

#endif //_DLL_454_RECOMP_H
