// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_481_RECOMP_H
#define _DLL_481_RECOMP_H

#define dll_481_ctor __dll481_dll_481_ctor
#define dll_481_dtor __dll481_dll_481_dtor
#define dll_481_setup __dll481_dll_481_setup
#define dll_481_control __dll481_dll_481_control
#define dll_481_update __dll481_dll_481_update
#define dll_481_print __dll481_dll_481_print
#define dll_481_free __dll481_dll_481_free
#define dll_481_get_model_flags __dll481_dll_481_get_model_flags
#define dll_481_get_data_size __dll481_dll_481_get_data_size
#define dll_481_func_C10 __dll481_dll_481_func_C10
#define dll_481_func_1084 __dll481_dll_481_func_1084
#define str_0 __dll481_str_0
#define _data_0 __dll481__data_0

#endif //_DLL_481_RECOMP_H
