// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_493_RECOMP_H
#define _DLL_493_RECOMP_H

#define NWsfx_ctor __dll493_NWsfx_ctor
#define NWsfx_dtor __dll493_NWsfx_dtor
#define NWsfx_setup __dll493_NWsfx_setup
#define NWsfx_control __dll493_NWsfx_control
#define NWsfx_update __dll493_NWsfx_update
#define NWsfx_print __dll493_NWsfx_print
#define NWsfx_free __dll493_NWsfx_free
#define NWsfx_get_model_flags __dll493_NWsfx_get_model_flags
#define NWsfx_get_data_size __dll493_NWsfx_get_data_size
#define dSoundIDs __dll493_dSoundIDs

#endif //_DLL_493_RECOMP_H
