// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_498_RECOMP_H
#define _DLL_498_RECOMP_H

#define dll_498_ctor __dll498_dll_498_ctor
#define dll_498_dtor __dll498_dll_498_dtor
#define dll_498_setup __dll498_dll_498_setup
#define dll_498_control __dll498_dll_498_control
#define dll_498_update __dll498_dll_498_update
#define dll_498_print __dll498_dll_498_print
#define dll_498_free __dll498_dll_498_free
#define dll_498_get_model_flags __dll498_dll_498_get_model_flags
#define dll_498_get_data_size __dll498_dll_498_get_data_size
#define dll_498_func_108 __dll498_dll_498_func_108

#endif //_DLL_498_RECOMP_H
