// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_509_RECOMP_H
#define _DLL_509_RECOMP_H

#define dll_509_ctor __dll509_dll_509_ctor
#define dll_509_dtor __dll509_dll_509_dtor
#define dll_509_setup __dll509_dll_509_setup
#define dll_509_control __dll509_dll_509_control
#define dll_509_update __dll509_dll_509_update
#define dll_509_print __dll509_dll_509_print
#define dll_509_free __dll509_dll_509_free
#define dll_509_get_model_flags __dll509_dll_509_get_model_flags
#define dll_509_get_data_size __dll509_dll_509_get_data_size
#define str_0 __dll509_str_0

#endif //_DLL_509_RECOMP_H
