// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_510_RECOMP_H
#define _DLL_510_RECOMP_H

#define dll_510_ctor __dll510_dll_510_ctor
#define dll_510_dtor __dll510_dll_510_dtor
#define dll_510_setup __dll510_dll_510_setup
#define dll_510_control __dll510_dll_510_control
#define dll_510_update __dll510_dll_510_update
#define dll_510_print __dll510_dll_510_print
#define dll_510_free __dll510_dll_510_free
#define dll_510_get_model_flags __dll510_dll_510_get_model_flags
#define dll_510_get_data_size __dll510_dll_510_get_data_size

#endif //_DLL_510_RECOMP_H
