// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_511_RECOMP_H
#define _DLL_511_RECOMP_H

#define SHboulder_ctor __dll511_SHboulder_ctor
#define SHboulder_dtor __dll511_SHboulder_dtor
#define SHboulder_setup __dll511_SHboulder_setup
#define SHboulder_control __dll511_SHboulder_control
#define SHboulder_update __dll511_SHboulder_update
#define SHboulder_print __dll511_SHboulder_print
#define SHboulder_free __dll511_SHboulder_free
#define SHboulder_get_model_flags __dll511_SHboulder_get_model_flags
#define SHboulder_get_data_size __dll511_SHboulder_get_data_size

#endif //_DLL_511_RECOMP_H
