// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_584_RECOMP_H
#define _DLL_584_RECOMP_H

#define SB_Debris_ctor __dll584_SB_Debris_ctor
#define SB_Debris_dtor __dll584_SB_Debris_dtor
#define SB_Debris_setup __dll584_SB_Debris_setup
#define SB_Debris_control __dll584_SB_Debris_control
#define SB_Debris_update __dll584_SB_Debris_update
#define SB_Debris_print __dll584_SB_Debris_print
#define SB_Debris_free __dll584_SB_Debris_free
#define SB_Debris_get_model_flags __dll584_SB_Debris_get_model_flags
#define SB_Debris_get_data_size __dll584_SB_Debris_get_data_size
#define sSpeed __dll584_sSpeed

#endif //_DLL_584_RECOMP_H
