// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_602_RECOMP_H
#define _DLL_602_RECOMP_H

#define dll_602_ctor __dll602_dll_602_ctor
#define dll_602_dtor __dll602_dll_602_dtor
#define dll_602_setup __dll602_dll_602_setup
#define dll_602_control __dll602_dll_602_control
#define dll_602_update __dll602_dll_602_update
#define dll_602_print __dll602_dll_602_print
#define dll_602_free __dll602_dll_602_free
#define dll_602_get_model_flags __dll602_dll_602_get_model_flags
#define dll_602_get_data_size __dll602_dll_602_get_data_size

#endif //_DLL_602_RECOMP_H
