// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_603_RECOMP_H
#define _DLL_603_RECOMP_H

#define WMvein_ctor __dll603_WMvein_ctor
#define WMvein_dtor __dll603_WMvein_dtor
#define WMvein_setup __dll603_WMvein_setup
#define WMvein_control __dll603_WMvein_control
#define WMvein_update __dll603_WMvein_update
#define WMvein_print __dll603_WMvein_print
#define WMvein_free __dll603_WMvein_free
#define WMvein_get_model_flags __dll603_WMvein_get_model_flags
#define WMvein_get_data_size __dll603_WMvein_get_data_size
#define _data_0 __dll603__data_0

#endif //_DLL_603_RECOMP_H
