// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_605_RECOMP_H
#define _DLL_605_RECOMP_H

#define WLWorm_ctor __dll605_WLWorm_ctor
#define WLWorm_dtor __dll605_WLWorm_dtor
#define WLWorm_setup __dll605_WLWorm_setup
#define WLWorm_control __dll605_WLWorm_control
#define WLWorm_update __dll605_WLWorm_update
#define WLWorm_print __dll605_WLWorm_print
#define WLWorm_free __dll605_WLWorm_free
#define WLWorm_get_model_flags __dll605_WLWorm_get_model_flags
#define WLWorm_get_data_size __dll605_WLWorm_get_data_size
#define _data_0 __dll605__data_0

#endif //_DLL_605_RECOMP_H
