// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_614_RECOMP_H
#define _DLL_614_RECOMP_H

#define WMPlanets_ctor __dll614_WMPlanets_ctor
#define WMPlanets_dtor __dll614_WMPlanets_dtor
#define WMPlanets_setup __dll614_WMPlanets_setup
#define WMPlanets_control __dll614_WMPlanets_control
#define WMPlanets_update __dll614_WMPlanets_update
#define WMPlanets_print __dll614_WMPlanets_print
#define WMPlanets_free __dll614_WMPlanets_free
#define WMPlanets_get_model_flags __dll614_WMPlanets_get_model_flags
#define WMPlanets_get_data_size __dll614_WMPlanets_get_data_size
#define _data_0 __dll614__data_0

#endif //_DLL_614_RECOMP_H
