// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_638_RECOMP_H
#define _DLL_638_RECOMP_H

#define dll_638_ctor __dll638_dll_638_ctor
#define dll_638_dtor __dll638_dll_638_dtor
#define dll_638_func_18 __dll638_dll_638_func_18
#define dll_638_func_260 __dll638_dll_638_func_260
#define dll_638_func_51C __dll638_dll_638_func_51C
#define dll_638_func_528 __dll638_dll_638_func_528
#define dll_638_func_540 __dll638_dll_638_func_540
#define dll_638_get_model_flags __dll638_dll_638_get_model_flags
#define dll_638_get_state_size __dll638_dll_638_get_state_size
#define dll_638_func_5E4 __dll638_dll_638_func_5E4
#define dll_638_func_62C __dll638_dll_638_func_62C
#define dll_638_func_6C4 __dll638_dll_638_func_6C4
#define dll_638_func_B2C __dll638_dll_638_func_B2C
#define dll_638_func_ECC __dll638_dll_638_func_ECC
#define _data_0 __dll638__data_0
#define _data_4 __dll638__data_4
#define _data_10 __dll638__data_10
#define _data_14 __dll638__data_14
#define _data_18 __dll638__data_18
#define _data_1C __dll638__data_1C
#define _data_20 __dll638__data_20
#define _data_24 __dll638__data_24

#endif //_DLL_638_RECOMP_H
