// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_668_RECOMP_H
#define _DLL_668_RECOMP_H

#define DBdiamond_ctor __dll668_DBdiamond_ctor
#define DBdiamond_dtor __dll668_DBdiamond_dtor
#define DBdiamond_create __dll668_DBdiamond_create
#define DBdiamond_update __dll668_DBdiamond_update
#define DBdiamond_func_204 __dll668_DBdiamond_func_204
#define DBdiamond_draw __dll668_DBdiamond_draw
#define DBdiamond_destroy __dll668_DBdiamond_destroy
#define DBdiamond_func_2BC __dll668_DBdiamond_func_2BC
#define DBdiamond_get_state_size __dll668_DBdiamond_get_state_size

#endif //_DLL_668_RECOMP_H
