// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_668_RECOMP_H
#define _DLL_668_RECOMP_H

#define dll_668_ctor __dll668_dll_668_ctor
#define dll_668_dtor __dll668_dll_668_dtor
#define dll_668_func_18 __dll668_dll_668_func_18
#define dll_668_func_D0 __dll668_dll_668_func_D0
#define dll_668_func_204 __dll668_dll_668_func_204
#define dll_668_func_210 __dll668_dll_668_func_210
#define dll_668_func_27C __dll668_dll_668_func_27C
#define dll_668_func_2BC __dll668_dll_668_func_2BC
#define dll_668_func_2CC __dll668_dll_668_func_2CC

#endif //_DLL_668_RECOMP_H
