// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_767_RECOMP_H
#define _DLL_767_RECOMP_H

#define SPItem_ctor __dll767_SPItem_ctor
#define SPItem_dtor __dll767_SPItem_dtor
#define SPItem_setup __dll767_SPItem_setup
#define SPItem_control __dll767_SPItem_control
#define SPItem_update __dll767_SPItem_update
#define SPItem_print __dll767_SPItem_print
#define SPItem_free __dll767_SPItem_free
#define SPItem_get_model_flags __dll767_SPItem_get_model_flags
#define SPItem_get_data_size __dll767_SPItem_get_data_size
#define SPItem_anim_callback __dll767_SPItem_anim_callback
#define SPItem_bought_callback __dll767_SPItem_bought_callback

#endif //_DLL_767_RECOMP_H
