// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_775_RECOMP_H
#define _DLL_775_RECOMP_H

#define WCTrex_func_0 __dll775_WCTrex_func_0
#define WCTrex_ctor __dll775_WCTrex_ctor
#define WCTrex_dtor __dll775_WCTrex_dtor
#define WCTrex_setup __dll775_WCTrex_setup
#define WCTrex_control __dll775_WCTrex_control
#define WCTrex_update __dll775_WCTrex_update
#define WCTrex_print __dll775_WCTrex_print
#define WCTrex_free __dll775_WCTrex_free
#define WCTrex_get_model_flags __dll775_WCTrex_get_model_flags
#define WCTrex_get_data_size __dll775_WCTrex_get_data_size
#define WCTrex_func_4A8 __dll775_WCTrex_func_4A8
#define WCTrex_func_584 __dll775_WCTrex_func_584
#define WCTrex_func_59C __dll775_WCTrex_func_59C
#define WCTrex_func_608 __dll775_WCTrex_func_608
#define WCTrex_func_728 __dll775_WCTrex_func_728
#define WCTrex_func_7E8 __dll775_WCTrex_func_7E8
#define WCTrex_func_800 __dll775_WCTrex_func_800
#define WCTrex_func_8DC __dll775_WCTrex_func_8DC
#define WCTrex_func_9E4 __dll775_WCTrex_func_9E4
#define str_0 __dll775_str_0
#define data_0 __dll775_data_0
#define data_10 __dll775_data_10
#define bss_0 __dll775_bss_0
#define bss_10 __dll775_bss_10

#endif //_DLL_775_RECOMP_H
