// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_109_RECOMP_H
#define _DLL_109_RECOMP_H

#define dll_109_ctor __dll109_dll_109_ctor
#define dll_109_dtor __dll109_dll_109_dtor
#define dll_109_modgfx_Func0 __dll109_dll_109_modgfx_Func0
#define data_0 __dll109_data_0
#define data_D4 __dll109_data_D4
#define data_174 __dll109_data_174
#define data_1B0 __dll109_data_1B0
#define data_1DC __dll109_data_1DC

#endif //_DLL_109_RECOMP_H
