// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_112_RECOMP_H
#define _DLL_112_RECOMP_H

#define dll_112_ctor __dll112_dll_112_ctor
#define dll_112_dtor __dll112_dll_112_dtor
#define dll_112_modgfx_Func0 __dll112_dll_112_modgfx_Func0
#define data_0 __dll112_data_0
#define data_8C __dll112_data_8C
#define data_F4 __dll112_data_F4
#define data_118 __dll112_data_118
#define data_12C __dll112_data_12C

#endif //_DLL_112_RECOMP_H
