// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_25_RECOMP_H
#define _DLL_25_RECOMP_H

#define errorMsg __dll25_errorMsg
#define _bss_0 __dll25__bss_0
#define _bss_DC __dll25__bss_DC
#define _bss_E0 __dll25__bss_E0
#define _bss_E4 __dll25__bss_E4
#define _bss_E8 __dll25__bss_E8
#define dll_25_func_D00 __dll25_dll_25_func_D00
#define dll_25_func_DF8 __dll25_dll_25_func_DF8
#define _data_400 __dll25__data_400
#define dll_25_func_EAC __dll25_dll_25_func_EAC
#define _rodata_40 __dll25__rodata_40
#define dll_25_func_1864 __dll25_dll_25_func_1864
#define dll_25_func_29FC __dll25_dll_25_func_29FC
#define _rodata_48 __dll25__rodata_48
#define dll_25_func_1A2C __dll25_dll_25_func_1A2C
#define dll_25_func_1D30 __dll25_dll_25_func_1D30
#define dll_25_func_15B0 __dll25_dll_25_func_15B0
#define dll_25_func_D8 __dll25_dll_25_func_D8
#define dll_25_func_12FC __dll25_dll_25_func_12FC
#define dll_25_func_27A8 __dll25_dll_25_func_27A8
#define _rodata_30 __dll25__rodata_30
#define dll_25_func_16D4 __dll25_dll_25_func_16D4
#define dll_25_func_1474 __dll25_dll_25_func_1474
#define _data_0 __dll25__data_0
#define dll_25_ctor __dll25_dll_25_ctor
#define _rodata_34 __dll25__rodata_34
#define dll_25_func_1158 __dll25_dll_25_func_1158
#define dll_25_func_21F4 __dll25_dll_25_func_21F4
#define dll_25_dtor __dll25_dll_25_dtor
#define dll_25_func_2BC4 __dll25_dll_25_func_2BC4
#define _rodata_38 __dll25__rodata_38
#define dll_25_func_2CF8 __dll25_dll_25_func_2CF8
#define _rodata_2C __dll25__rodata_2C
#define _rodata_28 __dll25__rodata_28
#define dll_25_func_2A50 __dll25_dll_25_func_2A50
#define _rodata_24 __dll25__rodata_24
#define _rodata_3C __dll25__rodata_3C
#define _rodata_44 __dll25__rodata_44

#endif //_DLL_25_RECOMP_H
