// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_36_RECOMP_H
#define _DLL_36_RECOMP_H

#define dimPartfx_ctor __dll36_dimPartfx_ctor
#define dimPartfx_dtor __dll36_dimPartfx_dtor
#define dimPartfx_Func_18 __dll36_dimPartfx_Func_18
#define dimPartfx_Func_20 __dll36_dimPartfx_Func_20
#define dimPartfx_Spawn __dll36_dimPartfx_Spawn
#define bss_0 __dll36_bss_0

#endif //_DLL_36_RECOMP_H
