// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_42_RECOMP_H
#define _DLL_42_RECOMP_H

#define bayPartfx_ctor __dll42_bayPartfx_ctor
#define bayPartfx_dtor __dll42_bayPartfx_dtor
#define bayPartfx_Func_18 __dll42_bayPartfx_Func_18
#define bayPartfx_Func_20 __dll42_bayPartfx_Func_20
#define bayPartfx_Spawn __dll42_bayPartfx_Spawn
#define data_0 __dll42_data_0
#define data_40 __dll42_data_40
#define data_44 __dll42_data_44
#define data_48 __dll42_data_48
#define data_4C __dll42_data_4C
#define data_50 __dll42_data_50
#define data_54 __dll42_data_54
#define data_58 __dll42_data_58
#define data_5C __dll42_data_5C
#define bss_0 __dll42_bss_0

#endif //_DLL_42_RECOMP_H
