// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_45_RECOMP_H
#define _DLL_45_RECOMP_H

#define rexPartfx_ctor __dll45_rexPartfx_ctor
#define rexPartfx_dtor __dll45_rexPartfx_dtor
#define rexPartfx_Func_18 __dll45_rexPartfx_Func_18
#define rexPartfx_Func_20 __dll45_rexPartfx_Func_20
#define rexPartfx_Spawn __dll45_rexPartfx_Spawn
#define bss_0 __dll45_bss_0

#endif //_DLL_45_RECOMP_H
