// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_48_RECOMP_H
#define _DLL_48_RECOMP_H

#define swhPartfx_ctor __dll48_swhPartfx_ctor
#define swhPartfx_dtor __dll48_swhPartfx_dtor
#define swhPartfx_Func_18 __dll48_swhPartfx_Func_18
#define swhPartfx_Func_20 __dll48_swhPartfx_Func_20
#define swhPartfx_Spawn __dll48_swhPartfx_Spawn
#define bss_0 __dll48_bss_0

#endif //_DLL_48_RECOMP_H
