// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_54_RECOMP_H
#define _DLL_54_RECOMP_H

#define dll_54_ctor __dll54_dll_54_ctor
#define dll_54_dtor __dll54_dll_54_dtor
#define dll_54_func_18 __dll54_dll_54_func_18
#define dll_54_func_64 __dll54_dll_54_func_64
#define dll_54_func_5DC __dll54_dll_54_func_5DC
#define dll_54_func_664 __dll54_dll_54_func_664
#define dll_54_func_6A0 __dll54_dll_54_func_6A0
#define dll_54_func_6AC __dll54_dll_54_func_6AC
#define dll_54_func_6C0 __dll54_dll_54_func_6C0
#define dll_54_func_6CC __dll54_dll_54_func_6CC
#define dll_54_func_704 __dll54_dll_54_func_704
#define dll_54_func_73C __dll54_dll_54_func_73C
#define dll_54_func_760 __dll54_dll_54_func_760
#define dll_54_func_798 __dll54_dll_54_func_798
#define dll_54_func_838 __dll54_dll_54_func_838
#define _rodata_0 __dll54__rodata_0

#endif //_DLL_54_RECOMP_H
