// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_55_RECOMP_H
#define _DLL_55_RECOMP_H

#define projlib_ctor __dll55_projlib_ctor
#define projlib_dtor __dll55_projlib_dtor
#define projlib_Func_18 __dll55_projlib_Func_18
#define projlib_Func_304 __dll55_projlib_Func_304
#define projlib_Func_580 __dll55_projlib_Func_580
#define str_0 __dll55_str_0

#endif //_DLL_55_RECOMP_H
