// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_59_RECOMP_H
#define _DLL_59_RECOMP_H

#define minimap_ctor __dll59_minimap_ctor
#define minimap_dtor __dll59_minimap_dtor
#define minimap_toggle __dll59_minimap_toggle
#define minimap_toggle_via_cmdmenu __dll59_minimap_toggle_via_cmdmenu
#define minimap_print __dll59_minimap_print
#define sLoadedTexTableID __dll59_sLoadedTexTableID
#define sMinimapVisible __dll59_sMinimapVisible
#define sOpacity __dll59_sOpacity
#define sMapTile __dll59_sMapTile
#define sMarkerSidekick __dll59_sMarkerSidekick
#define sMarkerPlayer __dll59_sMarkerPlayer
#define sOffsetX __dll59_sOffsetX
#define sOffsetY __dll59_sOffsetY
#define sGridX __dll59_sGridX
#define sGridZ __dll59_sGridZ
#define sLevelMaxX __dll59_sLevelMaxX
#define sLevelMaxZ __dll59_sLevelMaxZ
#define sLevelMinX __dll59_sLevelMinX
#define sLevelMinZ __dll59_sLevelMinZ
#define sTilesVFPT __dll59_sTilesVFPT
#define sTilesDIMExterior __dll59_sTilesDIMExterior
#define sTilesDIMInterior __dll59_sTilesDIMInterior
#define sTilesGaladon __dll59_sTilesGaladon
#define sTilesSW __dll59_sTilesSW
#define sTilesIMHotSpringA __dll59_sTilesIMHotSpringA
#define sTilesIMHotSpringB __dll59_sTilesIMHotSpringB
#define sTilesCRF __dll59_sTilesCRF
#define sTilesSC __dll59_sTilesSC
#define sTilesSH __dll59_sTilesSH
#define sTilesSHWell __dll59_sTilesSHWell
#define sTilesDF __dll59_sTilesDF
#define sTilesCRFTrack __dll59_sTilesCRFTrack
#define sTilesDRTop __dll59_sTilesDRTop
#define sTilesDRBottom __dll59_sTilesDRBottom
#define sTilesGP __dll59_sTilesGP
#define sTilesBWC __dll59_sTilesBWC
#define sTilesKP __dll59_sTilesKP
#define sTilesWG __dll59_sTilesWG
#define sTilesDFPTTop __dll59_sTilesDFPTTop
#define sTilesDFTPBottom __dll59_sTilesDFTPBottom
#define sTilesWC __dll59_sTilesWC
#define sTilesDB __dll59_sTilesDB
#define sTilesCC __dll59_sTilesCC
#define sTilesMMP __dll59_sTilesMMP
#define sTilesIM __dll59_sTilesIM
#define sTilesWM __dll59_sTilesWM
#define sMinimapLevels __dll59_sMinimapLevels

#endif //_DLL_59_RECOMP_H
