// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_61_RECOMP_H
#define _DLL_61_RECOMP_H

#define rareware_ctor __dll61_rareware_ctor
#define rareware_dtor __dll61_rareware_dtor
#define rareware_update1 __dll61_rareware_update1
#define rareware_update2 __dll61_rareware_update2
#define rareware_draw __dll61_rareware_draw
#define dFrame __dll61_dFrame
#define dState __dll61_dState
#define dColourUnused __dll61_dColourUnused
#define sFadeOutStarted __dll61_sFadeOutStarted
#define sFadeOutTimer __dll61_sFadeOutTimer
#define sCutToNextScreen __dll61_sCutToNextScreen
#define sLogoTimer __dll61_sLogoTimer
#define sGlowTimer __dll61_sGlowTimer
#define sTexRareLogo __dll61_sTexRareLogo
#define sTexRareLogoGlow __dll61_sTexRareLogoGlow
#define sTexRareware __dll61_sTexRareware
#define sTexRarewareGlow __dll61_sTexRarewareGlow

#endif //_DLL_61_RECOMP_H
