// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_69_RECOMP_H
#define _DLL_69_RECOMP_H

#define dll_69_ctor __dll69_dll_69_ctor
#define dll_69_dtor __dll69_dll_69_dtor
#define dll_69_update1 __dll69_dll_69_update1
#define dll_69_update2 __dll69_dll_69_update2
#define dll_69_draw __dll69_dll_69_draw

#endif //_DLL_69_RECOMP_H
