// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_72_RECOMP_H
#define _DLL_72_RECOMP_H

#define dll_72_ctor __dll72_dll_72_ctor
#define dll_72_dtor __dll72_dll_72_dtor
#define dll_72_update1 __dll72_dll_72_update1
#define dll_72_update2 __dll72_dll_72_update2
#define dll_72_draw __dll72_dll_72_draw
#define dTexTiles __dll72_dTexTiles

#endif //_DLL_72_RECOMP_H
