// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_90_RECOMP_H
#define _DLL_90_RECOMP_H

#define camstatic_ctor __dll90_camstatic_ctor
#define camstatic_dtor __dll90_camstatic_dtor
#define camstatic_func_18 __dll90_camstatic_func_18
#define camstatic_func_278 __dll90_camstatic_func_278
#define camstatic_func_584 __dll90_camstatic_func_584
#define camstatic_func_5C4 __dll90_camstatic_func_5C4
#define camstatic_func_5D4 __dll90_camstatic_func_5D4
#define camstatic_func_798 __dll90_camstatic_func_798
#define camstatic_func_C04 __dll90_camstatic_func_C04
#define sState __dll90_sState

#endif //_DLL_90_RECOMP_H
