// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_92_RECOMP_H
#define _DLL_92_RECOMP_H

#define camshipbattle_ctor __dll92_camshipbattle_ctor
#define camshipbattle_dtor __dll92_camshipbattle_dtor
#define camshipbattle_setup __dll92_camshipbattle_setup
#define camshipbattle_control __dll92_camshipbattle_control
#define camshipbattle_free __dll92_camshipbattle_free
#define camshipbattle_func_50C __dll92_camshipbattle_func_50C
#define sState __dll92_sState

#endif //_DLL_92_RECOMP_H
