// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_93_RECOMP_H
#define _DLL_93_RECOMP_H

#define camclimb_ctor __dll93_camclimb_ctor
#define camclimb_dtor __dll93_camclimb_dtor
#define camclimb_setup __dll93_camclimb_setup
#define camclimb_control __dll93_camclimb_control
#define camclimb_free __dll93_camclimb_free
#define camclimb_func_62C __dll93_camclimb_func_62C
#define camclimb_ease __dll93_camclimb_ease
#define sState __dll93_sState

#endif //_DLL_93_RECOMP_H
