// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_94_RECOMP_H
#define _DLL_94_RECOMP_H

#define camseq_ctor __dll94_camseq_ctor
#define camseq_dtor __dll94_camseq_dtor
#define camseq_setup __dll94_camseq_setup
#define camseq_control __dll94_camseq_control
#define camseq_free __dll94_camseq_free
#define camseq_func_7C __dll94_camseq_func_7C

#endif //_DLL_94_RECOMP_H
