// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_100_RECOMP_H
#define _DLL_100_RECOMP_H

#define dll_100_ctor __dll100_dll_100_ctor
#define dll_100_dtor __dll100_dll_100_dtor
#define dll_100_func_18 __dll100_dll_100_func_18
#define dll_100_func_64 __dll100_dll_100_func_64
#define dll_100_func_2C8 __dll100_dll_100_func_2C8
#define dll_100_func_2D4 __dll100_dll_100_func_2D4
#define dll_100_func_2E4 __dll100_dll_100_func_2E4
#define _data_0 __dll100__data_0
#define _bss_0 __dll100__bss_0
#define _bss_4 __dll100__bss_4

#endif //_DLL_100_RECOMP_H
