// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_106_RECOMP_H
#define _DLL_106_RECOMP_H

#define dll_106_ctor __dll106_dll_106_ctor
#define dll_106_dtor __dll106_dll_106_dtor
#define dll_106_func_18 __dll106_dll_106_func_18
#define _data_0 __dll106__data_0
#define _data_20 __dll106__data_20
#define _data_48 __dll106__data_48
#define _data_50 __dll106__data_50
#define _data_5C __dll106__data_5C
#define _data_64 __dll106__data_64
#define _data_6C __dll106__data_6C
#define _data_6E __dll106__data_6E
#define _data_70 __dll106__data_70

#endif //_DLL_106_RECOMP_H
