// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_108_RECOMP_H
#define _DLL_108_RECOMP_H

#define dll_108_ctor __dll108_dll_108_ctor
#define dll_108_dtor __dll108_dll_108_dtor
#define dll_108_func_18 __dll108_dll_108_func_18
#define _rodata_0 __dll108__rodata_0
#define _rodata_4 __dll108__rodata_4
#define _data_0 __dll108__data_0
#define _data_D4 __dll108__data_D4
#define _data_174 __dll108__data_174
#define _data_1B0 __dll108__data_1B0
#define _data_1DC __dll108__data_1DC
#define _data_1DE __dll108__data_1DE
#define _data_1E0 __dll108__data_1E0

#endif //_DLL_108_RECOMP_H
