// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_110_RECOMP_H
#define _DLL_110_RECOMP_H

#define dll_110_ctor __dll110_dll_110_ctor
#define dll_110_dtor __dll110_dll_110_dtor
#define dll_110_func_18 __dll110_dll_110_func_18
#define rodata_0 __dll110_rodata_0
#define rodata_4 __dll110_rodata_4
#define rodata_8 __dll110_rodata_8
#define data_0 __dll110_data_0
#define data_168 __dll110_data_168
#define data_1C8 __dll110_data_1C8
#define data_1DC __dll110_data_1DC
#define data_1F0 __dll110_data_1F0
#define data_204 __dll110_data_204
#define data_260 __dll110_data_260
#define data_2A8 __dll110_data_2A8
#define data_2CC __dll110_data_2CC

#endif //_DLL_110_RECOMP_H
