// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_111_RECOMP_H
#define _DLL_111_RECOMP_H

#define dll_111_ctor __dll111_dll_111_ctor
#define dll_111_dtor __dll111_dll_111_dtor
#define dll_111_func_18 __dll111_dll_111_func_18
#define _rodata_0 __dll111__rodata_0
#define _rodata_4 __dll111__rodata_4
#define _data_0 __dll111__data_0
#define _data_8C __dll111__data_8C
#define _data_D4 __dll111__data_D4
#define _data_F0 __dll111__data_F0
#define _data_100 __dll111__data_100
#define _data_110 __dll111__data_110
#define _data_112 __dll111__data_112
#define _data_114 __dll111__data_114

#endif //_DLL_111_RECOMP_H
