// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_114_RECOMP_H
#define _DLL_114_RECOMP_H

#define dll_114_ctor __dll114_dll_114_ctor
#define dll_114_dtor __dll114_dll_114_dtor
#define dll_114_func_18 __dll114_dll_114_func_18
#define _rodata_0 __dll114__rodata_0
#define _rodata_4 __dll114__rodata_4
#define _rodata_8 __dll114__rodata_8
#define _data_0 __dll114__data_0
#define _data_D4 __dll114__data_D4
#define _data_174 __dll114__data_174
#define _data_184 __dll114__data_184
#define _data_194 __dll114__data_194
#define _data_1B0 __dll114__data_1B0
#define _data_1DC __dll114__data_1DC
#define _data_1DE __dll114__data_1DE
#define _data_1E0 __dll114__data_1E0

#endif //_DLL_114_RECOMP_H
