// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_116_RECOMP_H
#define _DLL_116_RECOMP_H

#define dll_116_ctor __dll116_dll_116_ctor
#define dll_116_dtor __dll116_dll_116_dtor
#define dll_116_func_18 __dll116_dll_116_func_18
#define rodata_0 __dll116_rodata_0
#define rodata_4 __dll116_rodata_4
#define rodata_8 __dll116_rodata_8
#define data_0 __dll116_data_0
#define data_8C __dll116_data_8C
#define data_D4 __dll116_data_D4
#define data_F0 __dll116_data_F0
#define data_100 __dll116_data_100
#define data_110 __dll116_data_110
#define data_112 __dll116_data_112
#define data_114 __dll116_data_114

#endif //_DLL_116_RECOMP_H
