// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_11_RECOMP_H
#define _DLL_11_RECOMP_H

#define dll_11_ctor __dll11_dll_11_ctor
#define dll_11_dtor __dll11_dll_11_dtor
#define dll_11_func_18 __dll11_dll_11_func_18
#define dll_11_func_384 __dll11_dll_11_func_384
#define dll_11_func_488 __dll11_dll_11_func_488
#define dll_11_func_828 __dll11_dll_11_func_828
#define dll_11_func_874 __dll11_dll_11_func_874
#define dll_11_func_9D8 __dll11_dll_11_func_9D8
#define dll_11_func_BB8 __dll11_dll_11_func_BB8
#define dll_11_func_D44 __dll11_dll_11_func_D44
#define dll_11_func_1890 __dll11_dll_11_func_1890
#define dll_11_func_1EB0 __dll11_dll_11_func_1EB0
#define dll_11_func_2184 __dll11_dll_11_func_2184
#define dll_11_func_21FC __dll11_dll_11_func_21FC
#define str_0 __dll11_str_0
#define _rodata_B8 __dll11__rodata_B8
#define _rodata_BC __dll11__rodata_BC
#define _rodata_C0 __dll11__rodata_C0
#define _rodata_C4 __dll11__rodata_C4
#define _rodata_C8 __dll11__rodata_C8
#define _data_0 __dll11__data_0
#define _data_4 __dll11__data_4
#define _data_8 __dll11__data_8
#define _data_C __dll11__data_C
#define _data_10 __dll11__data_10
#define _data_18 __dll11__data_18
#define _bss_0 __dll11__bss_0
#define _bss_4 __dll11__bss_4
#define _bss_8 __dll11__bss_8
#define _bss_78 __dll11__bss_78
#define _bss_168 __dll11__bss_168
#define _bss_178 __dll11__bss_178

#endif //_DLL_11_RECOMP_H
