// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_123_RECOMP_H
#define _DLL_123_RECOMP_H

#define dll_123_ctor __dll123_dll_123_ctor
#define dll_123_dtor __dll123_dll_123_dtor
#define dll_123_func_18 __dll123_dll_123_func_18
#define rodata_0 __dll123_rodata_0
#define data_0 __dll123_data_0
#define data_34 __dll123_data_34
#define data_54 __dll123_data_54
#define data_6C __dll123_data_6C
#define data_6E __dll123_data_6E
#define data_70 __dll123_data_70

#endif //_DLL_123_RECOMP_H
