// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_123_RECOMP_H
#define _DLL_123_RECOMP_H

#define dll_123_ctor __dll123_dll_123_ctor
#define dll_123_dtor __dll123_dll_123_dtor
#define dll_123_func_18 __dll123_dll_123_func_18
#define _rodata_0 __dll123__rodata_0
#define _data_0 __dll123__data_0
#define _data_34 __dll123__data_34
#define _data_54 __dll123__data_54
#define _data_6C __dll123__data_6C
#define _data_6E __dll123__data_6E
#define _data_70 __dll123__data_70

#endif //_DLL_123_RECOMP_H
