// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_125_RECOMP_H
#define _DLL_125_RECOMP_H

#define dll_125_ctor __dll125_dll_125_ctor
#define dll_125_dtor __dll125_dll_125_dtor
#define dll_125_func_18 __dll125_dll_125_func_18
#define _rodata_0 __dll125__rodata_0
#define _rodata_4 __dll125__rodata_4
#define _data_0 __dll125__data_0
#define _data_8C __dll125__data_8C
#define _data_D4 __dll125__data_D4
#define _data_F0 __dll125__data_F0
#define _data_100 __dll125__data_100
#define _data_110 __dll125__data_110
#define _data_112 __dll125__data_112
#define _data_114 __dll125__data_114

#endif //_DLL_125_RECOMP_H
