// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_127_RECOMP_H
#define _DLL_127_RECOMP_H

#define dll_127_ctor __dll127_dll_127_ctor
#define dll_127_dtor __dll127_dll_127_dtor
#define dll_127_func_18 __dll127_dll_127_func_18
#define _rodata_0 __dll127__rodata_0
#define _data_0 __dll127__data_0
#define _data_F0 __dll127__data_F0
#define _data_150 __dll127__data_150
#define _data_158 __dll127__data_158
#define _data_188 __dll127__data_188
#define _data_198 __dll127__data_198
#define _data_1B0 __dll127__data_1B0
#define _data_1B2 __dll127__data_1B2
#define _data_1B4 __dll127__data_1B4

#endif //_DLL_127_RECOMP_H
