// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_137_RECOMP_H
#define _DLL_137_RECOMP_H

#define dll_137_ctor __dll137_dll_137_ctor
#define dll_137_dtor __dll137_dll_137_dtor
#define dll_137_func_18 __dll137_dll_137_func_18
#define _rodata_0 __dll137__rodata_0
#define _rodata_4 __dll137__rodata_4
#define _rodata_8 __dll137__rodata_8
#define _rodata_C __dll137__rodata_C
#define _rodata_10 __dll137__rodata_10
#define _rodata_14 __dll137__rodata_14
#define _rodata_18 __dll137__rodata_18
#define _rodata_1C __dll137__rodata_1C
#define _rodata_20 __dll137__rodata_20
#define _data_0 __dll137__data_0
#define _data_5C __dll137__data_5C
#define _data_8C __dll137__data_8C
#define _data_A4 __dll137__data_A4
#define _data_B4 __dll137__data_B4
#define _data_BC __dll137__data_BC
#define _data_BE __dll137__data_BE
#define _data_C0 __dll137__data_C0

#endif //_DLL_137_RECOMP_H
