// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_140_RECOMP_H
#define _DLL_140_RECOMP_H

#define dll_140_ctor __dll140_dll_140_ctor
#define dll_140_dtor __dll140_dll_140_dtor
#define dll_140_func_18 __dll140_dll_140_func_18
#define rodata_0 __dll140_rodata_0
#define rodata_4 __dll140_rodata_4
#define rodata_8 __dll140_rodata_8
#define rodata_C __dll140_rodata_C
#define rodata_10 __dll140_rodata_10
#define data_0 __dll140_data_0
#define data_D4 __dll140_data_D4
#define data_164 __dll140_data_164
#define data_174 __dll140_data_174
#define data_1B0 __dll140_data_1B0
#define data_1F8 __dll140_data_1F8
#define data_1FA __dll140_data_1FA
#define data_1FC __dll140_data_1FC

#endif //_DLL_140_RECOMP_H
