// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_140_RECOMP_H
#define _DLL_140_RECOMP_H

#define dll_140_ctor __dll140_dll_140_ctor
#define dll_140_dtor __dll140_dll_140_dtor
#define dll_140_func_18 __dll140_dll_140_func_18
#define _rodata_0 __dll140__rodata_0
#define _rodata_4 __dll140__rodata_4
#define _rodata_8 __dll140__rodata_8
#define _rodata_C __dll140__rodata_C
#define _rodata_10 __dll140__rodata_10
#define _data_0 __dll140__data_0
#define _data_D4 __dll140__data_D4
#define _data_164 __dll140__data_164
#define _data_174 __dll140__data_174
#define _data_1B0 __dll140__data_1B0
#define _data_1F8 __dll140__data_1F8
#define _data_1FA __dll140__data_1FA
#define _data_1FC __dll140__data_1FC

#endif //_DLL_140_RECOMP_H
