// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_143_RECOMP_H
#define _DLL_143_RECOMP_H

#define dll_143_ctor __dll143_dll_143_ctor
#define dll_143_dtor __dll143_dll_143_dtor
#define dll_143_func_18 __dll143_dll_143_func_18
#define rodata_0 __dll143_rodata_0
#define rodata_4 __dll143_rodata_4
#define rodata_8 __dll143_rodata_8
#define rodata_C __dll143_rodata_C
#define rodata_10 __dll143_rodata_10
#define data_0 __dll143_data_0
#define data_5C __dll143_data_5C
#define data_B8 __dll143_data_B8
#define data_E8 __dll143_data_E8
#define data_FC __dll143_data_FC
#define data_100 __dll143_data_100
#define data_110 __dll143_data_110
#define data_112 __dll143_data_112
#define data_114 __dll143_data_114

#endif //_DLL_143_RECOMP_H
