// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_149_RECOMP_H
#define _DLL_149_RECOMP_H

#define dll_149_ctor __dll149_dll_149_ctor
#define dll_149_dtor __dll149_dll_149_dtor
#define dll_149_func_18 __dll149_dll_149_func_18
#define _rodata_0 __dll149__rodata_0
#define _rodata_4 __dll149__rodata_4
#define _data_0 __dll149__data_0
#define _data_28 __dll149__data_28
#define _data_38 __dll149__data_38
#define _data_3C __dll149__data_3C
#define _data_44 __dll149__data_44
#define _data_48 __dll149__data_48
#define _data_4A __dll149__data_4A
#define _data_4C __dll149__data_4C
#define _data_58 __dll149__data_58

#endif //_DLL_149_RECOMP_H
