// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_155_RECOMP_H
#define _DLL_155_RECOMP_H

#define dll_155_ctor __dll155_dll_155_ctor
#define dll_155_dtor __dll155_dll_155_dtor
#define dll_155_func_18 __dll155_dll_155_func_18
#define _rodata_0 __dll155__rodata_0
#define _rodata_4 __dll155__rodata_4
#define _rodata_8 __dll155__rodata_8
#define _rodata_C __dll155__rodata_C
#define _rodata_10 __dll155__rodata_10
#define _rodata_14 __dll155__rodata_14
#define _rodata_18 __dll155__rodata_18
#define _rodata_1C __dll155__rodata_1C
#define _rodata_20 __dll155__rodata_20
#define _rodata_24 __dll155__rodata_24
#define _rodata_28 __dll155__rodata_28
#define _rodata_40 __dll155__rodata_40
#define _rodata_44 __dll155__rodata_44
#define _data_0 __dll155__data_0
#define _data_D4 __dll155__data_D4
#define _data_1B0 __dll155__data_1B0
#define _data_1F8 __dll155__data_1F8
#define _data_1FA __dll155__data_1FA
#define _data_1FC __dll155__data_1FC

#endif //_DLL_155_RECOMP_H
