// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_157_RECOMP_H
#define _DLL_157_RECOMP_H

#define dll_157_ctor __dll157_dll_157_ctor
#define dll_157_dtor __dll157_dll_157_dtor
#define dll_157_func_18 __dll157_dll_157_func_18
#define rodata_0 __dll157_rodata_0
#define rodata_4 __dll157_rodata_4
#define rodata_8 __dll157_rodata_8
#define rodata_C __dll157_rodata_C
#define rodata_10 __dll157_rodata_10
#define rodata_14 __dll157_rodata_14
#define rodata_18 __dll157_rodata_18
#define rodata_1C __dll157_rodata_1C
#define data_0 __dll157_data_0
#define data_5C __dll157_data_5C
#define data_8C __dll157_data_8C
#define data_B4 __dll157_data_B4
#define data_B6 __dll157_data_B6
#define data_B8 __dll157_data_B8

#endif //_DLL_157_RECOMP_H
