// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_160_RECOMP_H
#define _DLL_160_RECOMP_H

#define dll_160_ctor __dll160_dll_160_ctor
#define dll_160_dtor __dll160_dll_160_dtor
#define dll_160_func_18 __dll160_dll_160_func_18
#define rodata_0 __dll160_rodata_0
#define rodata_4 __dll160_rodata_4
#define rodata_8 __dll160_rodata_8
#define rodata_C __dll160_rodata_C
#define rodata_10 __dll160_rodata_10
#define data_0 __dll160_data_0
#define data_B4 __dll160_data_B4
#define data_114 __dll160_data_114
#define data_128 __dll160_data_128
#define data_150 __dll160_data_150
#define data_188 __dll160_data_188
#define data_194 __dll160_data_194
#define data_19C __dll160_data_19C
#define data_19E __dll160_data_19E
#define data_1A0 __dll160_data_1A0

#endif //_DLL_160_RECOMP_H
