// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_160_RECOMP_H
#define _DLL_160_RECOMP_H

#define dll_160_ctor __dll160_dll_160_ctor
#define dll_160_dtor __dll160_dll_160_dtor
#define dll_160_func_18 __dll160_dll_160_func_18
#define _rodata_0 __dll160__rodata_0
#define _rodata_4 __dll160__rodata_4
#define _rodata_8 __dll160__rodata_8
#define _rodata_C __dll160__rodata_C
#define _rodata_10 __dll160__rodata_10
#define _data_0 __dll160__data_0
#define _data_B4 __dll160__data_B4
#define _data_114 __dll160__data_114
#define _data_128 __dll160__data_128
#define _data_150 __dll160__data_150
#define _data_188 __dll160__data_188
#define _data_194 __dll160__data_194
#define _data_19C __dll160__data_19C
#define _data_19E __dll160__data_19E
#define _data_1A0 __dll160__data_1A0

#endif //_DLL_160_RECOMP_H
