// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_164_RECOMP_H
#define _DLL_164_RECOMP_H

#define dll_164_ctor __dll164_dll_164_ctor
#define dll_164_dtor __dll164_dll_164_dtor
#define dll_164_func_18 __dll164_dll_164_func_18
#define _rodata_0 __dll164__rodata_0
#define _rodata_4 __dll164__rodata_4
#define _data_0 __dll164__data_0
#define _data_3C __dll164__data_3C
#define _data_54 __dll164__data_54
#define _data_64 __dll164__data_64
#define _data_70 __dll164__data_70
#define _data_7C __dll164__data_7C

#endif //_DLL_164_RECOMP_H
