// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_169_RECOMP_H
#define _DLL_169_RECOMP_H

#define dll_169_ctor __dll169_dll_169_ctor
#define dll_169_dtor __dll169_dll_169_dtor
#define dll_169_func_18 __dll169_dll_169_func_18
#define rodata_0 __dll169_rodata_0
#define rodata_4 __dll169_rodata_4
#define data_0 __dll169_data_0
#define data_3C __dll169_data_3C
#define data_54 __dll169_data_54
#define data_64 __dll169_data_64
#define data_70 __dll169_data_70
#define data_7C __dll169_data_7C

#endif //_DLL_169_RECOMP_H
