// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_170_RECOMP_H
#define _DLL_170_RECOMP_H

#define dll_170_ctor __dll170_dll_170_ctor
#define dll_170_dtor __dll170_dll_170_dtor
#define dll_170_func_18 __dll170_dll_170_func_18
#define rodata_0 __dll170_rodata_0
#define rodata_4 __dll170_rodata_4
#define rodata_8 __dll170_rodata_8
#define rodata_C __dll170_rodata_C
#define rodata_10 __dll170_rodata_10
#define rodata_14 __dll170_rodata_14
#define rodata_18 __dll170_rodata_18
#define rodata_1C __dll170_rodata_1C
#define data_0 __dll170_data_0
#define data_20 __dll170_data_20
#define data_28 __dll170_data_28
#define data_34 __dll170_data_34
#define data_3C __dll170_data_3C

#endif //_DLL_170_RECOMP_H
