// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_182_RECOMP_H
#define _DLL_182_RECOMP_H

#define dll_182_ctor __dll182_dll_182_ctor
#define dll_182_dtor __dll182_dll_182_dtor
#define dll_182_func_18 __dll182_dll_182_func_18
#define _rodata_0 __dll182__rodata_0
#define _rodata_4 __dll182__rodata_4
#define _rodata_8 __dll182__rodata_8
#define _rodata_C __dll182__rodata_C
#define _rodata_10 __dll182__rodata_10
#define _data_0 __dll182__data_0
#define _data_20 __dll182__data_20
#define _data_30 __dll182__data_30
#define _data_38 __dll182__data_38
#define _data_3A __dll182__data_3A
#define _data_3C __dll182__data_3C

#endif //_DLL_182_RECOMP_H
