// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_184_RECOMP_H
#define _DLL_184_RECOMP_H

#define dll_184_ctor __dll184_dll_184_ctor
#define dll_184_dtor __dll184_dll_184_dtor
#define dll_184_func_18 __dll184_dll_184_func_18
#define _rodata_0 __dll184__rodata_0
#define _rodata_4 __dll184__rodata_4
#define _rodata_8 __dll184__rodata_8
#define _rodata_C __dll184__rodata_C
#define _rodata_10 __dll184__rodata_10
#define _rodata_14 __dll184__rodata_14
#define _data_0 __dll184__data_0
#define _data_8C __dll184__data_8C
#define _data_D4 __dll184__data_D4
#define _data_E4 __dll184__data_E4
#define _data_F4 __dll184__data_F4
#define _data_110 __dll184__data_110
#define _data_112 __dll184__data_112
#define _data_114 __dll184__data_114

#endif //_DLL_184_RECOMP_H
