// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_192_RECOMP_H
#define _DLL_192_RECOMP_H

#define dll_192_ctor __dll192_dll_192_ctor
#define dll_192_dtor __dll192_dll_192_dtor
#define dll_192_func_18 __dll192_dll_192_func_18
#define rodata_0 __dll192_rodata_0
#define rodata_4 __dll192_rodata_4
#define rodata_8 __dll192_rodata_8
#define rodata_C __dll192_rodata_C
#define data_0 __dll192_data_0
#define data_4 __dll192_data_4
#define data_8 __dll192_data_8

#endif //_DLL_192_RECOMP_H
