// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_197_RECOMP_H
#define _DLL_197_RECOMP_H

#define dll_197_ctor __dll197_dll_197_ctor
#define dll_197_dtor __dll197_dll_197_dtor
#define dll_197_func_18 __dll197_dll_197_func_18
#define rodata_0 __dll197_rodata_0
#define rodata_4 __dll197_rodata_4
#define rodata_8 __dll197_rodata_8
#define rodata_C __dll197_rodata_C
#define rodata_10 __dll197_rodata_10
#define rodata_14 __dll197_rodata_14
#define rodata_18 __dll197_rodata_18

#endif //_DLL_197_RECOMP_H
