// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_198_RECOMP_H
#define _DLL_198_RECOMP_H

#define dll_198_ctor __dll198_dll_198_ctor
#define dll_198_dtor __dll198_dll_198_dtor
#define dll_198_func_18 __dll198_dll_198_func_18

#endif //_DLL_198_RECOMP_H
