// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_203_RECOMP_H
#define _DLL_203_RECOMP_H

#define dll_203_ctor __dll203_dll_203_ctor
#define dll_203_dtor __dll203_dll_203_dtor
#define dll_203_func_18 __dll203_dll_203_func_18
#define _rodata_0 __dll203__rodata_0
#define _rodata_4 __dll203__rodata_4
#define _rodata_8 __dll203__rodata_8
#define _rodata_C __dll203__rodata_C
#define _data_0 __dll203__data_0

#endif //_DLL_203_RECOMP_H
