// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_206_RECOMP_H
#define _DLL_206_RECOMP_H

#define dll_206_ctor __dll206_dll_206_ctor
#define dll_206_dtor __dll206_dll_206_dtor
#define dll_206_func_18 __dll206_dll_206_func_18
#define rodata_0 __dll206_rodata_0
#define rodata_4 __dll206_rodata_4
#define rodata_8 __dll206_rodata_8
#define rodata_C __dll206_rodata_C
#define rodata_10 __dll206_rodata_10

#endif //_DLL_206_RECOMP_H
