// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_209_RECOMP_H
#define _DLL_209_RECOMP_H

#define dll_209_ctor __dll209_dll_209_ctor
#define dll_209_dtor __dll209_dll_209_dtor
#define dll_209_func_18 __dll209_dll_209_func_18
#define _rodata_0 __dll209__rodata_0
#define _rodata_4 __dll209__rodata_4
#define _rodata_8 __dll209__rodata_8
#define _rodata_C __dll209__rodata_C
#define _rodata_10 __dll209__rodata_10

#endif //_DLL_209_RECOMP_H
