// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_220_RECOMP_H
#define _DLL_220_RECOMP_H

#define dll_220_ctor __dll220_dll_220_ctor
#define dll_220_dtor __dll220_dll_220_dtor
#define dll_220_func_18 __dll220_dll_220_func_18
#define dll_220_func_118 __dll220_dll_220_func_118
#define dll_220_func_670 __dll220_dll_220_func_670
#define dll_220_func_67C __dll220_dll_220_func_67C
#define dll_220_func_6D0 __dll220_dll_220_func_6D0
#define dll_220_func_6E0 __dll220_dll_220_func_6E0
#define dll_220_func_6F0 __dll220_dll_220_func_6F0
#define dll_220_func_704 __dll220_dll_220_func_704
#define dll_220_func_778 __dll220_dll_220_func_778
#define dll_220_func_8A4 __dll220_dll_220_func_8A4
#define str_0 __dll220_str_0
#define _data_0 __dll220__data_0
#define _data_12 __dll220__data_12
#define _data_1A __dll220__data_1A
#define _data_1E __dll220__data_1E

#endif //_DLL_220_RECOMP_H
