// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_221_RECOMP_H
#define _DLL_221_RECOMP_H

#define dll_221_ctor __dll221_dll_221_ctor
#define dll_221_dtor __dll221_dll_221_dtor
#define dll_221_func_18 __dll221_dll_221_func_18
#define dll_221_func_A0 __dll221_dll_221_func_A0
#define dll_221_func_2D4 __dll221_dll_221_func_2D4
#define dll_221_func_2E0 __dll221_dll_221_func_2E0
#define dll_221_func_334 __dll221_dll_221_func_334
#define dll_221_func_374 __dll221_dll_221_func_374
#define dll_221_func_384 __dll221_dll_221_func_384
#define dll_221_func_398 __dll221_dll_221_func_398
#define dll_221_func_620 __dll221_dll_221_func_620
#define dll_221_func_77C __dll221_dll_221_func_77C
#define _rodata_0 __dll221__rodata_0
#define _rodata_4 __dll221__rodata_4

#endif //_DLL_221_RECOMP_H
