// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_226_RECOMP_H
#define _DLL_226_RECOMP_H

#define dll_226_ctor __dll226_dll_226_ctor
#define dll_226_dtor __dll226_dll_226_dtor
#define dll_226_func_18 __dll226_dll_226_func_18
#define dll_226_func_24C __dll226_dll_226_func_24C
#define dll_226_func_50C __dll226_dll_226_func_50C
#define dll_226_func_518 __dll226_dll_226_func_518
#define dll_226_func_5A8 __dll226_dll_226_func_5A8
#define dll_226_func_5B8 __dll226_dll_226_func_5B8
#define dll_226_func_5C8 __dll226_dll_226_func_5C8
#define dll_226_func_5DC __dll226_dll_226_func_5DC
#define dll_226_func_620 __dll226_dll_226_func_620
#define str_0 __dll226_str_0
#define _data_0 __dll226__data_0

#endif //_DLL_226_RECOMP_H
