// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_230_RECOMP_H
#define _DLL_230_RECOMP_H

#define dll_230_ctor __dll230_dll_230_ctor
#define dll_230_dtor __dll230_dll_230_dtor
#define dll_230_create __dll230_dll_230_create
#define dll_230_func_1BC __dll230_dll_230_func_1BC
#define dll_230_update __dll230_dll_230_update
#define dll_230_func_8D8 __dll230_dll_230_func_8D8
#define dll_230_draw __dll230_dll_230_draw
#define dll_230_destroy __dll230_dll_230_destroy
#define dll_230_get_model_flags __dll230_dll_230_get_model_flags
#define dll_230_get_state_size __dll230_dll_230_get_state_size
#define dll_230_func_A1C __dll230_dll_230_func_A1C
#define dll_230_func_BFC __dll230_dll_230_func_BFC
#define dll_230_func_E70 __dll230_dll_230_func_E70
#define dll_230_func_FB0 __dll230_dll_230_func_FB0
#define dll_230_func_10F4 __dll230_dll_230_func_10F4
#define str_0 __dll230_str_0
#define _rodata_28 __dll230__rodata_28
#define _rodata_2C __dll230__rodata_2C
#define _rodata_30 __dll230__rodata_30
#define _data_0 __dll230__data_0
#define _data_1C __dll230__data_1C
#define _bss_0 __dll230__bss_0
#define _bss_10 __dll230__bss_10

#endif //_DLL_230_RECOMP_H
