// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_238_RECOMP_H
#define _DLL_238_RECOMP_H

#define dll_238_func_0 __dll238_dll_238_func_0
#define dll_238_ctor __dll238_dll_238_ctor
#define dll_238_dtor __dll238_dll_238_dtor
#define dll_238_setup __dll238_dll_238_setup
#define dll_238_control __dll238_dll_238_control
#define dll_238_update __dll238_dll_238_update
#define dll_238_print __dll238_dll_238_print
#define dll_238_free __dll238_dll_238_free
#define dll_238_get_model_flags __dll238_dll_238_get_model_flags
#define dll_238_get_data_size __dll238_dll_238_get_data_size
#define dll_238_func_7E8 __dll238_dll_238_func_7E8
#define dll_238_func_90C __dll238_dll_238_func_90C
#define dll_238_func_A50 __dll238_dll_238_func_A50
#define dll_238_func_B54 __dll238_dll_238_func_B54
#define dll_238_func_C90 __dll238_dll_238_func_C90
#define _rodata_0 __dll238__rodata_0
#define _rodata_4 __dll238__rodata_4
#define _data_0 __dll238__data_0
#define _data_1C __dll238__data_1C
#define _bss_0 __dll238__bss_0
#define _bss_10 __dll238__bss_10

#endif //_DLL_238_RECOMP_H
