// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_239_RECOMP_H
#define _DLL_239_RECOMP_H

#define dll_239_func_0 __dll239_dll_239_func_0
#define dll_239_ctor __dll239_dll_239_ctor
#define dll_239_dtor __dll239_dll_239_dtor
#define dll_239_create __dll239_dll_239_create
#define dll_239_update __dll239_dll_239_update
#define dll_239_func_6FC __dll239_dll_239_func_6FC
#define dll_239_draw __dll239_dll_239_draw
#define dll_239_destroy __dll239_dll_239_destroy
#define dll_239_get_model_flags __dll239_dll_239_get_model_flags
#define dll_239_get_state_size __dll239_dll_239_get_state_size
#define dll_239_func_830 __dll239_dll_239_func_830
#define dll_239_func_954 __dll239_dll_239_func_954
#define dll_239_func_AD0 __dll239_dll_239_func_AD0
#define dll_239_func_BD4 __dll239_dll_239_func_BD4
#define dll_239_func_D10 __dll239_dll_239_func_D10
#define _rodata_0 __dll239__rodata_0
#define _rodata_4 __dll239__rodata_4
#define _data_0 __dll239__data_0
#define _data_1C __dll239__data_1C
#define _bss_0 __dll239__bss_0
#define _bss_10 __dll239__bss_10

#endif //_DLL_239_RECOMP_H
