// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_242_RECOMP_H
#define _DLL_242_RECOMP_H

#define dll_242_func_0 __dll242_dll_242_func_0
#define dll_242_ctor __dll242_dll_242_ctor
#define dll_242_dtor __dll242_dll_242_dtor
#define dll_242_func_80 __dll242_dll_242_func_80
#define dll_242_func_1B0 __dll242_dll_242_func_1B0
#define dll_242_func_2EC __dll242_dll_242_func_2EC
#define dll_242_func_3F8 __dll242_dll_242_func_3F8
#define dll_242_func_570 __dll242_dll_242_func_570
#define dll_242_func_57C __dll242_dll_242_func_57C
#define dll_242_func_5DC __dll242_dll_242_func_5DC
#define dll_242_func_680 __dll242_dll_242_func_680
#define dll_242_func_690 __dll242_dll_242_func_690
#define dll_242_func_6A4 __dll242_dll_242_func_6A4
#define dll_242_func_760 __dll242_dll_242_func_760
#define _bss_0 __dll242__bss_0
#define _bss_4 __dll242__bss_4

#endif //_DLL_242_RECOMP_H
