// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_242_RECOMP_H
#define _DLL_242_RECOMP_H

#define dll_242_func_0 __dll242_dll_242_func_0
#define dll_242_ctor __dll242_dll_242_ctor
#define dll_242_dtor __dll242_dll_242_dtor
#define dll_242_func_80 __dll242_dll_242_func_80
#define dll_242_setup __dll242_dll_242_setup
#define dll_242_func_2EC __dll242_dll_242_func_2EC
#define dll_242_control __dll242_dll_242_control
#define dll_242_update __dll242_dll_242_update
#define dll_242_print __dll242_dll_242_print
#define dll_242_free __dll242_dll_242_free
#define dll_242_get_model_flags __dll242_dll_242_get_model_flags
#define dll_242_get_data_size __dll242_dll_242_get_data_size
#define dll_242_func_6A4 __dll242_dll_242_func_6A4
#define dll_242_func_760 __dll242_dll_242_func_760
#define _bss_0 __dll242__bss_0
#define _bss_4 __dll242__bss_4

#endif //_DLL_242_RECOMP_H
