// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_246_RECOMP_H
#define _DLL_246_RECOMP_H

#define dll_246_ctor __dll246_dll_246_ctor
#define dll_246_dtor __dll246_dll_246_dtor
#define dll_246_func_18 __dll246_dll_246_func_18
#define dll_246_func_1CC __dll246_dll_246_func_1CC
#define dll_246_func_5B0 __dll246_dll_246_func_5B0
#define dll_246_func_5BC __dll246_dll_246_func_5BC
#define dll_246_func_5D4 __dll246_dll_246_func_5D4
#define dll_246_func_6A4 __dll246_dll_246_func_6A4
#define dll_246_func_6B4 __dll246_dll_246_func_6B4
#define dll_246_func_6C8 __dll246_dll_246_func_6C8
#define _rodata_0 __dll246__rodata_0
#define _rodata_4 __dll246__rodata_4
#define _rodata_8 __dll246__rodata_8
#define _rodata_C __dll246__rodata_C
#define _rodata_10 __dll246__rodata_10
#define _rodata_14 __dll246__rodata_14
#define _rodata_18 __dll246__rodata_18
#define _data_0 __dll246__data_0
#define _bss_0 __dll246__bss_0

#endif //_DLL_246_RECOMP_H
