// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_247_RECOMP_H
#define _DLL_247_RECOMP_H

#define dll_247_ctor __dll247_dll_247_ctor
#define dll_247_dtor __dll247_dll_247_dtor
#define dll_247_obj_Setup __dll247_dll_247_obj_Setup
#define dll_247_obj_Control __dll247_dll_247_obj_Control
#define dll_247_obj_Update __dll247_dll_247_obj_Update
#define dll_247_obj_Print __dll247_dll_247_obj_Print
#define dll_247_obj_Free __dll247_dll_247_obj_Free
#define dll_247_obj_GetModelFlags __dll247_dll_247_obj_GetModelFlags
#define dll_247_obj_GetDataSize __dll247_dll_247_obj_GetDataSize
#define dll_247_func_A5C __dll247_dll_247_func_A5C
#define rodata_0 __dll247_rodata_0
#define rodata_4 __dll247_rodata_4
#define rodata_8 __dll247_rodata_8
#define rodata_C __dll247_rodata_C
#define rodata_10 __dll247_rodata_10
#define rodata_18 __dll247_rodata_18
#define rodata_1C __dll247_rodata_1C
#define data_0 __dll247_data_0
#define bss_0 __dll247_bss_0

#endif //_DLL_247_RECOMP_H
