// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_247_RECOMP_H
#define _DLL_247_RECOMP_H

#define dll_247_ctor __dll247_dll_247_ctor
#define dll_247_dtor __dll247_dll_247_dtor
#define dll_247_setup __dll247_dll_247_setup
#define dll_247_control __dll247_dll_247_control
#define dll_247_update __dll247_dll_247_update
#define dll_247_print __dll247_dll_247_print
#define dll_247_free __dll247_dll_247_free
#define dll_247_get_model_flags __dll247_dll_247_get_model_flags
#define dll_247_get_data_size __dll247_dll_247_get_data_size
#define dll_247_func_A5C __dll247_dll_247_func_A5C
#define rodata_0 __dll247_rodata_0
#define rodata_4 __dll247_rodata_4
#define rodata_8 __dll247_rodata_8
#define rodata_C __dll247_rodata_C
#define rodata_10 __dll247_rodata_10
#define rodata_18 __dll247_rodata_18
#define rodata_1C __dll247_rodata_1C
#define data_0 __dll247_data_0
#define bss_0 __dll247_bss_0

#endif //_DLL_247_RECOMP_H
