// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_249_RECOMP_H
#define _DLL_249_RECOMP_H

#define dll_249_ctor __dll249_dll_249_ctor
#define dll_249_dtor __dll249_dll_249_dtor
#define dll_249_setup __dll249_dll_249_setup
#define dll_249_control __dll249_dll_249_control
#define dll_249_update __dll249_dll_249_update
#define dll_249_print __dll249_dll_249_print
#define dll_249_free __dll249_dll_249_free
#define dll_249_get_model_flags __dll249_dll_249_get_model_flags
#define dll_249_get_data_size __dll249_dll_249_get_data_size
#define dll_249_func_854 __dll249_dll_249_func_854
#define rodata_0 __dll249_rodata_0
#define rodata_4 __dll249_rodata_4
#define rodata_8 __dll249_rodata_8
#define rodata_C __dll249_rodata_C
#define rodata_10 __dll249_rodata_10
#define rodata_14 __dll249_rodata_14
#define rodata_18 __dll249_rodata_18
#define rodata_1C __dll249_rodata_1C
#define rodata_20 __dll249_rodata_20
#define data_0 __dll249_data_0
#define bss_0 __dll249_bss_0

#endif //_DLL_249_RECOMP_H
