// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_249_RECOMP_H
#define _DLL_249_RECOMP_H

#define dll_249_ctor __dll249_dll_249_ctor
#define dll_249_dtor __dll249_dll_249_dtor
#define dll_249_create __dll249_dll_249_create
#define dll_249_update __dll249_dll_249_update
#define dll_249_func_73C __dll249_dll_249_func_73C
#define dll_249_draw __dll249_dll_249_draw
#define dll_249_destroy __dll249_dll_249_destroy
#define dll_249_get_setup_flags __dll249_dll_249_get_setup_flags
#define dll_249_get_state_size __dll249_dll_249_get_state_size
#define dll_249_func_854 __dll249_dll_249_func_854
#define _rodata_0 __dll249__rodata_0
#define _rodata_4 __dll249__rodata_4
#define _rodata_8 __dll249__rodata_8
#define _rodata_C __dll249__rodata_C
#define _rodata_10 __dll249__rodata_10
#define _rodata_14 __dll249__rodata_14
#define _rodata_18 __dll249__rodata_18
#define _rodata_1C __dll249__rodata_1C
#define _rodata_20 __dll249__rodata_20
#define _data_0 __dll249__data_0
#define _bss_0 __dll249__bss_0

#endif //_DLL_249_RECOMP_H
