// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_250_RECOMP_H
#define _DLL_250_RECOMP_H

#define dll_250_ctor __dll250_dll_250_ctor
#define dll_250_dtor __dll250_dll_250_dtor
#define dll_250_create __dll250_dll_250_create
#define dll_250_update __dll250_dll_250_update
#define dll_250_func_808 __dll250_dll_250_func_808
#define dll_250_draw __dll250_dll_250_draw
#define dll_250_destroy __dll250_dll_250_destroy
#define dll_250_get_setup_flags __dll250_dll_250_get_setup_flags
#define dll_250_get_state_size __dll250_dll_250_get_state_size
#define dll_250_func_A5C __dll250_dll_250_func_A5C
#define _rodata_0 __dll250__rodata_0
#define _rodata_4 __dll250__rodata_4
#define _rodata_8 __dll250__rodata_8
#define _rodata_C __dll250__rodata_C
#define _rodata_10 __dll250__rodata_10
#define _rodata_18 __dll250__rodata_18
#define _rodata_1C __dll250__rodata_1C
#define _data_0 __dll250__data_0
#define _bss_0 __dll250__bss_0

#endif //_DLL_250_RECOMP_H
