// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_259_RECOMP_H
#define _DLL_259_RECOMP_H

#define dll_259_ctor __dll259_dll_259_ctor
#define dll_259_dtor __dll259_dll_259_dtor
#define dll_259_func_18 __dll259_dll_259_func_18
#define dll_259_func_AC __dll259_dll_259_func_AC
#define dll_259_func_310 __dll259_dll_259_func_310
#define dll_259_func_334 __dll259_dll_259_func_334
#define dll_259_func_34C __dll259_dll_259_func_34C
#define dll_259_func_3AC __dll259_dll_259_func_3AC
#define dll_259_func_3BC __dll259_dll_259_func_3BC
#define dll_259_func_3D0 __dll259_dll_259_func_3D0
#define _data_0 __dll259__data_0

#endif //_DLL_259_RECOMP_H
