// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_261_RECOMP_H
#define _DLL_261_RECOMP_H

#define dll_261_ctor __dll261_dll_261_ctor
#define dll_261_dtor __dll261_dll_261_dtor
#define dll_261_create __dll261_dll_261_create
#define dll_261_update __dll261_dll_261_update
#define dll_261_func_2F0 __dll261_dll_261_func_2F0
#define dll_261_draw __dll261_dll_261_draw
#define dll_261_destroy __dll261_dll_261_destroy
#define dll_261_get_setup_flags __dll261_dll_261_get_setup_flags
#define dll_261_get_state_size __dll261_dll_261_get_state_size
#define _rodata_0 __dll261__rodata_0
#define _rodata_4 __dll261__rodata_4

#endif //_DLL_261_RECOMP_H
