// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_261_RECOMP_H
#define _DLL_261_RECOMP_H

#define dll_261_ctor __dll261_dll_261_ctor
#define dll_261_dtor __dll261_dll_261_dtor
#define dll_261_func_18 __dll261_dll_261_func_18
#define dll_261_func_F4 __dll261_dll_261_func_F4
#define dll_261_func_2F0 __dll261_dll_261_func_2F0
#define dll_261_func_2FC __dll261_dll_261_func_2FC
#define dll_261_func_350 __dll261_dll_261_func_350
#define dll_261_func_390 __dll261_dll_261_func_390
#define dll_261_func_3A0 __dll261_dll_261_func_3A0
#define _rodata_0 __dll261__rodata_0
#define _rodata_4 __dll261__rodata_4

#endif //_DLL_261_RECOMP_H
