// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_265_RECOMP_H
#define _DLL_265_RECOMP_H

#define dll_265_ctor __dll265_dll_265_ctor
#define dll_265_dtor __dll265_dll_265_dtor
#define dll_265_func_18 __dll265_dll_265_func_18
#define dll_265_func_104 __dll265_dll_265_func_104
#define dll_265_func_22C __dll265_dll_265_func_22C
#define dll_265_func_2A4 __dll265_dll_265_func_2A4
#define dll_265_func_470 __dll265_dll_265_func_470
#define dll_265_func_4C4 __dll265_dll_265_func_4C4
#define dll_265_func_4D4 __dll265_dll_265_func_4D4
#define str_0 __dll265_str_0
#define _rodata_30 __dll265__rodata_30

#endif //_DLL_265_RECOMP_H
