// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_266_RECOMP_H
#define _DLL_266_RECOMP_H

#define dll_266_ctor __dll266_dll_266_ctor
#define dll_266_dtor __dll266_dll_266_dtor
#define dll_266_func_18 __dll266_dll_266_func_18
#define dll_266_func_FC __dll266_dll_266_func_FC
#define dll_266_func_458 __dll266_dll_266_func_458
#define dll_266_func_464 __dll266_dll_266_func_464
#define dll_266_func_4C0 __dll266_dll_266_func_4C0
#define dll_266_func_51C __dll266_dll_266_func_51C
#define dll_266_func_52C __dll266_dll_266_func_52C
#define _oob_rodata_0 __dll266__oob_rodata_0

#endif //_DLL_266_RECOMP_H
