// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_268_RECOMP_H
#define _DLL_268_RECOMP_H

#define dll_268_ctor __dll268_dll_268_ctor
#define dll_268_dtor __dll268_dll_268_dtor
#define dll_268_func_18 __dll268_dll_268_func_18
#define dll_268_func_58 __dll268_dll_268_func_58
#define dll_268_func_64 __dll268_dll_268_func_64
#define dll_268_func_70 __dll268_dll_268_func_70
#define dll_268_func_C4 __dll268_dll_268_func_C4
#define dll_268_func_D4 __dll268_dll_268_func_D4
#define dll_268_func_E4 __dll268_dll_268_func_E4
#define _oob_rodata_0 __dll268__oob_rodata_0

#endif //_DLL_268_RECOMP_H
