// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_275_RECOMP_H
#define _DLL_275_RECOMP_H

#define dll_275_ctor __dll275_dll_275_ctor
#define dll_275_dtor __dll275_dll_275_dtor
#define dll_275_func_18 __dll275_dll_275_func_18
#define dll_275_func_AC __dll275_dll_275_func_AC
#define dll_275_func_83C __dll275_dll_275_func_83C
#define dll_275_func_848 __dll275_dll_275_func_848
#define dll_275_func_868 __dll275_dll_275_func_868
#define dll_275_func_878 __dll275_dll_275_func_878
#define dll_275_func_888 __dll275_dll_275_func_888
#define dll_275_func_89C __dll275_dll_275_func_89C
#define str_0 __dll275_str_0

#endif //_DLL_275_RECOMP_H
