// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_282_RECOMP_H
#define _DLL_282_RECOMP_H

#define dll_282_ctor __dll282_dll_282_ctor
#define dll_282_dtor __dll282_dll_282_dtor
#define dll_282_setup __dll282_dll_282_setup
#define dll_282_control __dll282_dll_282_control
#define dll_282_update __dll282_dll_282_update
#define dll_282_print __dll282_dll_282_print
#define dll_282_free __dll282_dll_282_free
#define dll_282_get_model_flags __dll282_dll_282_get_model_flags
#define dll_282_get_data_size __dll282_dll_282_get_data_size
#define _data_0 __dll282__data_0
#define _data_4 __dll282__data_4
#define _data_8 __dll282__data_8

#endif //_DLL_282_RECOMP_H
