// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_283_RECOMP_H
#define _DLL_283_RECOMP_H

#define dll_283_ctor __dll283_dll_283_ctor
#define dll_283_dtor __dll283_dll_283_dtor
#define dll_283_func_18 __dll283_dll_283_func_18
#define dll_283_func_88 __dll283_dll_283_func_88
#define dll_283_func_324 __dll283_dll_283_func_324
#define dll_283_func_330 __dll283_dll_283_func_330
#define dll_283_func_3A4 __dll283_dll_283_func_3A4
#define dll_283_func_414 __dll283_dll_283_func_414
#define dll_283_func_424 __dll283_dll_283_func_424
#define dll_283_func_438 __dll283_dll_283_func_438
#define dll_283_func_564 __dll283_dll_283_func_564
#define dll_283_func_61C __dll283_dll_283_func_61C
#define _rodata_0 __dll283__rodata_0
#define _bss_0 __dll283__bss_0

#endif //_DLL_283_RECOMP_H
