// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_283_RECOMP_H
#define _DLL_283_RECOMP_H

#define dll_283_ctor __dll283_dll_283_ctor
#define dll_283_dtor __dll283_dll_283_dtor
#define dll_283_create __dll283_dll_283_create
#define dll_283_update __dll283_dll_283_update
#define dll_283_func_324 __dll283_dll_283_func_324
#define dll_283_draw __dll283_dll_283_draw
#define dll_283_destroy __dll283_dll_283_destroy
#define dll_283_get_setup_flags __dll283_dll_283_get_setup_flags
#define dll_283_get_state_size __dll283_dll_283_get_state_size
#define dll_283_func_438 __dll283_dll_283_func_438
#define dll_283_func_564 __dll283_dll_283_func_564
#define dll_283_func_61C __dll283_dll_283_func_61C
#define _rodata_0 __dll283__rodata_0
#define _bss_0 __dll283__bss_0

#endif //_DLL_283_RECOMP_H
