// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_287_RECOMP_H
#define _DLL_287_RECOMP_H

#define dll_287_ctor __dll287_dll_287_ctor
#define dll_287_dtor __dll287_dll_287_dtor
#define dll_287_create __dll287_dll_287_create
#define dll_287_update __dll287_dll_287_update
#define dll_287_func_524 __dll287_dll_287_func_524
#define dll_287_draw __dll287_dll_287_draw
#define dll_287_destroy __dll287_dll_287_destroy
#define dll_287_get_setup_flags __dll287_dll_287_get_setup_flags
#define dll_287_get_state_size __dll287_dll_287_get_state_size
#define dll_287_func_628 __dll287_dll_287_func_628
#define dll_287_func_694 __dll287_dll_287_func_694
#define dll_287_func_718 __dll287_dll_287_func_718
#define str_0 __dll287_str_0

#endif //_DLL_287_RECOMP_H
