// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_291_RECOMP_H
#define _DLL_291_RECOMP_H

#define dll_291_ctor __dll291_dll_291_ctor
#define dll_291_dtor __dll291_dll_291_dtor
#define dll_291_func_18 __dll291_dll_291_func_18
#define dll_291_func_3F0 __dll291_dll_291_func_3F0
#define dll_291_func_EFC __dll291_dll_291_func_EFC
#define dll_291_func_F08 __dll291_dll_291_func_F08
#define dll_291_func_F68 __dll291_dll_291_func_F68
#define dll_291_func_F78 __dll291_dll_291_func_F78
#define dll_291_func_F88 __dll291_dll_291_func_F88
#define dll_291_func_F9C __dll291_dll_291_func_F9C
#define _rodata_0 __dll291__rodata_0
#define _rodata_4 __dll291__rodata_4
#define _rodata_8 __dll291__rodata_8
#define _rodata_C __dll291__rodata_C
#define _rodata_10 __dll291__rodata_10
#define _data_0 __dll291__data_0

#endif //_DLL_291_RECOMP_H
