// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_291_RECOMP_H
#define _DLL_291_RECOMP_H

#define dll_291_ctor __dll291_dll_291_ctor
#define dll_291_dtor __dll291_dll_291_dtor
#define dll_291_create __dll291_dll_291_create
#define dll_291_update __dll291_dll_291_update
#define dll_291_func_EFC __dll291_dll_291_func_EFC
#define dll_291_draw __dll291_dll_291_draw
#define dll_291_destroy __dll291_dll_291_destroy
#define dll_291_get_model_flags __dll291_dll_291_get_model_flags
#define dll_291_get_state_size __dll291_dll_291_get_state_size
#define dll_291_func_F9C __dll291_dll_291_func_F9C
#define _rodata_0 __dll291__rodata_0
#define _rodata_4 __dll291__rodata_4
#define _rodata_8 __dll291__rodata_8
#define _rodata_C __dll291__rodata_C
#define _rodata_10 __dll291__rodata_10
#define _data_0 __dll291__data_0

#endif //_DLL_291_RECOMP_H
