// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_293_RECOMP_H
#define _DLL_293_RECOMP_H

#define dll_293_ctor __dll293_dll_293_ctor
#define dll_293_dtor __dll293_dll_293_dtor
#define dll_293_func_18 __dll293_dll_293_func_18
#define dll_293_func_6C __dll293_dll_293_func_6C
#define dll_293_func_18C __dll293_dll_293_func_18C
#define dll_293_func_198 __dll293_dll_293_func_198
#define dll_293_func_1B0 __dll293_dll_293_func_1B0
#define dll_293_func_1F0 __dll293_dll_293_func_1F0
#define dll_293_func_200 __dll293_dll_293_func_200

#endif //_DLL_293_RECOMP_H
