// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_301_RECOMP_H
#define _DLL_301_RECOMP_H

#define dll_301_ctor __dll301_dll_301_ctor
#define dll_301_dtor __dll301_dll_301_dtor
#define dll_301_func_18 __dll301_dll_301_func_18
#define dll_301_func_BC __dll301_dll_301_func_BC
#define dll_301_func_3A8 __dll301_dll_301_func_3A8
#define dll_301_func_3B4 __dll301_dll_301_func_3B4
#define dll_301_func_450 __dll301_dll_301_func_450
#define dll_301_func_498 __dll301_dll_301_func_498
#define dll_301_func_4A8 __dll301_dll_301_func_4A8
#define _oob_rodata_0 __dll301__oob_rodata_0

#endif //_DLL_301_RECOMP_H
