// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_304_RECOMP_H
#define _DLL_304_RECOMP_H

#define dll_304_ctor __dll304_dll_304_ctor
#define dll_304_dtor __dll304_dll_304_dtor
#define dll_304_setup __dll304_dll_304_setup
#define dll_304_control __dll304_dll_304_control
#define dll_304_update __dll304_dll_304_update
#define dll_304_print __dll304_dll_304_print
#define dll_304_free __dll304_dll_304_free
#define dll_304_get_model_flags __dll304_dll_304_get_model_flags
#define dll_304_get_data_size __dll304_dll_304_get_data_size
#define dll_304_func_984 __dll304_dll_304_func_984
#define dll_304_func_AB0 __dll304_dll_304_func_AB0
#define dll_304_func_BE0 __dll304_dll_304_func_BE0
#define dll_304_func_C3C __dll304_dll_304_func_C3C
#define dll_304_func_E54 __dll304_dll_304_func_E54
#define str_0 __dll304_str_0
#define str_14 __dll304_str_14
#define _rodata_38 __dll304__rodata_38
#define _rodata_3C __dll304__rodata_3C
#define _rodata_40 __dll304__rodata_40
#define _rodata_44 __dll304__rodata_44
#define _rodata_48 __dll304__rodata_48
#define _rodata_4C __dll304__rodata_4C
#define _rodata_50 __dll304__rodata_50
#define _data_0 __dll304__data_0
#define _data_4 __dll304__data_4

#endif //_DLL_304_RECOMP_H
