// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_306_RECOMP_H
#define _DLL_306_RECOMP_H

#define dll_306_ctor __dll306_dll_306_ctor
#define dll_306_dtor __dll306_dll_306_dtor
#define dll_306_create __dll306_dll_306_create
#define dll_306_update __dll306_dll_306_update
#define dll_306_func_610 __dll306_dll_306_func_610
#define dll_306_draw __dll306_dll_306_draw
#define dll_306_destroy __dll306_dll_306_destroy
#define dll_306_get_model_flags __dll306_dll_306_get_model_flags
#define dll_306_get_state_size __dll306_dll_306_get_state_size
#define dll_306_func_6E0 __dll306_dll_306_func_6E0
#define dll_306_func_7FC __dll306_dll_306_func_7FC
#define dll_306_func_95C __dll306_dll_306_func_95C
#define _rodata_0 __dll306__rodata_0
#define _rodata_4 __dll306__rodata_4
#define _data_0 __dll306__data_0
#define _data_20 __dll306__data_20
#define _data_40 __dll306__data_40
#define _data_60 __dll306__data_60

#endif //_DLL_306_RECOMP_H
