// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_306_RECOMP_H
#define _DLL_306_RECOMP_H

#define dll_306_ctor __dll306_dll_306_ctor
#define dll_306_dtor __dll306_dll_306_dtor
#define dll_306_func_18 __dll306_dll_306_func_18
#define dll_306_func_35C __dll306_dll_306_func_35C
#define dll_306_func_610 __dll306_dll_306_func_610
#define dll_306_func_61C __dll306_dll_306_func_61C
#define dll_306_func_688 __dll306_dll_306_func_688
#define dll_306_func_698 __dll306_dll_306_func_698
#define dll_306_func_6CC __dll306_dll_306_func_6CC
#define dll_306_func_6E0 __dll306_dll_306_func_6E0
#define dll_306_func_7FC __dll306_dll_306_func_7FC
#define dll_306_func_95C __dll306_dll_306_func_95C
#define _rodata_0 __dll306__rodata_0
#define _rodata_4 __dll306__rodata_4
#define _data_0 __dll306__data_0
#define _data_20 __dll306__data_20
#define _data_40 __dll306__data_40
#define _data_60 __dll306__data_60

#endif //_DLL_306_RECOMP_H
