// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_308_RECOMP_H
#define _DLL_308_RECOMP_H

#define dll_308_ctor __dll308_dll_308_ctor
#define dll_308_dtor __dll308_dll_308_dtor
#define dll_308_setup __dll308_dll_308_setup
#define dll_308_control __dll308_dll_308_control
#define dll_308_update __dll308_dll_308_update
#define dll_308_print __dll308_dll_308_print
#define dll_308_free __dll308_dll_308_free
#define dll_308_get_model_flags __dll308_dll_308_get_model_flags
#define dll_308_get_data_size __dll308_dll_308_get_data_size
#define dll_308_func_4C8 __dll308_dll_308_func_4C8
#define str_0 __dll308_str_0

#endif //_DLL_308_RECOMP_H
