// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_311_RECOMP_H
#define _DLL_311_RECOMP_H

#define dll_311_ctor __dll311_dll_311_ctor
#define dll_311_dtor __dll311_dll_311_dtor
#define dll_311_create __dll311_dll_311_create
#define dll_311_update __dll311_dll_311_update
#define dll_311_func_2B8 __dll311_dll_311_func_2B8
#define dll_311_draw __dll311_dll_311_draw
#define dll_311_destroy __dll311_dll_311_destroy
#define dll_311_get_model_flags __dll311_dll_311_get_model_flags
#define dll_311_get_state_size __dll311_dll_311_get_state_size
#define dll_311_func_37C __dll311_dll_311_func_37C
#define str_0 __dll311_str_0

#endif //_DLL_311_RECOMP_H
