// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_319_RECOMP_H
#define _DLL_319_RECOMP_H

#define dll_319_ctor __dll319_dll_319_ctor
#define dll_319_dtor __dll319_dll_319_dtor
#define dll_319_func_18 __dll319_dll_319_func_18
#define dll_319_func_5C __dll319_dll_319_func_5C
#define dll_319_func_68 __dll319_dll_319_func_68
#define dll_319_func_74 __dll319_dll_319_func_74
#define dll_319_func_8C __dll319_dll_319_func_8C
#define dll_319_func_9C __dll319_dll_319_func_9C
#define dll_319_func_AC __dll319_dll_319_func_AC
#define dll_319_func_C0 __dll319_dll_319_func_C0
#define dll_319_func_DC __dll319_dll_319_func_DC
#define dll_319_func_304 __dll319_dll_319_func_304
#define dll_319_func_338 __dll319_dll_319_func_338
#define dll_319_func_4D4 __dll319_dll_319_func_4D4

#endif //_DLL_319_RECOMP_H
