// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_320_RECOMP_H
#define _DLL_320_RECOMP_H

#define dll_320_ctor __dll320_dll_320_ctor
#define dll_320_dtor __dll320_dll_320_dtor
#define dll_320_create __dll320_dll_320_create
#define dll_320_update __dll320_dll_320_update
#define dll_320_func_3D4 __dll320_dll_320_func_3D4
#define dll_320_draw __dll320_dll_320_draw
#define dll_320_destroy __dll320_dll_320_destroy
#define dll_320_get_model_flags __dll320_dll_320_get_model_flags
#define dll_320_get_state_size __dll320_dll_320_get_state_size
#define _rodata_0 __dll320__rodata_0
#define _data_0 __dll320__data_0

#endif //_DLL_320_RECOMP_H
