// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_320_RECOMP_H
#define _DLL_320_RECOMP_H

#define dll_320_ctor __dll320_dll_320_ctor
#define dll_320_dtor __dll320_dll_320_dtor
#define dll_320_func_18 __dll320_dll_320_func_18
#define dll_320_func_1BC __dll320_dll_320_func_1BC
#define dll_320_func_3D4 __dll320_dll_320_func_3D4
#define dll_320_func_3E0 __dll320_dll_320_func_3E0
#define dll_320_func_498 __dll320_dll_320_func_498
#define dll_320_func_4DC __dll320_dll_320_func_4DC
#define dll_320_func_4EC __dll320_dll_320_func_4EC
#define _rodata_0 __dll320__rodata_0
#define _data_0 __dll320__data_0

#endif //_DLL_320_RECOMP_H
