// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_331_RECOMP_H
#define _DLL_331_RECOMP_H

#define dll_331_ctor __dll331_dll_331_ctor
#define dll_331_dtor __dll331_dll_331_dtor
#define dll_331_func_18 __dll331_dll_331_func_18
#define dll_331_func_7CC __dll331_dll_331_func_7CC
#define dll_331_func_1D28 __dll331_dll_331_func_1D28
#define dll_331_func_1D34 __dll331_dll_331_func_1D34
#define dll_331_func_1F2C __dll331_dll_331_func_1F2C
#define dll_331_func_1FB8 __dll331_dll_331_func_1FB8
#define dll_331_func_2000 __dll331_dll_331_func_2000
#define dll_331_func_2010 __dll331_dll_331_func_2010
#define str_0 __dll331_str_0
#define str_10 __dll331_str_10
#define str_20 __dll331_str_20
#define str_34 __dll331_str_34
#define str_60 __dll331_str_60
#define str_70 __dll331_str_70
#define str_8C __dll331_str_8C
#define str_9C __dll331_str_9C
#define _rodata_14C __dll331__rodata_14C
#define _rodata_150 __dll331__rodata_150
#define _rodata_154 __dll331__rodata_154
#define _rodata_158 __dll331__rodata_158
#define _rodata_15C __dll331__rodata_15C
#define _rodata_160 __dll331__rodata_160
#define _rodata_164 __dll331__rodata_164
#define _rodata_168 __dll331__rodata_168
#define _rodata_16C __dll331__rodata_16C
#define _rodata_170 __dll331__rodata_170
#define _rodata_174 __dll331__rodata_174
#define _rodata_178 __dll331__rodata_178
#define _rodata_210 __dll331__rodata_210
#define _rodata_214 __dll331__rodata_214
#define _rodata_218 __dll331__rodata_218
#define _rodata_21C __dll331__rodata_21C
#define _rodata_220 __dll331__rodata_220
#define _rodata_224 __dll331__rodata_224
#define _rodata_228 __dll331__rodata_228
#define _rodata_22C __dll331__rodata_22C
#define _rodata_230 __dll331__rodata_230
#define _rodata_234 __dll331__rodata_234
#define _data_0 __dll331__data_0
#define _data_4 __dll331__data_4

#endif //_DLL_331_RECOMP_H
