// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_332_RECOMP_H
#define _DLL_332_RECOMP_H

#define dll_332_ctor __dll332_dll_332_ctor
#define dll_332_dtor __dll332_dll_332_dtor
#define dll_332_create __dll332_dll_332_create
#define dll_332_update __dll332_dll_332_update
#define dll_332_func_608 __dll332_dll_332_func_608
#define dll_332_draw __dll332_dll_332_draw
#define dll_332_destroy __dll332_dll_332_destroy
#define dll_332_get_model_flags __dll332_dll_332_get_model_flags
#define dll_332_get_state_size __dll332_dll_332_get_state_size
#define dll_332_func_6C0 __dll332_dll_332_func_6C0
#define dll_332_func_8E8 __dll332_dll_332_func_8E8
#define _rodata_0 __dll332__rodata_0

#endif //_DLL_332_RECOMP_H
