// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_333_RECOMP_H
#define _DLL_333_RECOMP_H

#define dll_333_ctor __dll333_dll_333_ctor
#define dll_333_dtor __dll333_dll_333_dtor
#define dll_333_func_18 __dll333_dll_333_func_18
#define dll_333_func_8C __dll333_dll_333_func_8C
#define dll_333_func_2F4 __dll333_dll_333_func_2F4
#define dll_333_func_300 __dll333_dll_333_func_300
#define dll_333_func_318 __dll333_dll_333_func_318
#define dll_333_func_328 __dll333_dll_333_func_328
#define dll_333_func_338 __dll333_dll_333_func_338
#define _rodata_0 __dll333__rodata_0

#endif //_DLL_333_RECOMP_H
