// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_335_RECOMP_H
#define _DLL_335_RECOMP_H

#define dll_335_ctor __dll335_dll_335_ctor
#define dll_335_dtor __dll335_dll_335_dtor
#define dll_335_obj_Setup __dll335_dll_335_obj_Setup
#define dll_335_obj_Control __dll335_dll_335_obj_Control
#define dll_335_obj_Update __dll335_dll_335_obj_Update
#define dll_335_obj_Print __dll335_dll_335_obj_Print
#define dll_335_obj_Free __dll335_dll_335_obj_Free
#define dll_335_obj_GetModelFlags __dll335_dll_335_obj_GetModelFlags
#define dll_335_obj_GetDataSize __dll335_dll_335_obj_GetDataSize
#define dll_335_func_B48 __dll335_dll_335_func_B48
#define rodata_0 __dll335_rodata_0
#define rodata_4 __dll335_rodata_4
#define rodata_8 __dll335_rodata_8
#define rodata_C __dll335_rodata_C

#endif //_DLL_335_RECOMP_H
