// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_335_RECOMP_H
#define _DLL_335_RECOMP_H

#define dll_335_ctor __dll335_dll_335_ctor
#define dll_335_dtor __dll335_dll_335_dtor
#define dll_335_setup __dll335_dll_335_setup
#define dll_335_control __dll335_dll_335_control
#define dll_335_update __dll335_dll_335_update
#define dll_335_print __dll335_dll_335_print
#define dll_335_free __dll335_dll_335_free
#define dll_335_get_model_flags __dll335_dll_335_get_model_flags
#define dll_335_get_data_size __dll335_dll_335_get_data_size
#define dll_335_func_B48 __dll335_dll_335_func_B48
#define rodata_0 __dll335_rodata_0
#define rodata_4 __dll335_rodata_4
#define rodata_8 __dll335_rodata_8
#define rodata_C __dll335_rodata_C

#endif //_DLL_335_RECOMP_H
