// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_337_RECOMP_H
#define _DLL_337_RECOMP_H

#define dll_337_ctor __dll337_dll_337_ctor
#define dll_337_dtor __dll337_dll_337_dtor
#define dll_337_obj_Setup __dll337_dll_337_obj_Setup
#define dll_337_obj_Control __dll337_dll_337_obj_Control
#define dll_337_obj_Update __dll337_dll_337_obj_Update
#define dll_337_obj_Print __dll337_dll_337_obj_Print
#define dll_337_obj_Free __dll337_dll_337_obj_Free
#define dll_337_obj_GetModelFlags __dll337_dll_337_obj_GetModelFlags
#define dll_337_obj_GetDataSize __dll337_dll_337_obj_GetDataSize
#define rodata_0 __dll337_rodata_0
#define rodata_4 __dll337_rodata_4
#define rodata_8 __dll337_rodata_8
#define rodata_C __dll337_rodata_C
#define rodata_10 __dll337_rodata_10
#define rodata_14 __dll337_rodata_14
#define rodata_18 __dll337_rodata_18
#define rodata_1C __dll337_rodata_1C
#define data_0 __dll337_data_0
#define data_C __dll337_data_C
#define data_18 __dll337_data_18
#define data_1C __dll337_data_1C

#endif //_DLL_337_RECOMP_H
