// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_337_RECOMP_H
#define _DLL_337_RECOMP_H

#define dll_337_ctor __dll337_dll_337_ctor
#define dll_337_dtor __dll337_dll_337_dtor
#define dll_337_setup __dll337_dll_337_setup
#define dll_337_control __dll337_dll_337_control
#define dll_337_update __dll337_dll_337_update
#define dll_337_print __dll337_dll_337_print
#define dll_337_free __dll337_dll_337_free
#define dll_337_get_model_flags __dll337_dll_337_get_model_flags
#define dll_337_get_data_size __dll337_dll_337_get_data_size
#define _rodata_0 __dll337__rodata_0
#define _rodata_4 __dll337__rodata_4
#define _rodata_8 __dll337__rodata_8
#define _rodata_C __dll337__rodata_C
#define _rodata_10 __dll337__rodata_10
#define _rodata_14 __dll337__rodata_14
#define _rodata_18 __dll337__rodata_18
#define _rodata_1C __dll337__rodata_1C
#define _data_0 __dll337__data_0
#define _data_C __dll337__data_C
#define _data_18 __dll337__data_18
#define _data_1C __dll337__data_1C

#endif //_DLL_337_RECOMP_H
