// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_337_RECOMP_H
#define _DLL_337_RECOMP_H

#define dll_337_ctor __dll337_dll_337_ctor
#define dll_337_dtor __dll337_dll_337_dtor
#define dll_337_setup __dll337_dll_337_setup
#define dll_337_control __dll337_dll_337_control
#define dll_337_update __dll337_dll_337_update
#define dll_337_print __dll337_dll_337_print
#define dll_337_free __dll337_dll_337_free
#define dll_337_get_model_flags __dll337_dll_337_get_model_flags
#define dll_337_get_data_size __dll337_dll_337_get_data_size
#define rodata_0 __dll337_rodata_0
#define rodata_4 __dll337_rodata_4
#define rodata_8 __dll337_rodata_8
#define rodata_C __dll337_rodata_C
#define rodata_10 __dll337_rodata_10
#define rodata_14 __dll337_rodata_14
#define rodata_18 __dll337_rodata_18
#define rodata_1C __dll337_rodata_1C
#define data_0 __dll337_data_0
#define data_C __dll337_data_C
#define data_18 __dll337_data_18
#define data_1C __dll337_data_1C

#endif //_DLL_337_RECOMP_H
