// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_338_RECOMP_H
#define _DLL_338_RECOMP_H

#define dll_338_ctor __dll338_dll_338_ctor
#define dll_338_dtor __dll338_dll_338_dtor
#define dll_338_create __dll338_dll_338_create
#define dll_338_update __dll338_dll_338_update
#define dll_338_func_4A8 __dll338_dll_338_func_4A8
#define dll_338_draw __dll338_dll_338_draw
#define dll_338_destroy __dll338_dll_338_destroy
#define dll_338_get_model_flags __dll338_dll_338_get_model_flags
#define dll_338_get_state_size __dll338_dll_338_get_state_size
#define dll_338_func_5AC __dll338_dll_338_func_5AC
#define dll_338_func_6B8 __dll338_dll_338_func_6B8
#define dll_338_func_6DC __dll338_dll_338_func_6DC
#define _rodata_0 __dll338__rodata_0
#define _data_0 __dll338__data_0
#define _bss_0 __dll338__bss_0
#define _bss_E __dll338__bss_E

#endif //_DLL_338_RECOMP_H
