// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_339_RECOMP_H
#define _DLL_339_RECOMP_H

#define dll_339_ctor __dll339_dll_339_ctor
#define dll_339_dtor __dll339_dll_339_dtor
#define dll_339_func_18 __dll339_dll_339_func_18
#define dll_339_func_D4 __dll339_dll_339_func_D4
#define dll_339_func_E0 __dll339_dll_339_func_E0
#define dll_339_func_EC __dll339_dll_339_func_EC
#define dll_339_func_140 __dll339_dll_339_func_140
#define dll_339_func_150 __dll339_dll_339_func_150
#define dll_339_func_160 __dll339_dll_339_func_160

#endif //_DLL_339_RECOMP_H
