// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_340_RECOMP_H
#define _DLL_340_RECOMP_H

#define dll_340_ctor __dll340_dll_340_ctor
#define dll_340_dtor __dll340_dll_340_dtor
#define dll_340_func_18 __dll340_dll_340_func_18
#define dll_340_func_144 __dll340_dll_340_func_144
#define dll_340_func_384 __dll340_dll_340_func_384
#define dll_340_func_390 __dll340_dll_340_func_390
#define dll_340_func_3A8 __dll340_dll_340_func_3A8
#define dll_340_func_3F0 __dll340_dll_340_func_3F0
#define dll_340_func_400 __dll340_dll_340_func_400
#define dll_340_func_414 __dll340_dll_340_func_414
#define dll_340_func_4BC __dll340_dll_340_func_4BC
#define dll_340_func_D40 __dll340_dll_340_func_D40
#define _rodata_0 __dll340__rodata_0

#endif //_DLL_340_RECOMP_H
