// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_343_RECOMP_H
#define _DLL_343_RECOMP_H

#define dll_343_ctor __dll343_dll_343_ctor
#define dll_343_dtor __dll343_dll_343_dtor
#define dll_343_func_18 __dll343_dll_343_func_18
#define dll_343_func_E4 __dll343_dll_343_func_E4
#define dll_343_func_240 __dll343_dll_343_func_240
#define dll_343_func_24C __dll343_dll_343_func_24C
#define dll_343_func_264 __dll343_dll_343_func_264
#define dll_343_func_274 __dll343_dll_343_func_274
#define dll_343_func_284 __dll343_dll_343_func_284
#define str_0 __dll343_str_0

#endif //_DLL_343_RECOMP_H
