// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_344_RECOMP_H
#define _DLL_344_RECOMP_H

#define dll_344_ctor __dll344_dll_344_ctor
#define dll_344_dtor __dll344_dll_344_dtor
#define dll_344_func_7C __dll344_dll_344_func_7C
#define dll_344_func_190 __dll344_dll_344_func_190
#define dll_344_func_1D4 __dll344_dll_344_func_1D4
#define dll_344_func_1E0 __dll344_dll_344_func_1E0
#define dll_344_func_494 __dll344_dll_344_func_494
#define dll_344_func_4F0 __dll344_dll_344_func_4F0
#define dll_344_func_500 __dll344_dll_344_func_500
#define dll_344_func_514 __dll344_dll_344_func_514
#define dll_344_func_5AC __dll344_dll_344_func_5AC
#define str_0 __dll344_str_0
#define str_10 __dll344_str_10
#define str_24 __dll344_str_24
#define _data_0 __dll344__data_0
#define _data_8 __dll344__data_8

#endif //_DLL_344_RECOMP_H
