// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_346_RECOMP_H
#define _DLL_346_RECOMP_H

#define dll_346_ctor __dll346_dll_346_ctor
#define dll_346_dtor __dll346_dll_346_dtor
#define dll_346_func_18 __dll346_dll_346_func_18
#define dll_346_func_2C __dll346_dll_346_func_2C
#define dll_346_func_38 __dll346_dll_346_func_38
#define dll_346_func_44 __dll346_dll_346_func_44
#define dll_346_func_98 __dll346_dll_346_func_98
#define dll_346_func_A8 __dll346_dll_346_func_A8
#define dll_346_func_B8 __dll346_dll_346_func_B8
#define _oob_rodata_0 __dll346__oob_rodata_0

#endif //_DLL_346_RECOMP_H
