// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_346_RECOMP_H
#define _DLL_346_RECOMP_H

#define dll_346_ctor __dll346_dll_346_ctor
#define dll_346_dtor __dll346_dll_346_dtor
#define dll_346_create __dll346_dll_346_create
#define dll_346_update __dll346_dll_346_update
#define dll_346_func_38 __dll346_dll_346_func_38
#define dll_346_draw __dll346_dll_346_draw
#define dll_346_destroy __dll346_dll_346_destroy
#define dll_346_get_setup_flags __dll346_dll_346_get_setup_flags
#define dll_346_get_state_size __dll346_dll_346_get_state_size
#define _oob_rodata_0 __dll346__oob_rodata_0

#endif //_DLL_346_RECOMP_H
