// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_347_RECOMP_H
#define _DLL_347_RECOMP_H

#define dll_347_ctor __dll347_dll_347_ctor
#define dll_347_dtor __dll347_dll_347_dtor
#define dll_347_func_18 __dll347_dll_347_func_18
#define dll_347_func_80 __dll347_dll_347_func_80
#define dll_347_func_128 __dll347_dll_347_func_128
#define dll_347_func_134 __dll347_dll_347_func_134
#define dll_347_func_188 __dll347_dll_347_func_188
#define dll_347_func_198 __dll347_dll_347_func_198
#define dll_347_func_1A8 __dll347_dll_347_func_1A8
#define dll_347_func_1BC __dll347_dll_347_func_1BC
#define dll_347_func_468 __dll347_dll_347_func_468
#define str_0 __dll347_str_0

#endif //_DLL_347_RECOMP_H
