// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_351_RECOMP_H
#define _DLL_351_RECOMP_H

#define dll_351_ctor __dll351_dll_351_ctor
#define dll_351_dtor __dll351_dll_351_dtor
#define dll_351_setup __dll351_dll_351_setup
#define dll_351_control __dll351_dll_351_control
#define dll_351_update __dll351_dll_351_update
#define dll_351_print __dll351_dll_351_print
#define dll_351_free __dll351_dll_351_free
#define dll_351_get_model_flags __dll351_dll_351_get_model_flags
#define dll_351_get_data_size __dll351_dll_351_get_data_size
#define dll_351_func_A28 __dll351_dll_351_func_A28
#define dll_351_func_C90 __dll351_dll_351_func_C90
#define dll_351_func_DFC __dll351_dll_351_func_DFC
#define dll_351_func_E38 __dll351_dll_351_func_E38
#define str_0 __dll351_str_0
#define _data_0 __dll351__data_0

#endif //_DLL_351_RECOMP_H
