// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_351_RECOMP_H
#define _DLL_351_RECOMP_H

#define dll_351_ctor __dll351_dll_351_ctor
#define dll_351_dtor __dll351_dll_351_dtor
#define dll_351_create __dll351_dll_351_create
#define dll_351_update __dll351_dll_351_update
#define dll_351_func_950 __dll351_dll_351_func_950
#define dll_351_draw __dll351_dll_351_draw
#define dll_351_destroy __dll351_dll_351_destroy
#define dll_351_get_setup_flags __dll351_dll_351_get_setup_flags
#define dll_351_get_state_size __dll351_dll_351_get_state_size
#define dll_351_func_A28 __dll351_dll_351_func_A28
#define dll_351_func_C90 __dll351_dll_351_func_C90
#define dll_351_func_DFC __dll351_dll_351_func_DFC
#define dll_351_func_E38 __dll351_dll_351_func_E38
#define str_0 __dll351_str_0
#define _data_0 __dll351__data_0

#endif //_DLL_351_RECOMP_H
