// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_352_RECOMP_H
#define _DLL_352_RECOMP_H

#define dll_352_ctor __dll352_dll_352_ctor
#define dll_352_dtor __dll352_dll_352_dtor
#define dll_352_func_18 __dll352_dll_352_func_18
#define dll_352_func_2C8 __dll352_dll_352_func_2C8
#define dll_352_func_EE0 __dll352_dll_352_func_EE0
#define dll_352_func_EEC __dll352_dll_352_func_EEC
#define dll_352_func_F04 __dll352_dll_352_func_F04
#define dll_352_func_FE4 __dll352_dll_352_func_FE4
#define dll_352_func_FF4 __dll352_dll_352_func_FF4
#define dll_352_func_1008 __dll352_dll_352_func_1008
#define dll_352_func_11A0 __dll352_dll_352_func_11A0
#define _rodata_0 __dll352__rodata_0
#define _rodata_4 __dll352__rodata_4
#define _rodata_8 __dll352__rodata_8
#define _rodata_C __dll352__rodata_C
#define _rodata_10 __dll352__rodata_10
#define _data_0 __dll352__data_0

#endif //_DLL_352_RECOMP_H
