// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_362_RECOMP_H
#define _DLL_362_RECOMP_H

#define dll_362_ctor __dll362_dll_362_ctor
#define dll_362_dtor __dll362_dll_362_dtor
#define dll_362_func_18 __dll362_dll_362_func_18
#define dll_362_func_78 __dll362_dll_362_func_78
#define dll_362_func_310 __dll362_dll_362_func_310
#define dll_362_func_414 __dll362_dll_362_func_414
#define dll_362_func_420 __dll362_dll_362_func_420
#define dll_362_func_474 __dll362_dll_362_func_474
#define dll_362_func_4C4 __dll362_dll_362_func_4C4
#define dll_362_func_4D4 __dll362_dll_362_func_4D4
#define str_0 __dll362_str_0

#endif //_DLL_362_RECOMP_H
