// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_363_RECOMP_H
#define _DLL_363_RECOMP_H

#define dll_363_ctor __dll363_dll_363_ctor
#define dll_363_dtor __dll363_dll_363_dtor
#define dll_363_create __dll363_dll_363_create
#define dll_363_update __dll363_dll_363_update
#define dll_363_func_68 __dll363_dll_363_func_68
#define dll_363_draw __dll363_dll_363_draw
#define dll_363_destroy __dll363_dll_363_destroy
#define dll_363_get_setup_flags __dll363_dll_363_get_setup_flags
#define dll_363_get_state_size __dll363_dll_363_get_state_size

#endif //_DLL_363_RECOMP_H
