// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_363_RECOMP_H
#define _DLL_363_RECOMP_H

#define dll_363_ctor __dll363_dll_363_ctor
#define dll_363_dtor __dll363_dll_363_dtor
#define dll_363_func_18 __dll363_dll_363_func_18
#define dll_363_func_5C __dll363_dll_363_func_5C
#define dll_363_func_68 __dll363_dll_363_func_68
#define dll_363_func_74 __dll363_dll_363_func_74
#define dll_363_func_C8 __dll363_dll_363_func_C8
#define dll_363_func_D8 __dll363_dll_363_func_D8
#define dll_363_func_E8 __dll363_dll_363_func_E8

#endif //_DLL_363_RECOMP_H
