// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_364_RECOMP_H
#define _DLL_364_RECOMP_H

#define dll_364_ctor __dll364_dll_364_ctor
#define dll_364_dtor __dll364_dll_364_dtor
#define dll_364_func_18 __dll364_dll_364_func_18
#define dll_364_func_6C __dll364_dll_364_func_6C
#define dll_364_func_E4 __dll364_dll_364_func_E4
#define dll_364_func_F0 __dll364_dll_364_func_F0
#define dll_364_func_144 __dll364_dll_364_func_144
#define dll_364_func_154 __dll364_dll_364_func_154
#define dll_364_func_164 __dll364_dll_364_func_164
#define dll_364_func_178 __dll364_dll_364_func_178
#define _data_0 __dll364__data_0

#endif //_DLL_364_RECOMP_H
