// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_366_RECOMP_H
#define _DLL_366_RECOMP_H

#define dll_366_ctor __dll366_dll_366_ctor
#define dll_366_dtor __dll366_dll_366_dtor
#define dll_366_func_30 __dll366_dll_366_func_30
#define dll_366_func_74 __dll366_dll_366_func_74
#define dll_366_func_32C __dll366_dll_366_func_32C
#define dll_366_func_338 __dll366_dll_366_func_338
#define dll_366_func_38C __dll366_dll_366_func_38C
#define dll_366_func_39C __dll366_dll_366_func_39C
#define dll_366_func_3AC __dll366_dll_366_func_3AC
#define dll_366_func_3C0 __dll366_dll_366_func_3C0
#define str_0 __dll366_str_0
#define _data_0 __dll366__data_0
#define _data_4 __dll366__data_4
#define _data_8 __dll366__data_8
#define _bss_0 __dll366__bss_0
#define _bss_8 __dll366__bss_8
#define _bss_90 __dll366__bss_90

#endif //_DLL_366_RECOMP_H
