// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_366_RECOMP_H
#define _DLL_366_RECOMP_H

#define dll_366_ctor __dll366_dll_366_ctor
#define dll_366_dtor __dll366_dll_366_dtor
#define dll_366_obj_Setup __dll366_dll_366_obj_Setup
#define dll_366_obj_Control __dll366_dll_366_obj_Control
#define dll_366_obj_Update __dll366_dll_366_obj_Update
#define dll_366_obj_Print __dll366_dll_366_obj_Print
#define dll_366_obj_Free __dll366_dll_366_obj_Free
#define dll_366_obj_GetModelFlags __dll366_dll_366_obj_GetModelFlags
#define dll_366_obj_GetDataSize __dll366_dll_366_obj_GetDataSize
#define dll_366_func_3C0 __dll366_dll_366_func_3C0
#define str_0 __dll366_str_0
#define data_0 __dll366_data_0
#define data_4 __dll366_data_4
#define data_8 __dll366_data_8
#define bss_0 __dll366_bss_0
#define bss_8 __dll366_bss_8
#define bss_90 __dll366_bss_90

#endif //_DLL_366_RECOMP_H
