// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_367_RECOMP_H
#define _DLL_367_RECOMP_H

#define dll_367_ctor __dll367_dll_367_ctor
#define dll_367_dtor __dll367_dll_367_dtor
#define dll_367_create __dll367_dll_367_create
#define dll_367_update __dll367_dll_367_update
#define dll_367_func_654 __dll367_dll_367_func_654
#define dll_367_draw __dll367_dll_367_draw
#define dll_367_destroy __dll367_dll_367_destroy
#define dll_367_get_model_flags __dll367_dll_367_get_model_flags
#define dll_367_get_state_size __dll367_dll_367_get_state_size
#define dll_367_func_728 __dll367_dll_367_func_728
#define dll_367_func_7F0 __dll367_dll_367_func_7F0
#define dll_367_func_9DC __dll367_dll_367_func_9DC
#define dll_367_func_A3C __dll367_dll_367_func_A3C
#define dll_367_func_D64 __dll367_dll_367_func_D64
#define _data_0 __dll367__data_0
#define _data_4 __dll367__data_4
#define _data_8 __dll367__data_8
#define _data_C __dll367__data_C
#define _data_10 __dll367__data_10
#define _data_18 __dll367__data_18
#define _bss_0 __dll367__bss_0
#define _bss_4 __dll367__bss_4
#define _bss_8 __dll367__bss_8
#define _bss_90 __dll367__bss_90
#define _bss_130 __dll367__bss_130
#define _bss_138 __dll367__bss_138
#define _bss_158 __dll367__bss_158
#define _bss_160 __dll367__bss_160

#endif //_DLL_367_RECOMP_H
