// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_368_RECOMP_H
#define _DLL_368_RECOMP_H

#define dll_368_ctor __dll368_dll_368_ctor
#define dll_368_dtor __dll368_dll_368_dtor
#define dll_368_func_18 __dll368_dll_368_func_18
#define dll_368_func_6C __dll368_dll_368_func_6C
#define dll_368_func_390 __dll368_dll_368_func_390
#define dll_368_func_39C __dll368_dll_368_func_39C
#define dll_368_func_3F0 __dll368_dll_368_func_3F0
#define dll_368_func_400 __dll368_dll_368_func_400
#define dll_368_func_410 __dll368_dll_368_func_410
#define dll_368_func_424 __dll368_dll_368_func_424
#define _rodata_20 __dll368__rodata_20

#endif //_DLL_368_RECOMP_H
