// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_370_RECOMP_H
#define _DLL_370_RECOMP_H

#define dll_370_ctor __dll370_dll_370_ctor
#define dll_370_dtor __dll370_dll_370_dtor
#define dll_370_obj_Setup __dll370_dll_370_obj_Setup
#define dll_370_obj_Control __dll370_dll_370_obj_Control
#define dll_370_obj_Update __dll370_dll_370_obj_Update
#define dll_370_obj_Print __dll370_dll_370_obj_Print
#define dll_370_obj_Free __dll370_dll_370_obj_Free
#define dll_370_obj_GetModelFlags __dll370_dll_370_obj_GetModelFlags
#define dll_370_obj_GetDataSize __dll370_dll_370_obj_GetDataSize
#define dll_370_func_880 __dll370_dll_370_func_880
#define dll_370_func_F0C __dll370_dll_370_func_F0C
#define str_0 __dll370_str_0
#define rodata_24 __dll370_rodata_24
#define rodata_28 __dll370_rodata_28
#define rodata_2C __dll370_rodata_2C
#define rodata_30 __dll370_rodata_30
#define rodata_34 __dll370_rodata_34
#define rodata_38 __dll370_rodata_38
#define rodata_3C __dll370_rodata_3C
#define rodata_40 __dll370_rodata_40
#define rodata_44 __dll370_rodata_44
#define rodata_48 __dll370_rodata_48
#define rodata_4C __dll370_rodata_4C
#define rodata_50 __dll370_rodata_50
#define rodata_54 __dll370_rodata_54

#endif //_DLL_370_RECOMP_H
