// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_370_RECOMP_H
#define _DLL_370_RECOMP_H

#define dll_370_ctor __dll370_dll_370_ctor
#define dll_370_dtor __dll370_dll_370_dtor
#define dll_370_func_18 __dll370_dll_370_func_18
#define dll_370_func_F8 __dll370_dll_370_func_F8
#define dll_370_func_7A0 __dll370_dll_370_func_7A0
#define dll_370_func_7AC __dll370_dll_370_func_7AC
#define dll_370_func_800 __dll370_dll_370_func_800
#define dll_370_func_85C __dll370_dll_370_func_85C
#define dll_370_func_86C __dll370_dll_370_func_86C
#define dll_370_func_880 __dll370_dll_370_func_880
#define dll_370_func_F0C __dll370_dll_370_func_F0C
#define str_0 __dll370_str_0
#define _rodata_24 __dll370__rodata_24
#define _rodata_28 __dll370__rodata_28
#define _rodata_2C __dll370__rodata_2C
#define _rodata_30 __dll370__rodata_30
#define _rodata_34 __dll370__rodata_34
#define _rodata_38 __dll370__rodata_38
#define _rodata_3C __dll370__rodata_3C
#define _rodata_40 __dll370__rodata_40
#define _rodata_44 __dll370__rodata_44
#define _rodata_48 __dll370__rodata_48
#define _rodata_4C __dll370__rodata_4C
#define _rodata_50 __dll370__rodata_50
#define _rodata_54 __dll370__rodata_54

#endif //_DLL_370_RECOMP_H
