// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_370_RECOMP_H
#define _DLL_370_RECOMP_H

#define dll_370_ctor __dll370_dll_370_ctor
#define dll_370_dtor __dll370_dll_370_dtor
#define dll_370_setup __dll370_dll_370_setup
#define dll_370_control __dll370_dll_370_control
#define dll_370_update __dll370_dll_370_update
#define dll_370_print __dll370_dll_370_print
#define dll_370_free __dll370_dll_370_free
#define dll_370_get_model_flags __dll370_dll_370_get_model_flags
#define dll_370_get_data_size __dll370_dll_370_get_data_size
#define dll_370_func_880 __dll370_dll_370_func_880
#define dll_370_func_F0C __dll370_dll_370_func_F0C
#define str_0 __dll370_str_0
#define _rodata_24 __dll370__rodata_24
#define _rodata_28 __dll370__rodata_28
#define _rodata_2C __dll370__rodata_2C
#define _rodata_30 __dll370__rodata_30
#define _rodata_34 __dll370__rodata_34
#define _rodata_38 __dll370__rodata_38
#define _rodata_3C __dll370__rodata_3C
#define _rodata_40 __dll370__rodata_40
#define _rodata_44 __dll370__rodata_44
#define _rodata_48 __dll370__rodata_48
#define _rodata_4C __dll370__rodata_4C
#define _rodata_50 __dll370__rodata_50
#define _rodata_54 __dll370__rodata_54

#endif //_DLL_370_RECOMP_H
