// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_372_RECOMP_H
#define _DLL_372_RECOMP_H

#define dll_372_ctor __dll372_dll_372_ctor
#define dll_372_dtor __dll372_dll_372_dtor
#define dll_372_setup __dll372_dll_372_setup
#define dll_372_control __dll372_dll_372_control
#define dll_372_update __dll372_dll_372_update
#define dll_372_print __dll372_dll_372_print
#define dll_372_free __dll372_dll_372_free
#define dll_372_get_model_flags __dll372_dll_372_get_model_flags
#define dll_372_get_data_size __dll372_dll_372_get_data_size
#define dll_372_func_288 __dll372_dll_372_func_288
#define dll_372_func_11B8 __dll372_dll_372_func_11B8
#define str_0 __dll372_str_0
#define rodata_34 __dll372_rodata_34
#define rodata_38 __dll372_rodata_38
#define rodata_3C __dll372_rodata_3C
#define rodata_40 __dll372_rodata_40
#define rodata_44 __dll372_rodata_44
#define data_0 __dll372_data_0
#define data_C __dll372_data_C
#define data_10 __dll372_data_10
#define bss_0 __dll372_bss_0

#endif //_DLL_372_RECOMP_H
