// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_375_RECOMP_H
#define _DLL_375_RECOMP_H

#define dll_375_ctor __dll375_dll_375_ctor
#define dll_375_dtor __dll375_dll_375_dtor
#define dll_375_create __dll375_dll_375_create
#define dll_375_update __dll375_dll_375_update
#define dll_375_func_274 __dll375_dll_375_func_274
#define dll_375_draw __dll375_dll_375_draw
#define dll_375_destroy __dll375_dll_375_destroy
#define dll_375_get_setup_flags __dll375_dll_375_get_setup_flags
#define dll_375_get_state_size __dll375_dll_375_get_state_size
#define dll_375_func_4B8 __dll375_dll_375_func_4B8
#define str_0 __dll375_str_0
#define str_40 __dll375_str_40
#define _rodata_64 __dll375__rodata_64
#define _rodata_68 __dll375__rodata_68

#endif //_DLL_375_RECOMP_H
