// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_377_RECOMP_H
#define _DLL_377_RECOMP_H

#define dll_377_ctor __dll377_dll_377_ctor
#define dll_377_dtor __dll377_dll_377_dtor
#define dll_377_create __dll377_dll_377_create
#define dll_377_update __dll377_dll_377_update
#define dll_377_func_1EC __dll377_dll_377_func_1EC
#define dll_377_draw __dll377_dll_377_draw
#define dll_377_destroy __dll377_dll_377_destroy
#define dll_377_get_model_flags __dll377_dll_377_get_model_flags
#define dll_377_get_state_size __dll377_dll_377_get_state_size
#define dll_377_func_484 __dll377_dll_377_func_484
#define str_0 __dll377_str_0

#endif //_DLL_377_RECOMP_H
