// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_377_RECOMP_H
#define _DLL_377_RECOMP_H

#define dll_377_ctor __dll377_dll_377_ctor
#define dll_377_dtor __dll377_dll_377_dtor
#define dll_377_setup __dll377_dll_377_setup
#define dll_377_control __dll377_dll_377_control
#define dll_377_update __dll377_dll_377_update
#define dll_377_print __dll377_dll_377_print
#define dll_377_free __dll377_dll_377_free
#define dll_377_get_model_flags __dll377_dll_377_get_model_flags
#define dll_377_get_data_size __dll377_dll_377_get_data_size
#define dll_377_func_484 __dll377_dll_377_func_484
#define str_0 __dll377_str_0

#endif //_DLL_377_RECOMP_H
