// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_378_RECOMP_H
#define _DLL_378_RECOMP_H

#define dll_378_ctor __dll378_dll_378_ctor
#define dll_378_dtor __dll378_dll_378_dtor
#define dll_378_setup __dll378_dll_378_setup
#define dll_378_control __dll378_dll_378_control
#define dll_378_update __dll378_dll_378_update
#define dll_378_print __dll378_dll_378_print
#define dll_378_free __dll378_dll_378_free
#define dll_378_get_model_flags __dll378_dll_378_get_model_flags
#define dll_378_get_data_size __dll378_dll_378_get_data_size
#define dll_378_func_16C __dll378_dll_378_func_16C
#define _data_0 __dll378__data_0

#endif //_DLL_378_RECOMP_H
