// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_379_RECOMP_H
#define _DLL_379_RECOMP_H

#define dll_379_ctor __dll379_dll_379_ctor
#define dll_379_dtor __dll379_dll_379_dtor
#define dll_379_func_18 __dll379_dll_379_func_18
#define dll_379_func_30 __dll379_dll_379_func_30
#define dll_379_func_3C __dll379_dll_379_func_3C
#define dll_379_func_48 __dll379_dll_379_func_48
#define dll_379_func_9C __dll379_dll_379_func_9C
#define dll_379_func_AC __dll379_dll_379_func_AC
#define dll_379_func_BC __dll379_dll_379_func_BC
#define _oob_rodata_0 __dll379__oob_rodata_0

#endif //_DLL_379_RECOMP_H
