// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_382_RECOMP_H
#define _DLL_382_RECOMP_H

#define dll_382_ctor __dll382_dll_382_ctor
#define dll_382_dtor __dll382_dll_382_dtor
#define dll_382_create __dll382_dll_382_create
#define dll_382_update __dll382_dll_382_update
#define dll_382_func_F4 __dll382_dll_382_func_F4
#define dll_382_draw __dll382_dll_382_draw
#define dll_382_destroy __dll382_dll_382_destroy
#define dll_382_get_setup_flags __dll382_dll_382_get_setup_flags
#define dll_382_get_state_size __dll382_dll_382_get_state_size

#endif //_DLL_382_RECOMP_H
