// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_382_RECOMP_H
#define _DLL_382_RECOMP_H

#define dll_382_ctor __dll382_dll_382_ctor
#define dll_382_dtor __dll382_dll_382_dtor
#define dll_382_func_18 __dll382_dll_382_func_18
#define dll_382_func_2C __dll382_dll_382_func_2C
#define dll_382_func_F4 __dll382_dll_382_func_F4
#define dll_382_func_100 __dll382_dll_382_func_100
#define dll_382_func_118 __dll382_dll_382_func_118
#define dll_382_func_128 __dll382_dll_382_func_128
#define dll_382_func_138 __dll382_dll_382_func_138

#endif //_DLL_382_RECOMP_H
