// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_387_RECOMP_H
#define _DLL_387_RECOMP_H

#define dll_387_ctor __dll387_dll_387_ctor
#define dll_387_dtor __dll387_dll_387_dtor
#define dll_387_create __dll387_dll_387_create
#define dll_387_update __dll387_dll_387_update
#define dll_387_func_254 __dll387_dll_387_func_254
#define dll_387_draw __dll387_dll_387_draw
#define dll_387_destroy __dll387_dll_387_destroy
#define dll_387_get_setup_flags __dll387_dll_387_get_setup_flags
#define dll_387_get_state_size __dll387_dll_387_get_state_size
#define str_0 __dll387_str_0

#endif //_DLL_387_RECOMP_H
