// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_389_RECOMP_H
#define _DLL_389_RECOMP_H

#define dll_389_ctor __dll389_dll_389_ctor
#define dll_389_dtor __dll389_dll_389_dtor
#define dll_389_func_18 __dll389_dll_389_func_18
#define dll_389_func_138 __dll389_dll_389_func_138
#define dll_389_func_3D8 __dll389_dll_389_func_3D8
#define dll_389_func_3E4 __dll389_dll_389_func_3E4
#define dll_389_func_45C __dll389_dll_389_func_45C
#define dll_389_func_46C __dll389_dll_389_func_46C
#define dll_389_func_47C __dll389_dll_389_func_47C
#define dll_389_func_490 __dll389_dll_389_func_490
#define str_0 __dll389_str_0
#define _data_0 __dll389__data_0
#define _bss_0 __dll389__bss_0

#endif //_DLL_389_RECOMP_H
