// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_38_RECOMP_H
#define _DLL_38_RECOMP_H

#define dll_38_ctor __dll38_dll_38_ctor
#define dll_38_dtor __dll38_dll_38_dtor
#define dll_38_func_18 __dll38_dll_38_func_18
#define dll_38_func_20 __dll38_dll_38_func_20
#define dll_38_func_194 __dll38_dll_38_func_194
#define rodata_0 __dll38_rodata_0
#define rodata_4 __dll38_rodata_4
#define rodata_8 __dll38_rodata_8
#define rodata_C __dll38_rodata_C
#define rodata_10 __dll38_rodata_10
#define rodata_14 __dll38_rodata_14
#define rodata_18 __dll38_rodata_18
#define rodata_5C __dll38_rodata_5C
#define rodata_60 __dll38_rodata_60
#define rodata_64 __dll38_rodata_64
#define rodata_68 __dll38_rodata_68
#define rodata_6C __dll38_rodata_6C
#define rodata_70 __dll38_rodata_70
#define rodata_74 __dll38_rodata_74
#define rodata_78 __dll38_rodata_78
#define rodata_7C __dll38_rodata_7C
#define rodata_80 __dll38_rodata_80
#define rodata_84 __dll38_rodata_84
#define rodata_88 __dll38_rodata_88
#define rodata_8C __dll38_rodata_8C
#define rodata_90 __dll38_rodata_90
#define rodata_94 __dll38_rodata_94
#define rodata_98 __dll38_rodata_98
#define rodata_9C __dll38_rodata_9C
#define rodata_A0 __dll38_rodata_A0
#define rodata_A4 __dll38_rodata_A4
#define rodata_A8 __dll38_rodata_A8
#define rodata_AC __dll38_rodata_AC
#define rodata_B0 __dll38_rodata_B0
#define rodata_B4 __dll38_rodata_B4
#define rodata_B8 __dll38_rodata_B8
#define rodata_BC __dll38_rodata_BC
#define rodata_C0 __dll38_rodata_C0
#define rodata_C4 __dll38_rodata_C4
#define rodata_C8 __dll38_rodata_C8
#define rodata_CC __dll38_rodata_CC
#define rodata_D0 __dll38_rodata_D0
#define rodata_D4 __dll38_rodata_D4
#define rodata_D8 __dll38_rodata_D8
#define rodata_DC __dll38_rodata_DC
#define rodata_E0 __dll38_rodata_E0
#define data_0 __dll38_data_0
#define data_40 __dll38_data_40
#define data_44 __dll38_data_44
#define data_48 __dll38_data_48
#define data_4C __dll38_data_4C
#define data_50 __dll38_data_50
#define data_54 __dll38_data_54
#define data_58 __dll38_data_58
#define data_5C __dll38_data_5C

#endif //_DLL_38_RECOMP_H
