// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_390_RECOMP_H
#define _DLL_390_RECOMP_H

#define dll_390_ctor __dll390_dll_390_ctor
#define dll_390_dtor __dll390_dll_390_dtor
#define dll_390_setup __dll390_dll_390_setup
#define dll_390_control __dll390_dll_390_control
#define dll_390_update __dll390_dll_390_update
#define dll_390_print __dll390_dll_390_print
#define dll_390_free __dll390_dll_390_free
#define dll_390_get_model_flags __dll390_dll_390_get_model_flags
#define dll_390_get_data_size __dll390_dll_390_get_data_size
#define dll_390_func_3E8 __dll390_dll_390_func_3E8
#define dll_390_func_884 __dll390_dll_390_func_884
#define dll_390_func_C60 __dll390_dll_390_func_C60
#define str_0 __dll390_str_0
#define rodata_AC __dll390_rodata_AC
#define data_0 __dll390_data_0
#define data_2E4 __dll390_data_2E4
#define data_2E8 __dll390_data_2E8
#define data_2EC __dll390_data_2EC
#define data_2F0 __dll390_data_2F0
#define data_2F4 __dll390_data_2F4
#define data_2F8 __dll390_data_2F8
#define data_2FC __dll390_data_2FC
#define data_300 __dll390_data_300
#define data_304 __dll390_data_304
#define data_308 __dll390_data_308
#define data_30C __dll390_data_30C
#define data_310 __dll390_data_310
#define data_314 __dll390_data_314
#define data_394 __dll390_data_394

#endif //_DLL_390_RECOMP_H
