// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_391_RECOMP_H
#define _DLL_391_RECOMP_H

#define dll_391_ctor __dll391_dll_391_ctor
#define dll_391_dtor __dll391_dll_391_dtor
#define dll_391_func_18 __dll391_dll_391_func_18
#define dll_391_func_168 __dll391_dll_391_func_168
#define dll_391_func_3E0 __dll391_dll_391_func_3E0
#define dll_391_func_3EC __dll391_dll_391_func_3EC
#define dll_391_func_528 __dll391_dll_391_func_528
#define dll_391_func_538 __dll391_dll_391_func_538
#define dll_391_func_548 __dll391_dll_391_func_548
#define dll_391_func_55C __dll391_dll_391_func_55C
#define dll_391_func_5A4 __dll391_dll_391_func_5A4
#define dll_391_func_66C __dll391_dll_391_func_66C
#define _rodata_0 __dll391__rodata_0
#define _rodata_4 __dll391__rodata_4
#define _rodata_8 __dll391__rodata_8
#define _rodata_C __dll391__rodata_C
#define _rodata_10 __dll391__rodata_10

#endif //_DLL_391_RECOMP_H
