// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_393_RECOMP_H
#define _DLL_393_RECOMP_H

#define dll_393_ctor __dll393_dll_393_ctor
#define dll_393_dtor __dll393_dll_393_dtor
#define dll_393_create __dll393_dll_393_create
#define dll_393_update __dll393_dll_393_update
#define dll_393_func_1D4 __dll393_dll_393_func_1D4
#define dll_393_draw __dll393_dll_393_draw
#define dll_393_destroy __dll393_dll_393_destroy
#define dll_393_get_setup_flags __dll393_dll_393_get_setup_flags
#define dll_393_get_state_size __dll393_dll_393_get_state_size
#define dll_393_func_268 __dll393_dll_393_func_268

#endif //_DLL_393_RECOMP_H
