// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_394_RECOMP_H
#define _DLL_394_RECOMP_H

#define dll_394_ctor __dll394_dll_394_ctor
#define dll_394_dtor __dll394_dll_394_dtor
#define dll_394_setup __dll394_dll_394_setup
#define dll_394_control __dll394_dll_394_control
#define dll_394_update __dll394_dll_394_update
#define dll_394_print __dll394_dll_394_print
#define dll_394_free __dll394_dll_394_free
#define dll_394_get_model_flags __dll394_dll_394_get_model_flags
#define dll_394_get_data_size __dll394_dll_394_get_data_size
#define _rodata_0 __dll394__rodata_0
#define _rodata_4 __dll394__rodata_4
#define _rodata_8 __dll394__rodata_8
#define _data_0 __dll394__data_0

#endif //_DLL_394_RECOMP_H
