// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_395_RECOMP_H
#define _DLL_395_RECOMP_H

#define dll_395_ctor __dll395_dll_395_ctor
#define dll_395_dtor __dll395_dll_395_dtor
#define dll_395_setup __dll395_dll_395_setup
#define dll_395_control __dll395_dll_395_control
#define dll_395_update __dll395_dll_395_update
#define dll_395_print __dll395_dll_395_print
#define dll_395_free __dll395_dll_395_free
#define dll_395_get_model_flags __dll395_dll_395_get_model_flags
#define dll_395_get_data_size __dll395_dll_395_get_data_size
#define dll_395_func_190 __dll395_dll_395_func_190
#define dll_395_func_1B4 __dll395_dll_395_func_1B4

#endif //_DLL_395_RECOMP_H
