// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_402_RECOMP_H
#define _DLL_402_RECOMP_H

#define dll_402_ctor __dll402_dll_402_ctor
#define dll_402_dtor __dll402_dll_402_dtor
#define dll_402_setup __dll402_dll_402_setup
#define dll_402_control __dll402_dll_402_control
#define dll_402_update __dll402_dll_402_update
#define dll_402_print __dll402_dll_402_print
#define dll_402_free __dll402_dll_402_free
#define dll_402_get_model_flags __dll402_dll_402_get_model_flags
#define dll_402_get_data_size __dll402_dll_402_get_data_size
#define dll_402_func_9A0 __dll402_dll_402_func_9A0
#define str_0 __dll402_str_0
#define _rodata_70 __dll402__rodata_70
#define _rodata_74 __dll402__rodata_74
#define _rodata_78 __dll402__rodata_78
#define _rodata_7C __dll402__rodata_7C
#define _rodata_80 __dll402__rodata_80
#define _data_0 __dll402__data_0
#define _data_4 __dll402__data_4

#endif //_DLL_402_RECOMP_H
