// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_402_RECOMP_H
#define _DLL_402_RECOMP_H

#define dll_402_ctor __dll402_dll_402_ctor
#define dll_402_dtor __dll402_dll_402_dtor
#define dll_402_obj_Setup __dll402_dll_402_obj_Setup
#define dll_402_obj_Control __dll402_dll_402_obj_Control
#define dll_402_obj_Update __dll402_dll_402_obj_Update
#define dll_402_obj_Print __dll402_dll_402_obj_Print
#define dll_402_obj_Free __dll402_dll_402_obj_Free
#define dll_402_obj_GetModelFlags __dll402_dll_402_obj_GetModelFlags
#define dll_402_obj_GetDataSize __dll402_dll_402_obj_GetDataSize
#define dll_402_func_9A0 __dll402_dll_402_func_9A0
#define str_0 __dll402_str_0
#define rodata_70 __dll402_rodata_70
#define rodata_74 __dll402_rodata_74
#define rodata_78 __dll402_rodata_78
#define rodata_7C __dll402_rodata_7C
#define rodata_80 __dll402_rodata_80
#define data_0 __dll402_data_0
#define data_4 __dll402_data_4

#endif //_DLL_402_RECOMP_H
