// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_405_RECOMP_H
#define _DLL_405_RECOMP_H

#define dll_405_ctor __dll405_dll_405_ctor
#define dll_405_dtor __dll405_dll_405_dtor
#define dll_405_func_18 __dll405_dll_405_func_18
#define dll_405_func_84 __dll405_dll_405_func_84
#define dll_405_func_F0 __dll405_dll_405_func_F0
#define dll_405_func_FC __dll405_dll_405_func_FC
#define dll_405_func_534 __dll405_dll_405_func_534
#define dll_405_func_588 __dll405_dll_405_func_588
#define dll_405_func_634 __dll405_dll_405_func_634
#define dll_405_func_644 __dll405_dll_405_func_644
#define _oob_rodata_0 __dll405__oob_rodata_0

#endif //_DLL_405_RECOMP_H
