// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_409_RECOMP_H
#define _DLL_409_RECOMP_H

#define dll_409_ctor __dll409_dll_409_ctor
#define dll_409_dtor __dll409_dll_409_dtor
#define dll_409_create __dll409_dll_409_create
#define dll_409_update __dll409_dll_409_update
#define dll_409_func_74C __dll409_dll_409_func_74C
#define dll_409_draw __dll409_dll_409_draw
#define dll_409_destroy __dll409_dll_409_destroy
#define dll_409_get_model_flags __dll409_dll_409_get_model_flags
#define dll_409_get_state_size __dll409_dll_409_get_state_size
#define dll_409_func_83C __dll409_dll_409_func_83C
#define dll_409_func_940 __dll409_dll_409_func_940
#define _rodata_0 __dll409__rodata_0
#define _rodata_4 __dll409__rodata_4
#define _bss_0 __dll409__bss_0

#endif //_DLL_409_RECOMP_H
