// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_409_RECOMP_H
#define _DLL_409_RECOMP_H

#define dll_409_ctor __dll409_dll_409_ctor
#define dll_409_dtor __dll409_dll_409_dtor
#define dll_409_func_70 __dll409_dll_409_func_70
#define dll_409_func_18C __dll409_dll_409_func_18C
#define dll_409_func_74C __dll409_dll_409_func_74C
#define dll_409_func_758 __dll409_dll_409_func_758
#define dll_409_func_7BC __dll409_dll_409_func_7BC
#define dll_409_func_818 __dll409_dll_409_func_818
#define dll_409_func_828 __dll409_dll_409_func_828
#define dll_409_func_83C __dll409_dll_409_func_83C
#define dll_409_func_940 __dll409_dll_409_func_940
#define _rodata_0 __dll409__rodata_0
#define _rodata_4 __dll409__rodata_4
#define _bss_0 __dll409__bss_0

#endif //_DLL_409_RECOMP_H
