// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_412_RECOMP_H
#define _DLL_412_RECOMP_H

#define dll_412_ctor __dll412_dll_412_ctor
#define dll_412_dtor __dll412_dll_412_dtor
#define dll_412_setup __dll412_dll_412_setup
#define dll_412_control __dll412_dll_412_control
#define dll_412_update __dll412_dll_412_update
#define dll_412_print __dll412_dll_412_print
#define dll_412_free __dll412_dll_412_free
#define dll_412_get_model_flags __dll412_dll_412_get_model_flags
#define dll_412_get_data_size __dll412_dll_412_get_data_size
#define _oob_rodata_0 __dll412__oob_rodata_0

#endif //_DLL_412_RECOMP_H
