// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_414_RECOMP_H
#define _DLL_414_RECOMP_H

#define dll_414_ctor __dll414_dll_414_ctor
#define dll_414_dtor __dll414_dll_414_dtor
#define dll_414_func_18 __dll414_dll_414_func_18
#define dll_414_func_208 __dll414_dll_414_func_208
#define dll_414_func_5A8 __dll414_dll_414_func_5A8
#define dll_414_func_5B4 __dll414_dll_414_func_5B4
#define dll_414_func_608 __dll414_dll_414_func_608
#define dll_414_func_6CC __dll414_dll_414_func_6CC
#define dll_414_func_6DC __dll414_dll_414_func_6DC
#define _rodata_1C __dll414__rodata_1C
#define _rodata_20 __dll414__rodata_20
#define _rodata_24 __dll414__rodata_24
#define _rodata_28 __dll414__rodata_28
#define _data_0 __dll414__data_0
#define _data_C __dll414__data_C

#endif //_DLL_414_RECOMP_H
