// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_414_RECOMP_H
#define _DLL_414_RECOMP_H

#define dll_414_ctor __dll414_dll_414_ctor
#define dll_414_dtor __dll414_dll_414_dtor
#define dll_414_setup __dll414_dll_414_setup
#define dll_414_control __dll414_dll_414_control
#define dll_414_update __dll414_dll_414_update
#define dll_414_print __dll414_dll_414_print
#define dll_414_free __dll414_dll_414_free
#define dll_414_get_model_flags __dll414_dll_414_get_model_flags
#define dll_414_get_data_size __dll414_dll_414_get_data_size
#define rodata_1C __dll414_rodata_1C
#define rodata_20 __dll414_rodata_20
#define rodata_24 __dll414_rodata_24
#define rodata_28 __dll414_rodata_28
#define data_0 __dll414_data_0
#define data_C __dll414_data_C

#endif //_DLL_414_RECOMP_H
