// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_418_RECOMP_H
#define _DLL_418_RECOMP_H

#define dll_418_ctor __dll418_dll_418_ctor
#define dll_418_dtor __dll418_dll_418_dtor
#define dll_418_setup __dll418_dll_418_setup
#define dll_418_control __dll418_dll_418_control
#define dll_418_update __dll418_dll_418_update
#define dll_418_print __dll418_dll_418_print
#define dll_418_free __dll418_dll_418_free
#define dll_418_get_model_flags __dll418_dll_418_get_model_flags
#define dll_418_get_data_size __dll418_dll_418_get_data_size
#define str_0 __dll418_str_0
#define _rodata_28 __dll418__rodata_28

#endif //_DLL_418_RECOMP_H
