// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_423_RECOMP_H
#define _DLL_423_RECOMP_H

#define dll_423_ctor __dll423_dll_423_ctor
#define dll_423_dtor __dll423_dll_423_dtor
#define dll_423_setup __dll423_dll_423_setup
#define dll_423_control __dll423_dll_423_control
#define dll_423_update __dll423_dll_423_update
#define dll_423_print __dll423_dll_423_print
#define dll_423_free __dll423_dll_423_free
#define dll_423_get_model_flags __dll423_dll_423_get_model_flags
#define dll_423_get_data_size __dll423_dll_423_get_data_size
#define dll_423_func_304 __dll423_dll_423_func_304
#define dll_423_func_960 __dll423_dll_423_func_960
#define rodata_0 __dll423_rodata_0
#define rodata_4 __dll423_rodata_4
#define rodata_8 __dll423_rodata_8
#define rodata_C __dll423_rodata_C
#define rodata_10 __dll423_rodata_10
#define rodata_14 __dll423_rodata_14

#endif //_DLL_423_RECOMP_H
