// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_433_RECOMP_H
#define _DLL_433_RECOMP_H

#define dll_433_ctor __dll433_dll_433_ctor
#define dll_433_dtor __dll433_dll_433_dtor
#define dll_433_func_18 __dll433_dll_433_func_18
#define dll_433_func_1A8 __dll433_dll_433_func_1A8
#define dll_433_func_E04 __dll433_dll_433_func_E04
#define dll_433_func_E10 __dll433_dll_433_func_E10
#define dll_433_func_E64 __dll433_dll_433_func_E64
#define dll_433_func_EF4 __dll433_dll_433_func_EF4
#define dll_433_func_F04 __dll433_dll_433_func_F04
#define dll_433_func_F18 __dll433_dll_433_func_F18
#define dll_433_func_12AC __dll433_dll_433_func_12AC
#define str_0 __dll433_str_0
#define _data_0 __dll433__data_0
#define _data_4 __dll433__data_4

#endif //_DLL_433_RECOMP_H
