// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_434_RECOMP_H
#define _DLL_434_RECOMP_H

#define dll_434_ctor __dll434_dll_434_ctor
#define dll_434_dtor __dll434_dll_434_dtor
#define dll_434_create __dll434_dll_434_create
#define dll_434_update __dll434_dll_434_update
#define dll_434_func_3D8 __dll434_dll_434_func_3D8
#define dll_434_draw __dll434_dll_434_draw
#define dll_434_destroy __dll434_dll_434_destroy
#define dll_434_get_model_flags __dll434_dll_434_get_model_flags
#define dll_434_get_state_size __dll434_dll_434_get_state_size
#define _oob_rodata_0 __dll434__oob_rodata_0

#endif //_DLL_434_RECOMP_H
