// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_436_RECOMP_H
#define _DLL_436_RECOMP_H

#define dll_436_ctor __dll436_dll_436_ctor
#define dll_436_dtor __dll436_dll_436_dtor
#define dll_436_obj_Setup __dll436_dll_436_obj_Setup
#define dll_436_obj_Control __dll436_dll_436_obj_Control
#define dll_436_obj_Update __dll436_dll_436_obj_Update
#define dll_436_obj_Print __dll436_dll_436_obj_Print
#define dll_436_obj_Free __dll436_dll_436_obj_Free
#define dll_436_obj_GetModelFlags __dll436_dll_436_obj_GetModelFlags
#define dll_436_obj_GetDataSize __dll436_dll_436_obj_GetDataSize
#define rodata_0 __dll436_rodata_0
#define rodata_4 __dll436_rodata_4
#define rodata_8 __dll436_rodata_8
#define data_0 __dll436_data_0
#define data_8 __dll436_data_8

#endif //_DLL_436_RECOMP_H
