// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_438_RECOMP_H
#define _DLL_438_RECOMP_H

#define dll_438_ctor __dll438_dll_438_ctor
#define dll_438_dtor __dll438_dll_438_dtor
#define dll_438_setup __dll438_dll_438_setup
#define dll_438_control __dll438_dll_438_control
#define dll_438_update __dll438_dll_438_update
#define dll_438_print __dll438_dll_438_print
#define dll_438_free __dll438_dll_438_free
#define dll_438_get_model_flags __dll438_dll_438_get_model_flags
#define dll_438_get_data_size __dll438_dll_438_get_data_size

#endif //_DLL_438_RECOMP_H
