// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_440_RECOMP_H
#define _DLL_440_RECOMP_H

#define dll_440_ctor __dll440_dll_440_ctor
#define dll_440_dtor __dll440_dll_440_dtor
#define dll_440_setup __dll440_dll_440_setup
#define dll_440_control __dll440_dll_440_control
#define dll_440_update __dll440_dll_440_update
#define dll_440_print __dll440_dll_440_print
#define dll_440_free __dll440_dll_440_free
#define dll_440_get_model_flags __dll440_dll_440_get_model_flags
#define dll_440_get_data_size __dll440_dll_440_get_data_size
#define dll_440_func_940 __dll440_dll_440_func_940
#define rodata_0 __dll440_rodata_0
#define rodata_4 __dll440_rodata_4
#define rodata_8 __dll440_rodata_8
#define data_0 __dll440_data_0
#define data_8 __dll440_data_8
#define bss_0 __dll440_bss_0

#endif //_DLL_440_RECOMP_H
