// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_443_RECOMP_H
#define _DLL_443_RECOMP_H

#define dll_443_ctor __dll443_dll_443_ctor
#define dll_443_dtor __dll443_dll_443_dtor
#define dll_443_setup __dll443_dll_443_setup
#define dll_443_control __dll443_dll_443_control
#define dll_443_update __dll443_dll_443_update
#define dll_443_print __dll443_dll_443_print
#define dll_443_free __dll443_dll_443_free
#define dll_443_get_model_flags __dll443_dll_443_get_model_flags
#define dll_443_get_data_size __dll443_dll_443_get_data_size
#define dll_443_func_9C8 __dll443_dll_443_func_9C8
#define _rodata_0 __dll443__rodata_0
#define _rodata_4 __dll443__rodata_4
#define _rodata_8 __dll443__rodata_8
#define _bss_0 __dll443__bss_0
#define _bss_8 __dll443__bss_8
#define _bss_10 __dll443__bss_10
#define _bss_14 __dll443__bss_14
#define _bss_18 __dll443__bss_18
#define _bss_1C __dll443__bss_1C

#endif //_DLL_443_RECOMP_H
