// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_444_RECOMP_H
#define _DLL_444_RECOMP_H

#define dll_444_ctor __dll444_dll_444_ctor
#define dll_444_dtor __dll444_dll_444_dtor
#define dll_444_func_18 __dll444_dll_444_func_18
#define dll_444_func_9C __dll444_dll_444_func_9C
#define dll_444_func_3B4 __dll444_dll_444_func_3B4
#define dll_444_func_3C0 __dll444_dll_444_func_3C0
#define dll_444_func_3D8 __dll444_dll_444_func_3D8
#define dll_444_func_420 __dll444_dll_444_func_420
#define dll_444_func_430 __dll444_dll_444_func_430
#define _rodata_0 __dll444__rodata_0
#define _bss_0 __dll444__bss_0
#define _bss_8 __dll444__bss_8
#define _bss_C __dll444__bss_C
#define _bss_10 __dll444__bss_10
#define _bss_14 __dll444__bss_14

#endif //_DLL_444_RECOMP_H
