// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_445_RECOMP_H
#define _DLL_445_RECOMP_H

#define dll_445_ctor __dll445_dll_445_ctor
#define dll_445_dtor __dll445_dll_445_dtor
#define dll_445_setup __dll445_dll_445_setup
#define dll_445_control __dll445_dll_445_control
#define dll_445_update __dll445_dll_445_update
#define dll_445_print __dll445_dll_445_print
#define dll_445_free __dll445_dll_445_free
#define dll_445_get_model_flags __dll445_dll_445_get_model_flags
#define dll_445_get_data_size __dll445_dll_445_get_data_size
#define dll_445_func_628 __dll445_dll_445_func_628
#define dll_445_func_A8C __dll445_dll_445_func_A8C
#define rodata_0 __dll445_rodata_0
#define rodata_4 __dll445_rodata_4
#define rodata_8 __dll445_rodata_8
#define bss_0 __dll445_bss_0
#define bss_8 __dll445_bss_8
#define bss_C __dll445_bss_C
#define bss_10 __dll445_bss_10
#define bss_14 __dll445_bss_14

#endif //_DLL_445_RECOMP_H
