// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_446_RECOMP_H
#define _DLL_446_RECOMP_H

#define dll_446_ctor __dll446_dll_446_ctor
#define dll_446_dtor __dll446_dll_446_dtor
#define dll_446_func_18 __dll446_dll_446_func_18
#define dll_446_func_80 __dll446_dll_446_func_80
#define dll_446_func_1DC __dll446_dll_446_func_1DC
#define dll_446_func_1E8 __dll446_dll_446_func_1E8
#define dll_446_func_200 __dll446_dll_446_func_200
#define dll_446_func_210 __dll446_dll_446_func_210
#define dll_446_func_220 __dll446_dll_446_func_220
#define _data_0 __dll446__data_0

#endif //_DLL_446_RECOMP_H
