// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_449_RECOMP_H
#define _DLL_449_RECOMP_H

#define dll_449_ctor __dll449_dll_449_ctor
#define dll_449_dtor __dll449_dll_449_dtor
#define dll_449_setup __dll449_dll_449_setup
#define dll_449_control __dll449_dll_449_control
#define dll_449_update __dll449_dll_449_update
#define dll_449_print __dll449_dll_449_print
#define dll_449_free __dll449_dll_449_free
#define dll_449_get_model_flags __dll449_dll_449_get_model_flags
#define dll_449_get_data_size __dll449_dll_449_get_data_size
#define dll_449_func_2B8 __dll449_dll_449_func_2B8

#endif //_DLL_449_RECOMP_H
