// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_449_RECOMP_H
#define _DLL_449_RECOMP_H

#define dll_449_ctor __dll449_dll_449_ctor
#define dll_449_dtor __dll449_dll_449_dtor
#define dll_449_create __dll449_dll_449_create
#define dll_449_update __dll449_dll_449_update
#define dll_449_func_1F4 __dll449_dll_449_func_1F4
#define dll_449_draw __dll449_dll_449_draw
#define dll_449_destroy __dll449_dll_449_destroy
#define dll_449_get_setup_flags __dll449_dll_449_get_setup_flags
#define dll_449_get_state_size __dll449_dll_449_get_state_size
#define dll_449_func_2B8 __dll449_dll_449_func_2B8

#endif //_DLL_449_RECOMP_H
