// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_451_RECOMP_H
#define _DLL_451_RECOMP_H

#define dll_451_ctor __dll451_dll_451_ctor
#define dll_451_dtor __dll451_dll_451_dtor
#define dll_451_func_18 __dll451_dll_451_func_18
#define dll_451_func_98 __dll451_dll_451_func_98
#define dll_451_func_1DC __dll451_dll_451_func_1DC
#define dll_451_func_1E8 __dll451_dll_451_func_1E8
#define dll_451_func_200 __dll451_dll_451_func_200
#define dll_451_func_210 __dll451_dll_451_func_210
#define dll_451_func_220 __dll451_dll_451_func_220
#define dll_451_func_234 __dll451_dll_451_func_234
#define dll_451_func_308 __dll451_dll_451_func_308

#endif //_DLL_451_RECOMP_H
