// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_452_RECOMP_H
#define _DLL_452_RECOMP_H

#define dll_452_ctor __dll452_dll_452_ctor
#define dll_452_dtor __dll452_dll_452_dtor
#define dll_452_func_18 __dll452_dll_452_func_18
#define dll_452_func_210 __dll452_dll_452_func_210
#define dll_452_func_3A8 __dll452_dll_452_func_3A8
#define dll_452_func_3B4 __dll452_dll_452_func_3B4
#define dll_452_func_41C __dll452_dll_452_func_41C
#define dll_452_func_518 __dll452_dll_452_func_518
#define dll_452_func_528 __dll452_dll_452_func_528
#define dll_452_func_53C __dll452_dll_452_func_53C
#define dll_452_func_614 __dll452_dll_452_func_614
#define str_0 __dll452_str_0

#endif //_DLL_452_RECOMP_H
