// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_454_RECOMP_H
#define _DLL_454_RECOMP_H

#define dll_454_ctor __dll454_dll_454_ctor
#define dll_454_dtor __dll454_dll_454_dtor
#define dll_454_create __dll454_dll_454_create
#define dll_454_update __dll454_dll_454_update
#define dll_454_func_AB0 __dll454_dll_454_func_AB0
#define dll_454_func_B54 __dll454_dll_454_func_B54
#define dll_454_draw __dll454_dll_454_draw
#define dll_454_destroy __dll454_dll_454_destroy
#define dll_454_get_model_flags __dll454_dll_454_get_model_flags
#define dll_454_get_state_size __dll454_dll_454_get_state_size
#define dll_454_func_BE8 __dll454_dll_454_func_BE8
#define dll_454_func_CEC __dll454_dll_454_func_CEC
#define dll_454_func_DC4 __dll454_dll_454_func_DC4
#define dll_454_func_104C __dll454_dll_454_func_104C
#define str_0 __dll454_str_0
#define _rodata_54 __dll454__rodata_54
#define _rodata_84 __dll454__rodata_84
#define _rodata_88 __dll454__rodata_88
#define _rodata_8C __dll454__rodata_8C
#define _rodata_90 __dll454__rodata_90
#define _rodata_94 __dll454__rodata_94
#define _rodata_98 __dll454__rodata_98
#define _rodata_9C __dll454__rodata_9C
#define _rodata_A0 __dll454__rodata_A0
#define _rodata_A4 __dll454__rodata_A4
#define _rodata_A8 __dll454__rodata_A8
#define _rodata_AC __dll454__rodata_AC
#define _rodata_B0 __dll454__rodata_B0
#define _rodata_B4 __dll454__rodata_B4
#define _rodata_B8 __dll454__rodata_B8
#define _rodata_BC __dll454__rodata_BC
#define _rodata_C0 __dll454__rodata_C0
#define _rodata_C4 __dll454__rodata_C4

#endif //_DLL_454_RECOMP_H
