// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_456_RECOMP_H
#define _DLL_456_RECOMP_H

#define dll_456_ctor __dll456_dll_456_ctor
#define dll_456_dtor __dll456_dll_456_dtor
#define dll_456_func_18 __dll456_dll_456_func_18
#define dll_456_func_64 __dll456_dll_456_func_64
#define dll_456_func_70 __dll456_dll_456_func_70
#define dll_456_func_7C __dll456_dll_456_func_7C
#define dll_456_func_1B4 __dll456_dll_456_func_1B4
#define dll_456_func_1C4 __dll456_dll_456_func_1C4
#define dll_456_func_1D4 __dll456_dll_456_func_1D4

#endif //_DLL_456_RECOMP_H
