// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_459_RECOMP_H
#define _DLL_459_RECOMP_H

#define dll_459_ctor __dll459_dll_459_ctor
#define dll_459_dtor __dll459_dll_459_dtor
#define dll_459_create __dll459_dll_459_create
#define dll_459_update __dll459_dll_459_update
#define dll_459_func_1BC __dll459_dll_459_func_1BC
#define dll_459_draw __dll459_dll_459_draw
#define dll_459_destroy __dll459_dll_459_destroy
#define dll_459_get_model_flags __dll459_dll_459_get_model_flags
#define dll_459_get_state_size __dll459_dll_459_get_state_size
#define dll_459_func_214 __dll459_dll_459_func_214
#define dll_459_func_3F8 __dll459_dll_459_func_3F8
#define dll_459_func_48C __dll459_dll_459_func_48C
#define _rodata_0 __dll459__rodata_0

#endif //_DLL_459_RECOMP_H
