// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_45_RECOMP_H
#define _DLL_45_RECOMP_H

#define dll_45_ctor __dll45_dll_45_ctor
#define dll_45_dtor __dll45_dll_45_dtor
#define dll_45_func_18 __dll45_dll_45_func_18
#define dll_45_func_20 __dll45_dll_45_func_20
#define dll_45_func_2C __dll45_dll_45_func_2C
#define rodata_3C __dll45_rodata_3C
#define rodata_40 __dll45_rodata_40
#define rodata_44 __dll45_rodata_44
#define rodata_48 __dll45_rodata_48
#define rodata_4C __dll45_rodata_4C
#define rodata_50 __dll45_rodata_50
#define rodata_54 __dll45_rodata_54
#define rodata_58 __dll45_rodata_58
#define rodata_5C __dll45_rodata_5C
#define rodata_60 __dll45_rodata_60
#define rodata_64 __dll45_rodata_64
#define rodata_68 __dll45_rodata_68
#define rodata_6C __dll45_rodata_6C
#define rodata_70 __dll45_rodata_70
#define rodata_74 __dll45_rodata_74
#define rodata_78 __dll45_rodata_78
#define rodata_7C __dll45_rodata_7C
#define rodata_80 __dll45_rodata_80
#define rodata_84 __dll45_rodata_84
#define rodata_88 __dll45_rodata_88
#define rodata_8C __dll45_rodata_8C
#define rodata_90 __dll45_rodata_90
#define rodata_94 __dll45_rodata_94
#define rodata_98 __dll45_rodata_98
#define rodata_9C __dll45_rodata_9C
#define rodata_A0 __dll45_rodata_A0
#define rodata_A4 __dll45_rodata_A4
#define rodata_A8 __dll45_rodata_A8
#define rodata_AC __dll45_rodata_AC
#define rodata_B0 __dll45_rodata_B0
#define rodata_B4 __dll45_rodata_B4
#define rodata_B8 __dll45_rodata_B8
#define rodata_BC __dll45_rodata_BC
#define rodata_C0 __dll45_rodata_C0
#define rodata_C4 __dll45_rodata_C4
#define rodata_C8 __dll45_rodata_C8
#define rodata_CC __dll45_rodata_CC
#define rodata_D0 __dll45_rodata_D0
#define rodata_D4 __dll45_rodata_D4
#define rodata_D8 __dll45_rodata_D8
#define rodata_DC __dll45_rodata_DC
#define bss_0 __dll45_bss_0

#endif //_DLL_45_RECOMP_H
