// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_463_RECOMP_H
#define _DLL_463_RECOMP_H

#define dll_463_ctor __dll463_dll_463_ctor
#define dll_463_dtor __dll463_dll_463_dtor
#define dll_463_func_18 __dll463_dll_463_func_18
#define dll_463_func_6C __dll463_dll_463_func_6C
#define dll_463_func_1E8 __dll463_dll_463_func_1E8
#define dll_463_func_1F4 __dll463_dll_463_func_1F4
#define dll_463_func_20C __dll463_dll_463_func_20C
#define dll_463_func_280 __dll463_dll_463_func_280
#define dll_463_func_290 __dll463_dll_463_func_290
#define _rodata_0 __dll463__rodata_0

#endif //_DLL_463_RECOMP_H
