// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_464_RECOMP_H
#define _DLL_464_RECOMP_H

#define dll_464_ctor __dll464_dll_464_ctor
#define dll_464_dtor __dll464_dll_464_dtor
#define dll_464_func_18 __dll464_dll_464_func_18
#define dll_464_func_84 __dll464_dll_464_func_84
#define dll_464_func_37C __dll464_dll_464_func_37C
#define dll_464_func_388 __dll464_dll_464_func_388
#define dll_464_func_3DC __dll464_dll_464_func_3DC
#define dll_464_func_3EC __dll464_dll_464_func_3EC
#define dll_464_func_3FC __dll464_dll_464_func_3FC

#endif //_DLL_464_RECOMP_H
