// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_467_RECOMP_H
#define _DLL_467_RECOMP_H

#define dll_467_ctor __dll467_dll_467_ctor
#define dll_467_dtor __dll467_dll_467_dtor
#define dll_467_create __dll467_dll_467_create
#define dll_467_update __dll467_dll_467_update
#define dll_467_func_374 __dll467_dll_467_func_374
#define dll_467_draw __dll467_dll_467_draw
#define dll_467_destroy __dll467_dll_467_destroy
#define dll_467_get_setup_flags __dll467_dll_467_get_setup_flags
#define dll_467_get_state_size __dll467_dll_467_get_state_size

#endif //_DLL_467_RECOMP_H
