// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_468_RECOMP_H
#define _DLL_468_RECOMP_H

#define dll_468_ctor __dll468_dll_468_ctor
#define dll_468_dtor __dll468_dll_468_dtor
#define dll_468_setup __dll468_dll_468_setup
#define dll_468_control __dll468_dll_468_control
#define dll_468_update __dll468_dll_468_update
#define dll_468_print __dll468_dll_468_print
#define dll_468_free __dll468_dll_468_free
#define dll_468_get_model_flags __dll468_dll_468_get_model_flags
#define dll_468_get_data_size __dll468_dll_468_get_data_size
#define rodata_0 __dll468_rodata_0
#define data_0 __dll468_data_0
#define data_4 __dll468_data_4
#define data_14 __dll468_data_14

#endif //_DLL_468_RECOMP_H
