// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_468_RECOMP_H
#define _DLL_468_RECOMP_H

#define dll_468_ctor __dll468_dll_468_ctor
#define dll_468_dtor __dll468_dll_468_dtor
#define dll_468_func_18 __dll468_dll_468_func_18
#define dll_468_func_194 __dll468_dll_468_func_194
#define dll_468_func_73C __dll468_dll_468_func_73C
#define dll_468_func_748 __dll468_dll_468_func_748
#define dll_468_func_A24 __dll468_dll_468_func_A24
#define dll_468_func_AD4 __dll468_dll_468_func_AD4
#define dll_468_func_AE4 __dll468_dll_468_func_AE4
#define _rodata_0 __dll468__rodata_0
#define _data_0 __dll468__data_0
#define _data_4 __dll468__data_4
#define _data_14 __dll468__data_14

#endif //_DLL_468_RECOMP_H
