// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_470_RECOMP_H
#define _DLL_470_RECOMP_H

#define dll_470_ctor __dll470_dll_470_ctor
#define dll_470_dtor __dll470_dll_470_dtor
#define dll_470_func_18 __dll470_dll_470_func_18
#define dll_470_func_13C __dll470_dll_470_func_13C
#define dll_470_func_8E8 __dll470_dll_470_func_8E8
#define dll_470_func_8F4 __dll470_dll_470_func_8F4
#define dll_470_func_948 __dll470_dll_470_func_948
#define dll_470_func_990 __dll470_dll_470_func_990
#define dll_470_func_9A0 __dll470_dll_470_func_9A0
#define _rodata_0 __dll470__rodata_0
#define _data_0 __dll470__data_0
#define _data_4 __dll470__data_4

#endif //_DLL_470_RECOMP_H
