// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_476_RECOMP_H
#define _DLL_476_RECOMP_H

#define dll_476_ctor __dll476_dll_476_ctor
#define dll_476_dtor __dll476_dll_476_dtor
#define dll_476_func_18 __dll476_dll_476_func_18
#define dll_476_func_54 __dll476_dll_476_func_54
#define dll_476_func_284 __dll476_dll_476_func_284
#define dll_476_func_290 __dll476_dll_476_func_290
#define dll_476_func_2E4 __dll476_dll_476_func_2E4
#define dll_476_func_340 __dll476_dll_476_func_340
#define dll_476_func_350 __dll476_dll_476_func_350
#define dll_476_func_364 __dll476_dll_476_func_364

#endif //_DLL_476_RECOMP_H
