// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_478_RECOMP_H
#define _DLL_478_RECOMP_H

#define dll_478_ctor __dll478_dll_478_ctor
#define dll_478_dtor __dll478_dll_478_dtor
#define dll_478_func_18 __dll478_dll_478_func_18
#define dll_478_func_94 __dll478_dll_478_func_94
#define dll_478_func_5F8 __dll478_dll_478_func_5F8
#define dll_478_func_604 __dll478_dll_478_func_604
#define dll_478_func_64C __dll478_dll_478_func_64C
#define dll_478_func_68C __dll478_dll_478_func_68C
#define dll_478_func_69C __dll478_dll_478_func_69C
#define dll_478_func_6B0 __dll478_dll_478_func_6B0
#define _rodata_0 __dll478__rodata_0
#define _rodata_4 __dll478__rodata_4
#define _rodata_8 __dll478__rodata_8
#define _rodata_C __dll478__rodata_C
#define _rodata_10 __dll478__rodata_10
#define _rodata_14 __dll478__rodata_14
#define _rodata_18 __dll478__rodata_18
#define _data_0 __dll478__data_0
#define _data_4 __dll478__data_4
#define _data_8 __dll478__data_8
#define _bss_0 __dll478__bss_0

#endif //_DLL_478_RECOMP_H
