// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_482_RECOMP_H
#define _DLL_482_RECOMP_H

#define dll_482_ctor __dll482_dll_482_ctor
#define dll_482_dtor __dll482_dll_482_dtor
#define dll_482_func_18 __dll482_dll_482_func_18
#define dll_482_func_90 __dll482_dll_482_func_90
#define dll_482_func_490 __dll482_dll_482_func_490
#define dll_482_func_49C __dll482_dll_482_func_49C
#define dll_482_func_4B4 __dll482_dll_482_func_4B4
#define dll_482_func_4C4 __dll482_dll_482_func_4C4
#define dll_482_func_4D4 __dll482_dll_482_func_4D4

#endif //_DLL_482_RECOMP_H
