// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_482_RECOMP_H
#define _DLL_482_RECOMP_H

#define dll_482_ctor __dll482_dll_482_ctor
#define dll_482_dtor __dll482_dll_482_dtor
#define dll_482_setup __dll482_dll_482_setup
#define dll_482_control __dll482_dll_482_control
#define dll_482_update __dll482_dll_482_update
#define dll_482_print __dll482_dll_482_print
#define dll_482_free __dll482_dll_482_free
#define dll_482_get_model_flags __dll482_dll_482_get_model_flags
#define dll_482_get_data_size __dll482_dll_482_get_data_size

#endif //_DLL_482_RECOMP_H
