// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_483_RECOMP_H
#define _DLL_483_RECOMP_H

#define dll_483_ctor __dll483_dll_483_ctor
#define dll_483_dtor __dll483_dll_483_dtor
#define dll_483_obj_Setup __dll483_dll_483_obj_Setup
#define dll_483_obj_Control __dll483_dll_483_obj_Control
#define dll_483_obj_Update __dll483_dll_483_obj_Update
#define dll_483_obj_Print __dll483_dll_483_obj_Print
#define dll_483_obj_Free __dll483_dll_483_obj_Free
#define dll_483_obj_GetModelFlags __dll483_dll_483_obj_GetModelFlags
#define dll_483_obj_GetDataSize __dll483_dll_483_obj_GetDataSize
#define str_0 __dll483_str_0
#define rodata_18 __dll483_rodata_18
#define data_0 __dll483_data_0
#define data_4 __dll483_data_4

#endif //_DLL_483_RECOMP_H
