// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_483_RECOMP_H
#define _DLL_483_RECOMP_H

#define dll_483_ctor __dll483_dll_483_ctor
#define dll_483_dtor __dll483_dll_483_dtor
#define dll_483_setup __dll483_dll_483_setup
#define dll_483_control __dll483_dll_483_control
#define dll_483_update __dll483_dll_483_update
#define dll_483_print __dll483_dll_483_print
#define dll_483_free __dll483_dll_483_free
#define dll_483_get_model_flags __dll483_dll_483_get_model_flags
#define dll_483_get_data_size __dll483_dll_483_get_data_size
#define str_0 __dll483_str_0
#define _rodata_18 __dll483__rodata_18
#define _data_0 __dll483__data_0
#define _data_4 __dll483__data_4

#endif //_DLL_483_RECOMP_H
