// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_484_RECOMP_H
#define _DLL_484_RECOMP_H

#define dll_484_ctor __dll484_dll_484_ctor
#define dll_484_dtor __dll484_dll_484_dtor
#define dll_484_func_18 __dll484_dll_484_func_18
#define dll_484_func_C4 __dll484_dll_484_func_C4
#define dll_484_func_178 __dll484_dll_484_func_178
#define dll_484_func_184 __dll484_dll_484_func_184
#define dll_484_func_19C __dll484_dll_484_func_19C
#define dll_484_func_1E4 __dll484_dll_484_func_1E4
#define dll_484_func_1F4 __dll484_dll_484_func_1F4
#define _rodata_0 __dll484__rodata_0
#define _data_0 __dll484__data_0

#endif //_DLL_484_RECOMP_H
