// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_484_RECOMP_H
#define _DLL_484_RECOMP_H

#define dll_484_ctor __dll484_dll_484_ctor
#define dll_484_dtor __dll484_dll_484_dtor
#define dll_484_setup __dll484_dll_484_setup
#define dll_484_control __dll484_dll_484_control
#define dll_484_update __dll484_dll_484_update
#define dll_484_print __dll484_dll_484_print
#define dll_484_free __dll484_dll_484_free
#define dll_484_get_model_flags __dll484_dll_484_get_model_flags
#define dll_484_get_data_size __dll484_dll_484_get_data_size
#define _rodata_0 __dll484__rodata_0
#define _data_0 __dll484__data_0

#endif //_DLL_484_RECOMP_H
