// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_485_RECOMP_H
#define _DLL_485_RECOMP_H

#define dll_485_ctor __dll485_dll_485_ctor
#define dll_485_dtor __dll485_dll_485_dtor
#define dll_485_obj_Setup __dll485_dll_485_obj_Setup
#define dll_485_obj_Control __dll485_dll_485_obj_Control
#define dll_485_obj_Update __dll485_dll_485_obj_Update
#define dll_485_obj_Print __dll485_dll_485_obj_Print
#define dll_485_obj_Free __dll485_dll_485_obj_Free
#define dll_485_obj_GetModelFlags __dll485_dll_485_obj_GetModelFlags
#define dll_485_obj_GetDataSize __dll485_dll_485_obj_GetDataSize
#define rodata_0 __dll485_rodata_0
#define rodata_4 __dll485_rodata_4
#define rodata_8 __dll485_rodata_8
#define rodata_C __dll485_rodata_C
#define data_0 __dll485_data_0
#define data_4 __dll485_data_4

#endif //_DLL_485_RECOMP_H
