// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_487_RECOMP_H
#define _DLL_487_RECOMP_H

#define dll_487_ctor __dll487_dll_487_ctor
#define dll_487_dtor __dll487_dll_487_dtor
#define dll_487_func_18 __dll487_dll_487_func_18
#define dll_487_func_50 __dll487_dll_487_func_50
#define dll_487_func_308 __dll487_dll_487_func_308
#define dll_487_func_314 __dll487_dll_487_func_314
#define dll_487_func_368 __dll487_dll_487_func_368
#define dll_487_func_378 __dll487_dll_487_func_378
#define dll_487_func_388 __dll487_dll_487_func_388
#define _oob_rodata_0 __dll487__oob_rodata_0

#endif //_DLL_487_RECOMP_H
