// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_489_RECOMP_H
#define _DLL_489_RECOMP_H

#define dll_489_ctor __dll489_dll_489_ctor
#define dll_489_dtor __dll489_dll_489_dtor
#define dll_489_create __dll489_dll_489_create
#define dll_489_update __dll489_dll_489_update
#define dll_489_func_294 __dll489_dll_489_func_294
#define dll_489_draw __dll489_dll_489_draw
#define dll_489_destroy __dll489_dll_489_destroy
#define dll_489_get_setup_flags __dll489_dll_489_get_setup_flags
#define dll_489_get_state_size __dll489_dll_489_get_state_size
#define _oob_rodata_0 __dll489__oob_rodata_0

#endif //_DLL_489_RECOMP_H
