// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_490_RECOMP_H
#define _DLL_490_RECOMP_H

#define dll_490_ctor __dll490_dll_490_ctor
#define dll_490_dtor __dll490_dll_490_dtor
#define dll_490_func_18 __dll490_dll_490_func_18
#define dll_490_func_1C0 __dll490_dll_490_func_1C0
#define dll_490_func_66C __dll490_dll_490_func_66C
#define dll_490_func_678 __dll490_dll_490_func_678
#define dll_490_func_6CC __dll490_dll_490_func_6CC
#define dll_490_func_6DC __dll490_dll_490_func_6DC
#define dll_490_func_6EC __dll490_dll_490_func_6EC
#define dll_490_func_700 __dll490_dll_490_func_700
#define dll_490_func_8A4 __dll490_dll_490_func_8A4
#define _rodata_0 __dll490__rodata_0
#define _rodata_4 __dll490__rodata_4
#define _data_0 __dll490__data_0
#define _data_4 __dll490__data_4

#endif //_DLL_490_RECOMP_H
