// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_492_RECOMP_H
#define _DLL_492_RECOMP_H

#define dll_492_ctor __dll492_dll_492_ctor
#define dll_492_dtor __dll492_dll_492_dtor
#define dll_492_obj_Setup __dll492_dll_492_obj_Setup
#define dll_492_obj_Control __dll492_dll_492_obj_Control
#define dll_492_obj_Update __dll492_dll_492_obj_Update
#define dll_492_obj_Print __dll492_dll_492_obj_Print
#define dll_492_obj_Free __dll492_dll_492_obj_Free
#define dll_492_obj_GetModelFlags __dll492_dll_492_obj_GetModelFlags
#define dll_492_obj_GetDataSize __dll492_dll_492_obj_GetDataSize
#define str_0 __dll492_str_0
#define rodata_14 __dll492_rodata_14
#define data_0 __dll492_data_0
#define data_4 __dll492_data_4
#define data_14 __dll492_data_14

#endif //_DLL_492_RECOMP_H
