// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_493_RECOMP_H
#define _DLL_493_RECOMP_H

#define dll_493_ctor __dll493_dll_493_ctor
#define dll_493_dtor __dll493_dll_493_dtor
#define dll_493_func_18 __dll493_dll_493_func_18
#define dll_493_func_84 __dll493_dll_493_func_84
#define dll_493_func_1E8 __dll493_dll_493_func_1E8
#define dll_493_func_1F4 __dll493_dll_493_func_1F4
#define dll_493_func_248 __dll493_dll_493_func_248
#define dll_493_func_258 __dll493_dll_493_func_258
#define dll_493_func_268 __dll493_dll_493_func_268
#define _data_0 __dll493__data_0

#endif //_DLL_493_RECOMP_H
