// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_500_RECOMP_H
#define _DLL_500_RECOMP_H

#define dll_500_ctor __dll500_dll_500_ctor
#define dll_500_dtor __dll500_dll_500_dtor
#define dll_500_obj_Setup __dll500_dll_500_obj_Setup
#define dll_500_obj_Control __dll500_dll_500_obj_Control
#define dll_500_obj_Update __dll500_dll_500_obj_Update
#define dll_500_obj_Print __dll500_dll_500_obj_Print
#define dll_500_obj_Free __dll500_dll_500_obj_Free
#define dll_500_obj_GetModelFlags __dll500_dll_500_obj_GetModelFlags
#define dll_500_obj_GetDataSize __dll500_dll_500_obj_GetDataSize
#define dll_500_func_2C0 __dll500_dll_500_func_2C0
#define rodata_0 __dll500_rodata_0
#define rodata_4 __dll500_rodata_4
#define rodata_8 __dll500_rodata_8
#define rodata_C __dll500_rodata_C

#endif //_DLL_500_RECOMP_H
