// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_502_RECOMP_H
#define _DLL_502_RECOMP_H

#define dll_502_ctor __dll502_dll_502_ctor
#define dll_502_dtor __dll502_dll_502_dtor
#define dll_502_setup __dll502_dll_502_setup
#define dll_502_control __dll502_dll_502_control
#define dll_502_update __dll502_dll_502_update
#define dll_502_print __dll502_dll_502_print
#define dll_502_free __dll502_dll_502_free
#define dll_502_get_model_flags __dll502_dll_502_get_model_flags
#define dll_502_get_data_size __dll502_dll_502_get_data_size
#define dll_502_func_910 __dll502_dll_502_func_910
#define dll_502_func_C70 __dll502_dll_502_func_C70
#define dll_502_func_D74 __dll502_dll_502_func_D74
#define str_0 __dll502_str_0
#define _rodata_38 __dll502__rodata_38
#define _rodata_50 __dll502__rodata_50
#define _rodata_7C __dll502__rodata_7C
#define _rodata_80 __dll502__rodata_80
#define _data_0 __dll502__data_0
#define _data_14 __dll502__data_14

#endif //_DLL_502_RECOMP_H
