// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_502_RECOMP_H
#define _DLL_502_RECOMP_H

#define dll_502_ctor __dll502_dll_502_ctor
#define dll_502_dtor __dll502_dll_502_dtor
#define dll_502_func_18 __dll502_dll_502_func_18
#define dll_502_func_3A8 __dll502_dll_502_func_3A8
#define dll_502_func_848 __dll502_dll_502_func_848
#define dll_502_func_854 __dll502_dll_502_func_854
#define dll_502_func_86C __dll502_dll_502_func_86C
#define dll_502_func_8E4 __dll502_dll_502_func_8E4
#define dll_502_func_8FC __dll502_dll_502_func_8FC
#define dll_502_func_910 __dll502_dll_502_func_910
#define dll_502_func_C70 __dll502_dll_502_func_C70
#define dll_502_func_D74 __dll502_dll_502_func_D74
#define str_0 __dll502_str_0
#define _rodata_38 __dll502__rodata_38
#define _rodata_50 __dll502__rodata_50
#define _rodata_7C __dll502__rodata_7C
#define _rodata_80 __dll502__rodata_80
#define _data_0 __dll502__data_0
#define _data_14 __dll502__data_14

#endif //_DLL_502_RECOMP_H
