// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_505_RECOMP_H
#define _DLL_505_RECOMP_H

#define dll_505_ctor __dll505_dll_505_ctor
#define dll_505_dtor __dll505_dll_505_dtor
#define dll_505_func_18 __dll505_dll_505_func_18
#define dll_505_func_18C __dll505_dll_505_func_18C
#define dll_505_func_750 __dll505_dll_505_func_750
#define dll_505_func_A00 __dll505_dll_505_func_A00
#define dll_505_func_B88 __dll505_dll_505_func_B88
#define dll_505_func_B94 __dll505_dll_505_func_B94
#define dll_505_func_BAC __dll505_dll_505_func_BAC
#define dll_505_func_BF4 __dll505_dll_505_func_BF4
#define dll_505_func_C04 __dll505_dll_505_func_C04
#define _rodata_0 __dll505__rodata_0
#define _rodata_4 __dll505__rodata_4
#define _rodata_8 __dll505__rodata_8
#define _rodata_C __dll505__rodata_C
#define _rodata_10 __dll505__rodata_10
#define _rodata_14 __dll505__rodata_14
#define _rodata_18 __dll505__rodata_18
#define _rodata_1C __dll505__rodata_1C
#define _data_0 __dll505__data_0
#define _data_C __dll505__data_C

#endif //_DLL_505_RECOMP_H
