// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_506_RECOMP_H
#define _DLL_506_RECOMP_H

#define dll_506_ctor __dll506_dll_506_ctor
#define dll_506_dtor __dll506_dll_506_dtor
#define dll_506_setup __dll506_dll_506_setup
#define dll_506_control __dll506_dll_506_control
#define dll_506_update __dll506_dll_506_update
#define dll_506_print __dll506_dll_506_print
#define dll_506_free __dll506_dll_506_free
#define dll_506_get_model_flags __dll506_dll_506_get_model_flags
#define dll_506_get_data_size __dll506_dll_506_get_data_size
#define _oob_rodata_0 __dll506__oob_rodata_0

#endif //_DLL_506_RECOMP_H
