// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_509_RECOMP_H
#define _DLL_509_RECOMP_H

#define dll_509_ctor __dll509_dll_509_ctor
#define dll_509_dtor __dll509_dll_509_dtor
#define dll_509_func_18 __dll509_dll_509_func_18
#define dll_509_func_110 __dll509_dll_509_func_110
#define dll_509_func_2C8 __dll509_dll_509_func_2C8
#define dll_509_func_2D4 __dll509_dll_509_func_2D4
#define dll_509_func_328 __dll509_dll_509_func_328
#define dll_509_func_338 __dll509_dll_509_func_338
#define dll_509_func_348 __dll509_dll_509_func_348
#define str_0 __dll509_str_0
#define _rodata_1C __dll509__rodata_1C
#define _rodata_20 __dll509__rodata_20
#define _rodata_24 __dll509__rodata_24
#define _rodata_28 __dll509__rodata_28

#endif //_DLL_509_RECOMP_H
