// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_510_RECOMP_H
#define _DLL_510_RECOMP_H

#define dll_510_ctor __dll510_dll_510_ctor
#define dll_510_dtor __dll510_dll_510_dtor
#define dll_510_create __dll510_dll_510_create
#define dll_510_update __dll510_dll_510_update
#define dll_510_func_5E0 __dll510_dll_510_func_5E0
#define dll_510_draw __dll510_dll_510_draw
#define dll_510_destroy __dll510_dll_510_destroy
#define dll_510_get_model_flags __dll510_dll_510_get_model_flags
#define dll_510_get_state_size __dll510_dll_510_get_state_size
#define _rodata_14 __dll510__rodata_14
#define _rodata_18 __dll510__rodata_18
#define _rodata_1C __dll510__rodata_1C
#define _rodata_20 __dll510__rodata_20

#endif //_DLL_510_RECOMP_H
