// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_511_RECOMP_H
#define _DLL_511_RECOMP_H

#define dll_511_ctor __dll511_dll_511_ctor
#define dll_511_dtor __dll511_dll_511_dtor
#define dll_511_create __dll511_dll_511_create
#define dll_511_update __dll511_dll_511_update
#define dll_511_func_C8 __dll511_dll_511_func_C8
#define dll_511_draw __dll511_dll_511_draw
#define dll_511_destroy __dll511_dll_511_destroy
#define dll_511_get_setup_flags __dll511_dll_511_get_setup_flags
#define dll_511_get_state_size __dll511_dll_511_get_state_size

#endif //_DLL_511_RECOMP_H
