// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_513_RECOMP_H
#define _DLL_513_RECOMP_H

#define dll_513_ctor __dll513_dll_513_ctor
#define dll_513_dtor __dll513_dll_513_dtor
#define dll_513_func_18 __dll513_dll_513_func_18
#define dll_513_func_74 __dll513_dll_513_func_74
#define dll_513_func_80 __dll513_dll_513_func_80
#define dll_513_func_8C __dll513_dll_513_func_8C
#define dll_513_func_18C __dll513_dll_513_func_18C
#define dll_513_func_19C __dll513_dll_513_func_19C
#define dll_513_func_1AC __dll513_dll_513_func_1AC
#define _rodata_0 __dll513__rodata_0

#endif //_DLL_513_RECOMP_H
