// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_517_RECOMP_H
#define _DLL_517_RECOMP_H

#define dll_517_func_0 __dll517_dll_517_func_0
#define dll_517_ctor __dll517_dll_517_ctor
#define dll_517_dtor __dll517_dll_517_dtor
#define dll_517_create __dll517_dll_517_create
#define dll_517_update __dll517_dll_517_update
#define dll_517_func_1FC __dll517_dll_517_func_1FC
#define dll_517_draw __dll517_dll_517_draw
#define dll_517_destroy __dll517_dll_517_destroy
#define dll_517_get_model_flags __dll517_dll_517_get_model_flags
#define dll_517_get_state_size __dll517_dll_517_get_state_size
#define dll_517_func_2FC __dll517_dll_517_func_2FC
#define dll_517_func_334 __dll517_dll_517_func_334
#define dll_517_func_4AC __dll517_dll_517_func_4AC
#define dll_517_func_628 __dll517_dll_517_func_628
#define dll_517_func_7C4 __dll517_dll_517_func_7C4
#define _rodata_0 __dll517__rodata_0
#define _rodata_4 __dll517__rodata_4
#define _rodata_8 __dll517__rodata_8
#define _data_0 __dll517__data_0
#define _data_8 __dll517__data_8
#define _data_18 __dll517__data_18
#define _bss_0 __dll517__bss_0
#define _bss_8 __dll517__bss_8

#endif //_DLL_517_RECOMP_H
