// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_520_RECOMP_H
#define _DLL_520_RECOMP_H

#define dll_520_ctor __dll520_dll_520_ctor
#define dll_520_dtor __dll520_dll_520_dtor
#define dll_520_setup __dll520_dll_520_setup
#define dll_520_control __dll520_dll_520_control
#define dll_520_update __dll520_dll_520_update
#define dll_520_print __dll520_dll_520_print
#define dll_520_free __dll520_dll_520_free
#define dll_520_get_model_flags __dll520_dll_520_get_model_flags
#define dll_520_get_data_size __dll520_dll_520_get_data_size
#define dll_520_func_914 __dll520_dll_520_func_914
#define dll_520_func_BAC __dll520_dll_520_func_BAC
#define dll_520_func_EA4 __dll520_dll_520_func_EA4
#define dll_520_func_FB4 __dll520_dll_520_func_FB4
#define _rodata_0 __dll520__rodata_0
#define _rodata_4 __dll520__rodata_4
#define _rodata_8 __dll520__rodata_8
#define _rodata_C __dll520__rodata_C
#define _rodata_10 __dll520__rodata_10

#endif //_DLL_520_RECOMP_H
