// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_521_RECOMP_H
#define _DLL_521_RECOMP_H

#define dll_521_ctor __dll521_dll_521_ctor
#define dll_521_dtor __dll521_dll_521_dtor
#define dll_521_setup __dll521_dll_521_setup
#define dll_521_control __dll521_dll_521_control
#define dll_521_update __dll521_dll_521_update
#define dll_521_print __dll521_dll_521_print
#define dll_521_free __dll521_dll_521_free
#define dll_521_get_model_flags __dll521_dll_521_get_model_flags
#define dll_521_get_data_size __dll521_dll_521_get_data_size
#define dll_521_func_4C8 __dll521_dll_521_func_4C8

#endif //_DLL_521_RECOMP_H
