// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_524_RECOMP_H
#define _DLL_524_RECOMP_H

#define dll_524_ctor __dll524_dll_524_ctor
#define dll_524_dtor __dll524_dll_524_dtor
#define dll_524_create __dll524_dll_524_create
#define dll_524_update __dll524_dll_524_update
#define dll_524_func_3F8 __dll524_dll_524_func_3F8
#define dll_524_draw __dll524_dll_524_draw
#define dll_524_destroy __dll524_dll_524_destroy
#define dll_524_get_model_flags __dll524_dll_524_get_model_flags
#define dll_524_get_state_size __dll524_dll_524_get_state_size
#define _bss_0 __dll524__bss_0
#define _bss_C __dll524__bss_C
#define _bss_10 __dll524__bss_10
#define _bss_14 __dll524__bss_14

#endif //_DLL_524_RECOMP_H
