// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_526_RECOMP_H
#define _DLL_526_RECOMP_H

#define dll_526_ctor __dll526_dll_526_ctor
#define dll_526_dtor __dll526_dll_526_dtor
#define dll_526_create __dll526_dll_526_create
#define dll_526_update __dll526_dll_526_update
#define dll_526_func_240 __dll526_dll_526_func_240
#define dll_526_draw __dll526_dll_526_draw
#define dll_526_destroy __dll526_dll_526_destroy
#define dll_526_get_model_flags __dll526_dll_526_get_model_flags
#define dll_526_get_state_size __dll526_dll_526_get_state_size

#endif //_DLL_526_RECOMP_H
