// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_526_RECOMP_H
#define _DLL_526_RECOMP_H

#define dll_526_ctor __dll526_dll_526_ctor
#define dll_526_dtor __dll526_dll_526_dtor
#define dll_526_func_18 __dll526_dll_526_func_18
#define dll_526_func_D4 __dll526_dll_526_func_D4
#define dll_526_func_240 __dll526_dll_526_func_240
#define dll_526_func_24C __dll526_dll_526_func_24C
#define dll_526_func_2A0 __dll526_dll_526_func_2A0
#define dll_526_func_328 __dll526_dll_526_func_328
#define dll_526_func_338 __dll526_dll_526_func_338

#endif //_DLL_526_RECOMP_H
