// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_528_RECOMP_H
#define _DLL_528_RECOMP_H

#define dll_528_ctor __dll528_dll_528_ctor
#define dll_528_dtor __dll528_dll_528_dtor
#define dll_528_func_18 __dll528_dll_528_func_18
#define dll_528_func_B0 __dll528_dll_528_func_B0
#define dll_528_func_38C __dll528_dll_528_func_38C
#define dll_528_func_398 __dll528_dll_528_func_398
#define dll_528_func_3E0 __dll528_dll_528_func_3E0
#define dll_528_func_448 __dll528_dll_528_func_448
#define dll_528_func_458 __dll528_dll_528_func_458
#define dll_528_func_46C __dll528_dll_528_func_46C
#define dll_528_func_F44 __dll528_dll_528_func_F44
#define str_0 __dll528_str_0
#define _rodata_2C __dll528__rodata_2C
#define _rodata_30 __dll528__rodata_30
#define _rodata_34 __dll528__rodata_34
#define _rodata_38 __dll528__rodata_38
#define _rodata_3C __dll528__rodata_3C
#define _rodata_40 __dll528__rodata_40
#define _rodata_44 __dll528__rodata_44
#define _data_0 __dll528__data_0
#define _data_8 __dll528__data_8
#define _bss_0 __dll528__bss_0

#endif //_DLL_528_RECOMP_H
