// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_52_RECOMP_H
#define _DLL_52_RECOMP_H

#define dll_52_ctor __dll52_dll_52_ctor
#define dll_52_dtor __dll52_dll_52_dtor
#define dll_52_func_18 __dll52_dll_52_func_18
#define dll_52_func_20 __dll52_dll_52_func_20
#define dll_52_func_194 __dll52_dll_52_func_194
#define _rodata_0 __dll52__rodata_0
#define _rodata_4 __dll52__rodata_4
#define _rodata_8 __dll52__rodata_8
#define _rodata_C __dll52__rodata_C
#define _rodata_10 __dll52__rodata_10
#define _rodata_14 __dll52__rodata_14
#define _rodata_18 __dll52__rodata_18
#define _rodata_1C __dll52__rodata_1C
#define _rodata_20 __dll52__rodata_20
#define _rodata_24 __dll52__rodata_24
#define _rodata_28 __dll52__rodata_28
#define _rodata_2C __dll52__rodata_2C
#define _data_0 __dll52__data_0
#define _data_4 __dll52__data_4
#define _data_8 __dll52__data_8
#define _data_C __dll52__data_C
#define _data_10 __dll52__data_10
#define _data_14 __dll52__data_14
#define _data_18 __dll52__data_18
#define _data_1C __dll52__data_1C

#endif //_DLL_52_RECOMP_H
