// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_52_RECOMP_H
#define _DLL_52_RECOMP_H

#define dll_52_ctor __dll52_dll_52_ctor
#define dll_52_dtor __dll52_dll_52_dtor
#define dll_52_func_18 __dll52_dll_52_func_18
#define dll_52_func_20 __dll52_dll_52_func_20
#define dll_52_func_194 __dll52_dll_52_func_194
#define rodata_0 __dll52_rodata_0
#define rodata_4 __dll52_rodata_4
#define rodata_8 __dll52_rodata_8
#define rodata_C __dll52_rodata_C
#define rodata_10 __dll52_rodata_10
#define rodata_14 __dll52_rodata_14
#define rodata_18 __dll52_rodata_18
#define rodata_1C __dll52_rodata_1C
#define rodata_20 __dll52_rodata_20
#define rodata_24 __dll52_rodata_24
#define rodata_28 __dll52_rodata_28
#define rodata_2C __dll52_rodata_2C
#define data_0 __dll52_data_0
#define data_4 __dll52_data_4
#define data_8 __dll52_data_8
#define data_C __dll52_data_C
#define data_10 __dll52_data_10
#define data_14 __dll52_data_14
#define data_18 __dll52_data_18
#define data_1C __dll52_data_1C

#endif //_DLL_52_RECOMP_H
