// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_532_RECOMP_H
#define _DLL_532_RECOMP_H

#define dll_532_ctor __dll532_dll_532_ctor
#define dll_532_dtor __dll532_dll_532_dtor
#define dll_532_create __dll532_dll_532_create
#define dll_532_update __dll532_dll_532_update
#define dll_532_func_514 __dll532_dll_532_func_514
#define dll_532_draw __dll532_dll_532_draw
#define dll_532_destroy __dll532_dll_532_destroy
#define dll_532_get_setup_flags __dll532_dll_532_get_setup_flags
#define dll_532_get_state_size __dll532_dll_532_get_state_size
#define _data_0 __dll532__data_0
#define _data_1884 __dll532__data_1884

#endif //_DLL_532_RECOMP_H
