// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_533_RECOMP_H
#define _DLL_533_RECOMP_H

#define dll_533_ctor __dll533_dll_533_ctor
#define dll_533_dtor __dll533_dll_533_dtor
#define dll_533_func_18 __dll533_dll_533_func_18
#define dll_533_func_50 __dll533_dll_533_func_50
#define dll_533_func_1B4 __dll533_dll_533_func_1B4
#define dll_533_func_1C0 __dll533_dll_533_func_1C0
#define dll_533_func_214 __dll533_dll_533_func_214
#define dll_533_func_224 __dll533_dll_533_func_224
#define dll_533_func_234 __dll533_dll_533_func_234

#endif //_DLL_533_RECOMP_H
