// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_535_RECOMP_H
#define _DLL_535_RECOMP_H

#define dll_535_ctor __dll535_dll_535_ctor
#define dll_535_dtor __dll535_dll_535_dtor
#define dll_535_setup __dll535_dll_535_setup
#define dll_535_control __dll535_dll_535_control
#define dll_535_update __dll535_dll_535_update
#define dll_535_print __dll535_dll_535_print
#define dll_535_free __dll535_dll_535_free
#define dll_535_get_model_flags __dll535_dll_535_get_model_flags
#define dll_535_get_data_size __dll535_dll_535_get_data_size
#define dll_535_func_278 __dll535_dll_535_func_278
#define _oob_rodata_0 __dll535__oob_rodata_0

#endif //_DLL_535_RECOMP_H
