// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_536_RECOMP_H
#define _DLL_536_RECOMP_H

#define dll_536_ctor __dll536_dll_536_ctor
#define dll_536_dtor __dll536_dll_536_dtor
#define dll_536_create __dll536_dll_536_create
#define dll_536_update __dll536_dll_536_update
#define dll_536_func_634 __dll536_dll_536_func_634
#define dll_536_draw __dll536_dll_536_draw
#define dll_536_destroy __dll536_dll_536_destroy
#define dll_536_get_model_flags __dll536_dll_536_get_model_flags
#define dll_536_get_state_size __dll536_dll_536_get_state_size
#define _rodata_0 __dll536__rodata_0
#define _rodata_4 __dll536__rodata_4
#define _rodata_8 __dll536__rodata_8
#define _data_0 __dll536__data_0

#endif //_DLL_536_RECOMP_H
