// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_536_RECOMP_H
#define _DLL_536_RECOMP_H

#define dll_536_ctor __dll536_dll_536_ctor
#define dll_536_dtor __dll536_dll_536_dtor
#define dll_536_setup __dll536_dll_536_setup
#define dll_536_control __dll536_dll_536_control
#define dll_536_update __dll536_dll_536_update
#define dll_536_print __dll536_dll_536_print
#define dll_536_free __dll536_dll_536_free
#define dll_536_get_model_flags __dll536_dll_536_get_model_flags
#define dll_536_get_data_size __dll536_dll_536_get_data_size
#define rodata_0 __dll536_rodata_0
#define rodata_4 __dll536_rodata_4
#define rodata_8 __dll536_rodata_8
#define data_0 __dll536_data_0

#endif //_DLL_536_RECOMP_H
