// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_543_RECOMP_H
#define _DLL_543_RECOMP_H

#define dll_543_ctor __dll543_dll_543_ctor
#define dll_543_dtor __dll543_dll_543_dtor
#define dll_543_func_18 __dll543_dll_543_func_18
#define dll_543_func_2CC __dll543_dll_543_func_2CC
#define dll_543_func_448 __dll543_dll_543_func_448
#define dll_543_func_454 __dll543_dll_543_func_454
#define dll_543_func_4A8 __dll543_dll_543_func_4A8
#define dll_543_func_4B8 __dll543_dll_543_func_4B8
#define dll_543_func_4C8 __dll543_dll_543_func_4C8
#define dll_543_func_4DC __dll543_dll_543_func_4DC
#define dll_543_func_648 __dll543_dll_543_func_648
#define dll_543_func_7A8 __dll543_dll_543_func_7A8
#define _rodata_0 __dll543__rodata_0
#define _rodata_4 __dll543__rodata_4
#define _rodata_8 __dll543__rodata_8

#endif //_DLL_543_RECOMP_H
