// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_546_RECOMP_H
#define _DLL_546_RECOMP_H

#define dll_546_ctor __dll546_dll_546_ctor
#define dll_546_dtor __dll546_dll_546_dtor
#define dll_546_create __dll546_dll_546_create
#define dll_546_update __dll546_dll_546_update
#define dll_546_func_A4 __dll546_dll_546_func_A4
#define dll_546_draw __dll546_dll_546_draw
#define dll_546_destroy __dll546_dll_546_destroy
#define dll_546_get_model_flags __dll546_dll_546_get_model_flags
#define dll_546_get_state_size __dll546_dll_546_get_state_size
#define str_0 __dll546_str_0

#endif //_DLL_546_RECOMP_H
