// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_548_RECOMP_H
#define _DLL_548_RECOMP_H

#define dll_548_ctor __dll548_dll_548_ctor
#define dll_548_dtor __dll548_dll_548_dtor
#define dll_548_create __dll548_dll_548_create
#define dll_548_update __dll548_dll_548_update
#define dll_548_func_1AC __dll548_dll_548_func_1AC
#define dll_548_draw __dll548_dll_548_draw
#define dll_548_destroy __dll548_dll_548_destroy
#define dll_548_get_model_flags __dll548_dll_548_get_model_flags
#define dll_548_get_state_size __dll548_dll_548_get_state_size
#define dll_548_func_41C __dll548_dll_548_func_41C
#define dll_548_func_6E8 __dll548_dll_548_func_6E8
#define dll_548_func_F18 __dll548_dll_548_func_F18
#define dll_548_func_1110 __dll548_dll_548_func_1110
#define dll_548_func_13AC __dll548_dll_548_func_13AC
#define dll_548_func_1460 __dll548_dll_548_func_1460
#define str_0 __dll548_str_0
#define _rodata_BC __dll548__rodata_BC
#define _rodata_C0 __dll548__rodata_C0
#define _rodata_C4 __dll548__rodata_C4
#define _rodata_108 __dll548__rodata_108
#define _rodata_10C __dll548__rodata_10C
#define _rodata_110 __dll548__rodata_110
#define _rodata_114 __dll548__rodata_114
#define _data_0 __dll548__data_0
#define _data_8 __dll548__data_8
#define _data_1C __dll548__data_1C
#define _data_24 __dll548__data_24
#define _data_34 __dll548__data_34
#define _data_3C __dll548__data_3C
#define _data_54 __dll548__data_54
#define _data_68 __dll548__data_68
#define _data_74 __dll548__data_74
#define _data_80 __dll548__data_80
#define _data_88 __dll548__data_88
#define _data_D0 __dll548__data_D0
#define _data_E4 __dll548__data_E4

#endif //_DLL_548_RECOMP_H
