// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_550_RECOMP_H
#define _DLL_550_RECOMP_H

#define dll_550_ctor __dll550_dll_550_ctor
#define dll_550_dtor __dll550_dll_550_dtor
#define dll_550_func_18 __dll550_dll_550_func_18
#define dll_550_func_114 __dll550_dll_550_func_114
#define dll_550_func_3F0 __dll550_dll_550_func_3F0
#define dll_550_func_3FC __dll550_dll_550_func_3FC
#define dll_550_func_460 __dll550_dll_550_func_460
#define dll_550_func_470 __dll550_dll_550_func_470
#define dll_550_func_480 __dll550_dll_550_func_480
#define _rodata_0 __dll550__rodata_0

#endif //_DLL_550_RECOMP_H
