// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_552_RECOMP_H
#define _DLL_552_RECOMP_H

#define dll_552_ctor __dll552_dll_552_ctor
#define dll_552_dtor __dll552_dll_552_dtor
#define dll_552_setup __dll552_dll_552_setup
#define dll_552_control __dll552_dll_552_control
#define dll_552_update __dll552_dll_552_update
#define dll_552_print __dll552_dll_552_print
#define dll_552_free __dll552_dll_552_free
#define dll_552_get_model_flags __dll552_dll_552_get_model_flags
#define dll_552_get_data_size __dll552_dll_552_get_data_size
#define dll_552_func_258 __dll552_dll_552_func_258
#define str_0 __dll552_str_0
#define _rodata_C __dll552__rodata_C
#define _rodata_10 __dll552__rodata_10
#define _rodata_14 __dll552__rodata_14
#define _rodata_18 __dll552__rodata_18
#define _rodata_1C __dll552__rodata_1C
#define _data_0 __dll552__data_0

#endif //_DLL_552_RECOMP_H
