// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_556_RECOMP_H
#define _DLL_556_RECOMP_H

#define dll_556_ctor __dll556_dll_556_ctor
#define dll_556_dtor __dll556_dll_556_dtor
#define dll_556_setup __dll556_dll_556_setup
#define dll_556_control __dll556_dll_556_control
#define dll_556_update __dll556_dll_556_update
#define dll_556_print __dll556_dll_556_print
#define dll_556_free __dll556_dll_556_free
#define dll_556_get_model_flags __dll556_dll_556_get_model_flags
#define dll_556_get_data_size __dll556_dll_556_get_data_size
#define dll_556_func_844 __dll556_dll_556_func_844
#define rodata_0 __dll556_rodata_0
#define rodata_4 __dll556_rodata_4
#define rodata_8 __dll556_rodata_8
#define rodata_C __dll556_rodata_C
#define rodata_10 __dll556_rodata_10
#define rodata_14 __dll556_rodata_14

#endif //_DLL_556_RECOMP_H
