// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_556_RECOMP_H
#define _DLL_556_RECOMP_H

#define dll_556_ctor __dll556_dll_556_ctor
#define dll_556_dtor __dll556_dll_556_dtor
#define dll_556_obj_Setup __dll556_dll_556_obj_Setup
#define dll_556_obj_Control __dll556_dll_556_obj_Control
#define dll_556_obj_Update __dll556_dll_556_obj_Update
#define dll_556_obj_Print __dll556_dll_556_obj_Print
#define dll_556_obj_Free __dll556_dll_556_obj_Free
#define dll_556_obj_GetModelFlags __dll556_dll_556_obj_GetModelFlags
#define dll_556_obj_GetDataSize __dll556_dll_556_obj_GetDataSize
#define dll_556_func_844 __dll556_dll_556_func_844
#define rodata_0 __dll556_rodata_0
#define rodata_4 __dll556_rodata_4
#define rodata_8 __dll556_rodata_8
#define rodata_C __dll556_rodata_C
#define rodata_10 __dll556_rodata_10
#define rodata_14 __dll556_rodata_14

#endif //_DLL_556_RECOMP_H
