// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_559_RECOMP_H
#define _DLL_559_RECOMP_H

#define dll_559_ctor __dll559_dll_559_ctor
#define dll_559_dtor __dll559_dll_559_dtor
#define dll_559_setup __dll559_dll_559_setup
#define dll_559_control __dll559_dll_559_control
#define dll_559_update __dll559_dll_559_update
#define dll_559_print __dll559_dll_559_print
#define dll_559_free __dll559_dll_559_free
#define dll_559_get_model_flags __dll559_dll_559_get_model_flags
#define dll_559_get_data_size __dll559_dll_559_get_data_size
#define _rodata_0 __dll559__rodata_0
#define _rodata_4 __dll559__rodata_4
#define _rodata_8 __dll559__rodata_8
#define _rodata_C __dll559__rodata_C
#define _rodata_10 __dll559__rodata_10
#define _rodata_14 __dll559__rodata_14

#endif //_DLL_559_RECOMP_H
