// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_55_RECOMP_H
#define _DLL_55_RECOMP_H

#define dll_55_ctor __dll55_dll_55_ctor
#define dll_55_dtor __dll55_dll_55_dtor
#define dll_55_func_18 __dll55_dll_55_func_18
#define dll_55_func_304 __dll55_dll_55_func_304
#define dll_55_func_580 __dll55_dll_55_func_580
#define str_0 __dll55_str_0
#define _rodata_28 __dll55__rodata_28
#define _rodata_2C __dll55__rodata_2C

#endif //_DLL_55_RECOMP_H
