// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_562_RECOMP_H
#define _DLL_562_RECOMP_H

#define dll_562_ctor __dll562_dll_562_ctor
#define dll_562_dtor __dll562_dll_562_dtor
#define dll_562_func_18 __dll562_dll_562_func_18
#define dll_562_func_BC __dll562_dll_562_func_BC
#define dll_562_func_538 __dll562_dll_562_func_538
#define dll_562_func_544 __dll562_dll_562_func_544
#define dll_562_func_598 __dll562_dll_562_func_598
#define dll_562_func_5A8 __dll562_dll_562_func_5A8
#define dll_562_func_5B8 __dll562_dll_562_func_5B8
#define _rodata_0 __dll562__rodata_0
#define _rodata_4 __dll562__rodata_4
#define _rodata_8 __dll562__rodata_8

#endif //_DLL_562_RECOMP_H
