// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_564_RECOMP_H
#define _DLL_564_RECOMP_H

#define dll_564_ctor __dll564_dll_564_ctor
#define dll_564_dtor __dll564_dll_564_dtor
#define dll_564_func_18 __dll564_dll_564_func_18
#define dll_564_func_CC __dll564_dll_564_func_CC
#define dll_564_func_8E0 __dll564_dll_564_func_8E0
#define dll_564_func_8EC __dll564_dll_564_func_8EC
#define dll_564_func_940 __dll564_dll_564_func_940
#define dll_564_func_950 __dll564_dll_564_func_950
#define dll_564_func_960 __dll564_dll_564_func_960
#define _rodata_0 __dll564__rodata_0
#define _rodata_4 __dll564__rodata_4
#define _rodata_8 __dll564__rodata_8
#define _rodata_C __dll564__rodata_C

#endif //_DLL_564_RECOMP_H
