// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_564_RECOMP_H
#define _DLL_564_RECOMP_H

#define dll_564_ctor __dll564_dll_564_ctor
#define dll_564_dtor __dll564_dll_564_dtor
#define dll_564_create __dll564_dll_564_create
#define dll_564_update __dll564_dll_564_update
#define dll_564_func_8E0 __dll564_dll_564_func_8E0
#define dll_564_draw __dll564_dll_564_draw
#define dll_564_destroy __dll564_dll_564_destroy
#define dll_564_get_setup_flags __dll564_dll_564_get_setup_flags
#define dll_564_get_state_size __dll564_dll_564_get_state_size
#define _rodata_0 __dll564__rodata_0
#define _rodata_4 __dll564__rodata_4
#define _rodata_8 __dll564__rodata_8
#define _rodata_C __dll564__rodata_C

#endif //_DLL_564_RECOMP_H
