// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_566_RECOMP_H
#define _DLL_566_RECOMP_H

#define dll_566_ctor __dll566_dll_566_ctor
#define dll_566_dtor __dll566_dll_566_dtor
#define dll_566_func_18 __dll566_dll_566_func_18
#define dll_566_func_B4 __dll566_dll_566_func_B4
#define dll_566_func_C0 __dll566_dll_566_func_C0
#define dll_566_func_CC __dll566_dll_566_func_CC
#define dll_566_func_160 __dll566_dll_566_func_160
#define dll_566_func_170 __dll566_dll_566_func_170
#define dll_566_func_180 __dll566_dll_566_func_180
#define dll_566_func_194 __dll566_dll_566_func_194

#endif //_DLL_566_RECOMP_H
