// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_567_RECOMP_H
#define _DLL_567_RECOMP_H

#define dll_567_func_0 __dll567_dll_567_func_0
#define dll_567_ctor __dll567_dll_567_ctor
#define dll_567_dtor __dll567_dll_567_dtor
#define dll_567_setup __dll567_dll_567_setup
#define dll_567_control __dll567_dll_567_control
#define dll_567_update __dll567_dll_567_update
#define dll_567_print __dll567_dll_567_print
#define dll_567_free __dll567_dll_567_free
#define dll_567_get_model_flags __dll567_dll_567_get_model_flags
#define dll_567_get_data_size __dll567_dll_567_get_data_size
#define dll_567_func_6CC __dll567_dll_567_func_6CC
#define dll_567_func_6DC __dll567_dll_567_func_6DC
#define dll_567_func_6EC __dll567_dll_567_func_6EC
#define dll_567_func_AE4 __dll567_dll_567_func_AE4
#define dll_567_func_EC8 __dll567_dll_567_func_EC8
#define dll_567_func_11FC __dll567_dll_567_func_11FC
#define dll_567_func_126C __dll567_dll_567_func_126C
#define dll_567_func_14C8 __dll567_dll_567_func_14C8
#define dll_567_func_1524 __dll567_dll_567_func_1524
#define rodata_0 __dll567_rodata_0
#define rodata_4 __dll567_rodata_4
#define data_0 __dll567_data_0
#define bss_0 __dll567_bss_0
#define bss_8 __dll567_bss_8
#define bss_10 __dll567_bss_10
#define bss_14 __dll567_bss_14
#define bss_18 __dll567_bss_18
#define bss_1C __dll567_bss_1C
#define bss_20 __dll567_bss_20
#define bss_28 __dll567_bss_28
#define bss_34 __dll567_bss_34
#define bss_38 __dll567_bss_38
#define bss_3C __dll567_bss_3C

#endif //_DLL_567_RECOMP_H
