// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_570_RECOMP_H
#define _DLL_570_RECOMP_H

#define dll_570_ctor __dll570_dll_570_ctor
#define dll_570_dtor __dll570_dll_570_dtor
#define dll_570_create __dll570_dll_570_create
#define dll_570_update __dll570_dll_570_update
#define dll_570_func_1A8 __dll570_dll_570_func_1A8
#define dll_570_draw __dll570_dll_570_draw
#define dll_570_destroy __dll570_dll_570_destroy
#define dll_570_get_setup_flags __dll570_dll_570_get_setup_flags
#define dll_570_get_state_size __dll570_dll_570_get_state_size
#define dll_570_func_2AC __dll570_dll_570_func_2AC
#define dll_570_func_360 __dll570_dll_570_func_360
#define dll_570_func_53C __dll570_dll_570_func_53C
#define _rodata_0 __dll570__rodata_0
#define _rodata_4 __dll570__rodata_4
#define _rodata_8 __dll570__rodata_8
#define _rodata_C __dll570__rodata_C
#define _bss_0 __dll570__bss_0

#endif //_DLL_570_RECOMP_H
