// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_574_RECOMP_H
#define _DLL_574_RECOMP_H

#define dll_574_ctor __dll574_dll_574_ctor
#define dll_574_dtor __dll574_dll_574_dtor
#define dll_574_create __dll574_dll_574_create
#define dll_574_update __dll574_dll_574_update
#define dll_574_func_464 __dll574_dll_574_func_464
#define dll_574_draw __dll574_dll_574_draw
#define dll_574_destroy __dll574_dll_574_destroy
#define dll_574_get_setup_flags __dll574_dll_574_get_setup_flags
#define dll_574_get_state_size __dll574_dll_574_get_state_size
#define _rodata_0 __dll574__rodata_0
#define _data_0 __dll574__data_0

#endif //_DLL_574_RECOMP_H
