// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_574_RECOMP_H
#define _DLL_574_RECOMP_H

#define dll_574_ctor __dll574_dll_574_ctor
#define dll_574_dtor __dll574_dll_574_dtor
#define dll_574_func_18 __dll574_dll_574_func_18
#define dll_574_func_4C __dll574_dll_574_func_4C
#define dll_574_func_464 __dll574_dll_574_func_464
#define dll_574_func_4AC __dll574_dll_574_func_4AC
#define dll_574_func_6B8 __dll574_dll_574_func_6B8
#define dll_574_func_714 __dll574_dll_574_func_714
#define dll_574_func_724 __dll574_dll_574_func_724
#define _rodata_0 __dll574__rodata_0
#define _data_0 __dll574__data_0

#endif //_DLL_574_RECOMP_H
