// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_578_RECOMP_H
#define _DLL_578_RECOMP_H

#define dll_578_ctor __dll578_dll_578_ctor
#define dll_578_dtor __dll578_dll_578_dtor
#define dll_578_func_18 __dll578_dll_578_func_18
#define dll_578_func_CC __dll578_dll_578_func_CC
#define dll_578_func_2CC __dll578_dll_578_func_2CC
#define dll_578_func_2D8 __dll578_dll_578_func_2D8
#define dll_578_func_374 __dll578_dll_578_func_374
#define dll_578_func_3E4 __dll578_dll_578_func_3E4
#define dll_578_func_3F4 __dll578_dll_578_func_3F4
#define dll_578_func_408 __dll578_dll_578_func_408

#endif //_DLL_578_RECOMP_H
