// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_57_RECOMP_H
#define _DLL_57_RECOMP_H

#define dll_57_ctor __dll57_dll_57_ctor
#define dll_57_dtor __dll57_dll_57_dtor
#define dll_57_func_18 __dll57_dll_57_func_18
#define dll_57_func_74 __dll57_dll_57_func_74
#define dll_57_func_190 __dll57_dll_57_func_190
#define dll_57_func_1E4 __dll57_dll_57_func_1E4
#define dll_57_func_9A0 __dll57_dll_57_func_9A0
#define dll_57_func_BB0 __dll57_dll_57_func_BB0
#define rodata_0 __dll57_rodata_0
#define rodata_4 __dll57_rodata_4
#define rodata_8 __dll57_rodata_8
#define rodata_C __dll57_rodata_C
#define rodata_10 __dll57_rodata_10
#define data_0 __dll57_data_0
#define data_18 __dll57_data_18
#define bss_0 __dll57_bss_0
#define bss_18 __dll57_bss_18
#define bss_30 __dll57_bss_30

#endif //_DLL_57_RECOMP_H
