// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_580_RECOMP_H
#define _DLL_580_RECOMP_H

#define dll_580_ctor __dll580_dll_580_ctor
#define dll_580_dtor __dll580_dll_580_dtor
#define dll_580_func_18 __dll580_dll_580_func_18
#define dll_580_func_40 __dll580_dll_580_func_40
#define dll_580_func_4C0 __dll580_dll_580_func_4C0
#define dll_580_func_644 __dll580_dll_580_func_644
#define dll_580_func_65C __dll580_dll_580_func_65C
#define dll_580_func_704 __dll580_dll_580_func_704
#define dll_580_func_714 __dll580_dll_580_func_714
#define _oob_rodata_0 __dll580__oob_rodata_0

#endif //_DLL_580_RECOMP_H
