// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_581_RECOMP_H
#define _DLL_581_RECOMP_H

#define dll_581_ctor __dll581_dll_581_ctor
#define dll_581_dtor __dll581_dll_581_dtor
#define dll_581_setup __dll581_dll_581_setup
#define dll_581_control __dll581_dll_581_control
#define dll_581_update __dll581_dll_581_update
#define dll_581_print __dll581_dll_581_print
#define dll_581_free __dll581_dll_581_free
#define dll_581_get_model_flags __dll581_dll_581_get_model_flags
#define dll_581_get_data_size __dll581_dll_581_get_data_size
#define dll_581_func_87C __dll581_dll_581_func_87C
#define _rodata_0 __dll581__rodata_0

#endif //_DLL_581_RECOMP_H
