// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_582_RECOMP_H
#define _DLL_582_RECOMP_H

#define dll_582_ctor __dll582_dll_582_ctor
#define dll_582_dtor __dll582_dll_582_dtor
#define dll_582_create __dll582_dll_582_create
#define dll_582_update __dll582_dll_582_update
#define dll_582_func_68 __dll582_dll_582_func_68
#define dll_582_draw __dll582_dll_582_draw
#define dll_582_destroy __dll582_dll_582_destroy
#define dll_582_get_model_flags __dll582_dll_582_get_model_flags
#define dll_582_get_state_size __dll582_dll_582_get_state_size
#define dll_582_func_FC __dll582_dll_582_func_FC

#endif //_DLL_582_RECOMP_H
