// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_586_RECOMP_H
#define _DLL_586_RECOMP_H

#define dll_586_ctor __dll586_dll_586_ctor
#define dll_586_dtor __dll586_dll_586_dtor
#define dll_586_func_18 __dll586_dll_586_func_18
#define dll_586_func_B8 __dll586_dll_586_func_B8
#define dll_586_func_124 __dll586_dll_586_func_124
#define dll_586_func_130 __dll586_dll_586_func_130
#define dll_586_func_5E4 __dll586_dll_586_func_5E4
#define dll_586_func_638 __dll586_dll_586_func_638
#define dll_586_func_6C8 __dll586_dll_586_func_6C8
#define dll_586_func_6D8 __dll586_dll_586_func_6D8
#define _data_0 __dll586__data_0

#endif //_DLL_586_RECOMP_H
