// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_586_RECOMP_H
#define _DLL_586_RECOMP_H

#define dll_586_ctor __dll586_dll_586_ctor
#define dll_586_dtor __dll586_dll_586_dtor
#define dll_586_setup __dll586_dll_586_setup
#define dll_586_control __dll586_dll_586_control
#define dll_586_update __dll586_dll_586_update
#define dll_586_func_130 __dll586_dll_586_func_130
#define dll_586_print __dll586_dll_586_print
#define dll_586_free __dll586_dll_586_free
#define dll_586_get_model_flags __dll586_dll_586_get_model_flags
#define dll_586_get_data_size __dll586_dll_586_get_data_size
#define _data_0 __dll586__data_0

#endif //_DLL_586_RECOMP_H
