// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_587_RECOMP_H
#define _DLL_587_RECOMP_H

#define dll_587_ctor __dll587_dll_587_ctor
#define dll_587_dtor __dll587_dll_587_dtor
#define dll_587_obj_Setup __dll587_dll_587_obj_Setup
#define dll_587_obj_Control __dll587_dll_587_obj_Control
#define dll_587_obj_Update __dll587_dll_587_obj_Update
#define dll_587_obj_Print __dll587_dll_587_obj_Print
#define dll_587_obj_Free __dll587_dll_587_obj_Free
#define dll_587_obj_GetModelFlags __dll587_dll_587_obj_GetModelFlags
#define dll_587_obj_GetDataSize __dll587_dll_587_obj_GetDataSize
#define dll_587_func_548 __dll587_dll_587_func_548
#define dll_587_func_75C __dll587_dll_587_func_75C
#define rodata_0 __dll587_rodata_0
#define rodata_C0 __dll587_rodata_C0
#define rodata_F0 __dll587_rodata_F0
#define rodata_134 __dll587_rodata_134
#define rodata_138 __dll587_rodata_138
#define rodata_13C __dll587_rodata_13C
#define rodata_140 __dll587_rodata_140
#define bss_0 __dll587_bss_0
#define bss_4 __dll587_bss_4

#endif //_DLL_587_RECOMP_H
