// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_587_RECOMP_H
#define _DLL_587_RECOMP_H

#define dll_587_ctor __dll587_dll_587_ctor
#define dll_587_dtor __dll587_dll_587_dtor
#define dll_587_create __dll587_dll_587_create
#define dll_587_update __dll587_dll_587_update
#define dll_587_func_340 __dll587_dll_587_func_340
#define dll_587_draw __dll587_dll_587_draw
#define dll_587_destroy __dll587_dll_587_destroy
#define dll_587_get_setup_flags __dll587_dll_587_get_setup_flags
#define dll_587_get_state_size __dll587_dll_587_get_state_size
#define dll_587_func_548 __dll587_dll_587_func_548
#define dll_587_func_75C __dll587_dll_587_func_75C
#define _rodata_0 __dll587__rodata_0
#define _rodata_C0 __dll587__rodata_C0
#define _rodata_F0 __dll587__rodata_F0
#define _rodata_134 __dll587__rodata_134
#define _rodata_138 __dll587__rodata_138
#define _rodata_13C __dll587__rodata_13C
#define _rodata_140 __dll587__rodata_140
#define _bss_0 __dll587__bss_0
#define _bss_4 __dll587__bss_4

#endif //_DLL_587_RECOMP_H
