// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_588_RECOMP_H
#define _DLL_588_RECOMP_H

#define dll_588_ctor __dll588_dll_588_ctor
#define dll_588_dtor __dll588_dll_588_dtor
#define dll_588_setup __dll588_dll_588_setup
#define dll_588_control __dll588_dll_588_control
#define dll_588_update __dll588_dll_588_update
#define dll_588_print __dll588_dll_588_print
#define dll_588_free __dll588_dll_588_free
#define dll_588_get_model_flags __dll588_dll_588_get_model_flags
#define dll_588_get_data_size __dll588_dll_588_get_data_size

#endif //_DLL_588_RECOMP_H
