// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_594_RECOMP_H
#define _DLL_594_RECOMP_H

#define dll_594_ctor __dll594_dll_594_ctor
#define dll_594_dtor __dll594_dll_594_dtor
#define dll_594_func_18 __dll594_dll_594_func_18
#define dll_594_func_174 __dll594_dll_594_func_174
#define dll_594_func_C80 __dll594_dll_594_func_C80
#define dll_594_func_C8C __dll594_dll_594_func_C8C
#define dll_594_func_F60 __dll594_dll_594_func_F60
#define dll_594_func_1024 __dll594_dll_594_func_1024
#define dll_594_func_1034 __dll594_dll_594_func_1034
#define _rodata_0 __dll594__rodata_0
#define _rodata_4 __dll594__rodata_4
#define _rodata_8 __dll594__rodata_8
#define _data_0 __dll594__data_0
#define _data_8 __dll594__data_8

#endif //_DLL_594_RECOMP_H
