// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_594_RECOMP_H
#define _DLL_594_RECOMP_H

#define dll_594_ctor __dll594_dll_594_ctor
#define dll_594_dtor __dll594_dll_594_dtor
#define dll_594_setup __dll594_dll_594_setup
#define dll_594_control __dll594_dll_594_control
#define dll_594_update __dll594_dll_594_update
#define dll_594_print __dll594_dll_594_print
#define dll_594_free __dll594_dll_594_free
#define dll_594_get_model_flags __dll594_dll_594_get_model_flags
#define dll_594_get_data_size __dll594_dll_594_get_data_size
#define rodata_0 __dll594_rodata_0
#define rodata_4 __dll594_rodata_4
#define rodata_8 __dll594_rodata_8
#define data_0 __dll594_data_0
#define data_8 __dll594_data_8

#endif //_DLL_594_RECOMP_H
