// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_594_RECOMP_H
#define _DLL_594_RECOMP_H

#define dll_594_ctor __dll594_dll_594_ctor
#define dll_594_dtor __dll594_dll_594_dtor
#define dll_594_obj_Setup __dll594_dll_594_obj_Setup
#define dll_594_obj_Control __dll594_dll_594_obj_Control
#define dll_594_obj_Update __dll594_dll_594_obj_Update
#define dll_594_obj_Print __dll594_dll_594_obj_Print
#define dll_594_obj_Free __dll594_dll_594_obj_Free
#define dll_594_obj_GetModelFlags __dll594_dll_594_obj_GetModelFlags
#define dll_594_obj_GetDataSize __dll594_dll_594_obj_GetDataSize
#define rodata_0 __dll594_rodata_0
#define rodata_4 __dll594_rodata_4
#define rodata_8 __dll594_rodata_8
#define data_0 __dll594_data_0
#define data_8 __dll594_data_8

#endif //_DLL_594_RECOMP_H
