// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_595_RECOMP_H
#define _DLL_595_RECOMP_H

#define dll_595_ctor __dll595_dll_595_ctor
#define dll_595_dtor __dll595_dll_595_dtor
#define dll_595_setup __dll595_dll_595_setup
#define dll_595_control __dll595_dll_595_control
#define dll_595_update __dll595_dll_595_update
#define dll_595_print __dll595_dll_595_print
#define dll_595_free __dll595_dll_595_free
#define dll_595_get_model_flags __dll595_dll_595_get_model_flags
#define dll_595_get_data_size __dll595_dll_595_get_data_size

#endif //_DLL_595_RECOMP_H
