// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_597_RECOMP_H
#define _DLL_597_RECOMP_H

#define dll_597_ctor __dll597_dll_597_ctor
#define dll_597_dtor __dll597_dll_597_dtor
#define dll_597_setup __dll597_dll_597_setup
#define dll_597_control __dll597_dll_597_control
#define dll_597_update __dll597_dll_597_update
#define dll_597_print __dll597_dll_597_print
#define dll_597_free __dll597_dll_597_free
#define dll_597_get_model_flags __dll597_dll_597_get_model_flags
#define dll_597_get_data_size __dll597_dll_597_get_data_size
#define dll_597_func_428 __dll597_dll_597_func_428
#define _rodata_0 __dll597__rodata_0

#endif //_DLL_597_RECOMP_H
