// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_599_RECOMP_H
#define _DLL_599_RECOMP_H

#define dll_599_ctor __dll599_dll_599_ctor
#define dll_599_dtor __dll599_dll_599_dtor
#define dll_599_func_18 __dll599_dll_599_func_18
#define dll_599_func_98 __dll599_dll_599_func_98
#define dll_599_func_384 __dll599_dll_599_func_384
#define dll_599_func_390 __dll599_dll_599_func_390
#define dll_599_func_3E4 __dll599_dll_599_func_3E4
#define dll_599_func_468 __dll599_dll_599_func_468
#define dll_599_func_478 __dll599_dll_599_func_478
#define dll_599_func_48C __dll599_dll_599_func_48C
#define _data_0 __dll599__data_0

#endif //_DLL_599_RECOMP_H
