// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_603_RECOMP_H
#define _DLL_603_RECOMP_H

#define dll_603_ctor __dll603_dll_603_ctor
#define dll_603_dtor __dll603_dll_603_dtor
#define dll_603_func_18 __dll603_dll_603_func_18
#define dll_603_func_EC __dll603_dll_603_func_EC
#define dll_603_func_2A4 __dll603_dll_603_func_2A4
#define dll_603_func_2B0 __dll603_dll_603_func_2B0
#define dll_603_func_2C8 __dll603_dll_603_func_2C8
#define dll_603_func_338 __dll603_dll_603_func_338
#define dll_603_func_348 __dll603_dll_603_func_348
#define _data_0 __dll603__data_0

#endif //_DLL_603_RECOMP_H
