// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_603_RECOMP_H
#define _DLL_603_RECOMP_H

#define dll_603_ctor __dll603_dll_603_ctor
#define dll_603_dtor __dll603_dll_603_dtor
#define dll_603_create __dll603_dll_603_create
#define dll_603_update __dll603_dll_603_update
#define dll_603_func_2A4 __dll603_dll_603_func_2A4
#define dll_603_draw __dll603_dll_603_draw
#define dll_603_destroy __dll603_dll_603_destroy
#define dll_603_get_model_flags __dll603_dll_603_get_model_flags
#define dll_603_get_state_size __dll603_dll_603_get_state_size
#define _data_0 __dll603__data_0

#endif //_DLL_603_RECOMP_H
