// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_605_RECOMP_H
#define _DLL_605_RECOMP_H

#define dll_605_ctor __dll605_dll_605_ctor
#define dll_605_dtor __dll605_dll_605_dtor
#define dll_605_create __dll605_dll_605_create
#define dll_605_update __dll605_dll_605_update
#define dll_605_func_388 __dll605_dll_605_func_388
#define dll_605_draw __dll605_dll_605_draw
#define dll_605_destroy __dll605_dll_605_destroy
#define dll_605_get_model_flags __dll605_dll_605_get_model_flags
#define dll_605_get_state_size __dll605_dll_605_get_state_size
#define _rodata_0 __dll605__rodata_0
#define _rodata_4 __dll605__rodata_4
#define _data_0 __dll605__data_0

#endif //_DLL_605_RECOMP_H
