// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_612_RECOMP_H
#define _DLL_612_RECOMP_H

#define dll_612_ctor __dll612_dll_612_ctor
#define dll_612_dtor __dll612_dll_612_dtor
#define dll_612_func_18 __dll612_dll_612_func_18
#define dll_612_func_47C __dll612_dll_612_func_47C
#define dll_612_func_1604 __dll612_dll_612_func_1604
#define dll_612_func_1610 __dll612_dll_612_func_1610
#define dll_612_func_16C4 __dll612_dll_612_func_16C4
#define dll_612_func_1794 __dll612_dll_612_func_1794
#define dll_612_func_17A4 __dll612_dll_612_func_17A4
#define dll_612_func_17B8 __dll612_dll_612_func_17B8
#define _rodata_0 __dll612__rodata_0
#define _rodata_4 __dll612__rodata_4
#define _rodata_8 __dll612__rodata_8
#define _rodata_C __dll612__rodata_C
#define _rodata_10 __dll612__rodata_10
#define _rodata_14 __dll612__rodata_14
#define _rodata_18 __dll612__rodata_18
#define _rodata_1C __dll612__rodata_1C
#define _rodata_20 __dll612__rodata_20
#define _rodata_24 __dll612__rodata_24
#define _rodata_28 __dll612__rodata_28
#define _rodata_2C __dll612__rodata_2C
#define _rodata_30 __dll612__rodata_30
#define _rodata_34 __dll612__rodata_34
#define _rodata_38 __dll612__rodata_38
#define _rodata_3C __dll612__rodata_3C
#define _rodata_40 __dll612__rodata_40
#define _rodata_44 __dll612__rodata_44
#define _rodata_48 __dll612__rodata_48
#define _rodata_4C __dll612__rodata_4C
#define _rodata_50 __dll612__rodata_50
#define _rodata_54 __dll612__rodata_54
#define _rodata_58 __dll612__rodata_58
#define _rodata_5C __dll612__rodata_5C
#define _data_0 __dll612__data_0
#define _data_4 __dll612__data_4
#define _data_10 __dll612__data_10
#define _data_1C __dll612__data_1C
#define _data_20 __dll612__data_20
#define _bss_0 __dll612__bss_0
#define _bss_2 __dll612__bss_2
#define _bss_4 __dll612__bss_4
#define _bss_6 __dll612__bss_6
#define _bss_8 __dll612__bss_8

#endif //_DLL_612_RECOMP_H
