// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_613_RECOMP_H
#define _DLL_613_RECOMP_H

#define dll_613_ctor __dll613_dll_613_ctor
#define dll_613_dtor __dll613_dll_613_dtor
#define dll_613_func_18 __dll613_dll_613_func_18
#define dll_613_func_60 __dll613_dll_613_func_60
#define dll_613_func_6C __dll613_dll_613_func_6C
#define dll_613_func_78 __dll613_dll_613_func_78
#define dll_613_func_114 __dll613_dll_613_func_114
#define dll_613_func_124 __dll613_dll_613_func_124
#define dll_613_func_134 __dll613_dll_613_func_134
#define _rodata_0 __dll613__rodata_0

#endif //_DLL_613_RECOMP_H
