// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_615_RECOMP_H
#define _DLL_615_RECOMP_H

#define dll_615_ctor __dll615_dll_615_ctor
#define dll_615_dtor __dll615_dll_615_dtor
#define dll_615_setup __dll615_dll_615_setup
#define dll_615_control __dll615_dll_615_control
#define dll_615_update __dll615_dll_615_update
#define dll_615_print __dll615_dll_615_print
#define dll_615_free __dll615_dll_615_free
#define dll_615_get_model_flags __dll615_dll_615_get_model_flags
#define dll_615_get_data_size __dll615_dll_615_get_data_size
#define dll_615_func_19FC __dll615_dll_615_func_19FC
#define dll_615_func_1AC8 __dll615_dll_615_func_1AC8
#define dll_615_func_1AE8 __dll615_dll_615_func_1AE8
#define str_0 __dll615_str_0
#define _rodata_48 __dll615__rodata_48
#define _rodata_4C __dll615__rodata_4C
#define _rodata_50 __dll615__rodata_50
#define _rodata_54 __dll615__rodata_54
#define _rodata_58 __dll615__rodata_58
#define _rodata_5C __dll615__rodata_5C
#define _rodata_60 __dll615__rodata_60
#define _rodata_64 __dll615__rodata_64
#define _rodata_68 __dll615__rodata_68
#define _rodata_6C __dll615__rodata_6C
#define _rodata_70 __dll615__rodata_70
#define _rodata_74 __dll615__rodata_74
#define _rodata_78 __dll615__rodata_78
#define _rodata_7C __dll615__rodata_7C
#define _rodata_80 __dll615__rodata_80
#define _data_0 __dll615__data_0
#define _data_10 __dll615__data_10
#define _data_14 __dll615__data_14
#define _data_18 __dll615__data_18
#define _data_24 __dll615__data_24

#endif //_DLL_615_RECOMP_H
