// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_616_RECOMP_H
#define _DLL_616_RECOMP_H

#define dll_616_ctor __dll616_dll_616_ctor
#define dll_616_dtor __dll616_dll_616_dtor
#define dll_616_setup __dll616_dll_616_setup
#define dll_616_control __dll616_dll_616_control
#define dll_616_update __dll616_dll_616_update
#define dll_616_print __dll616_dll_616_print
#define dll_616_free __dll616_dll_616_free
#define dll_616_get_model_flags __dll616_dll_616_get_model_flags
#define dll_616_get_data_size __dll616_dll_616_get_data_size
#define rodata_0 __dll616_rodata_0
#define rodata_4 __dll616_rodata_4
#define rodata_8 __dll616_rodata_8
#define rodata_C __dll616_rodata_C
#define rodata_10 __dll616_rodata_10
#define rodata_14 __dll616_rodata_14
#define rodata_18 __dll616_rodata_18
#define rodata_1C __dll616_rodata_1C

#endif //_DLL_616_RECOMP_H
