// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_616_RECOMP_H
#define _DLL_616_RECOMP_H

#define dll_616_ctor __dll616_dll_616_ctor
#define dll_616_dtor __dll616_dll_616_dtor
#define dll_616_obj_Setup __dll616_dll_616_obj_Setup
#define dll_616_obj_Control __dll616_dll_616_obj_Control
#define dll_616_obj_Update __dll616_dll_616_obj_Update
#define dll_616_obj_Print __dll616_dll_616_obj_Print
#define dll_616_obj_Free __dll616_dll_616_obj_Free
#define dll_616_obj_GetModelFlags __dll616_dll_616_obj_GetModelFlags
#define dll_616_obj_GetDataSize __dll616_dll_616_obj_GetDataSize
#define rodata_0 __dll616_rodata_0
#define rodata_4 __dll616_rodata_4
#define rodata_8 __dll616_rodata_8
#define rodata_C __dll616_rodata_C
#define rodata_10 __dll616_rodata_10
#define rodata_14 __dll616_rodata_14
#define rodata_18 __dll616_rodata_18
#define rodata_1C __dll616_rodata_1C

#endif //_DLL_616_RECOMP_H
