// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_618_RECOMP_H
#define _DLL_618_RECOMP_H

#define dll_618_ctor __dll618_dll_618_ctor
#define dll_618_dtor __dll618_dll_618_dtor
#define dll_618_setup __dll618_dll_618_setup
#define dll_618_control __dll618_dll_618_control
#define dll_618_update __dll618_dll_618_update
#define dll_618_print __dll618_dll_618_print
#define dll_618_free __dll618_dll_618_free
#define dll_618_get_model_flags __dll618_dll_618_get_model_flags
#define dll_618_get_data_size __dll618_dll_618_get_data_size
#define dll_618_func_1F0 __dll618_dll_618_func_1F0
#define _rodata_0 __dll618__rodata_0
#define _rodata_C0 __dll618__rodata_C0
#define _rodata_F0 __dll618__rodata_F0
#define _rodata_120 __dll618__rodata_120
#define _rodata_124 __dll618__rodata_124

#endif //_DLL_618_RECOMP_H
