// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_621_RECOMP_H
#define _DLL_621_RECOMP_H

#define dll_621_ctor __dll621_dll_621_ctor
#define dll_621_dtor __dll621_dll_621_dtor
#define dll_621_obj_Setup __dll621_dll_621_obj_Setup
#define dll_621_obj_Control __dll621_dll_621_obj_Control
#define dll_621_obj_Update __dll621_dll_621_obj_Update
#define dll_621_obj_Print __dll621_dll_621_obj_Print
#define dll_621_obj_Free __dll621_dll_621_obj_Free
#define dll_621_obj_GetModelFlags __dll621_dll_621_obj_GetModelFlags
#define dll_621_obj_GetDataSize __dll621_dll_621_obj_GetDataSize
#define rodata_0 __dll621_rodata_0
#define data_0 __dll621_data_0

#endif //_DLL_621_RECOMP_H
