// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_622_RECOMP_H
#define _DLL_622_RECOMP_H

#define dll_622_ctor __dll622_dll_622_ctor
#define dll_622_dtor __dll622_dll_622_dtor
#define dll_622_obj_Setup __dll622_dll_622_obj_Setup
#define dll_622_obj_Control __dll622_dll_622_obj_Control
#define dll_622_obj_Update __dll622_dll_622_obj_Update
#define dll_622_obj_Print __dll622_dll_622_obj_Print
#define dll_622_obj_Free __dll622_dll_622_obj_Free
#define dll_622_obj_GetModelFlags __dll622_dll_622_obj_GetModelFlags
#define dll_622_obj_GetDataSize __dll622_dll_622_obj_GetDataSize
#define rodata_0 __dll622_rodata_0
#define rodata_4 __dll622_rodata_4

#endif //_DLL_622_RECOMP_H
