// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_623_RECOMP_H
#define _DLL_623_RECOMP_H

#define dll_623_ctor __dll623_dll_623_ctor
#define dll_623_dtor __dll623_dll_623_dtor
#define dll_623_obj_Setup __dll623_dll_623_obj_Setup
#define dll_623_obj_Control __dll623_dll_623_obj_Control
#define dll_623_obj_Update __dll623_dll_623_obj_Update
#define dll_623_obj_Print __dll623_dll_623_obj_Print
#define dll_623_obj_Free __dll623_dll_623_obj_Free
#define dll_623_obj_GetModelFlags __dll623_dll_623_obj_GetModelFlags
#define dll_623_obj_GetDataSize __dll623_dll_623_obj_GetDataSize
#define rodata_0 __dll623_rodata_0
#define rodata_4 __dll623_rodata_4

#endif //_DLL_623_RECOMP_H
