// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_624_RECOMP_H
#define _DLL_624_RECOMP_H

#define dll_624_ctor __dll624_dll_624_ctor
#define dll_624_dtor __dll624_dll_624_dtor
#define dll_624_obj_Setup __dll624_dll_624_obj_Setup
#define dll_624_obj_Control __dll624_dll_624_obj_Control
#define dll_624_obj_Update __dll624_dll_624_obj_Update
#define dll_624_obj_Print __dll624_dll_624_obj_Print
#define dll_624_obj_Free __dll624_dll_624_obj_Free
#define dll_624_obj_GetModelFlags __dll624_dll_624_obj_GetModelFlags
#define dll_624_obj_GetDataSize __dll624_dll_624_obj_GetDataSize
#define rodata_0 __dll624_rodata_0
#define rodata_4 __dll624_rodata_4
#define rodata_8 __dll624_rodata_8
#define rodata_C __dll624_rodata_C

#endif //_DLL_624_RECOMP_H
