// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_625_RECOMP_H
#define _DLL_625_RECOMP_H

#define dll_625_ctor __dll625_dll_625_ctor
#define dll_625_dtor __dll625_dll_625_dtor
#define dll_625_setup __dll625_dll_625_setup
#define dll_625_control __dll625_dll_625_control
#define dll_625_update __dll625_dll_625_update
#define dll_625_print __dll625_dll_625_print
#define dll_625_free __dll625_dll_625_free
#define dll_625_get_model_flags __dll625_dll_625_get_model_flags
#define dll_625_get_data_size __dll625_dll_625_get_data_size
#define dll_625_func_28C __dll625_dll_625_func_28C
#define dll_625_func_3C4 __dll625_dll_625_func_3C4
#define str_0 __dll625_str_0
#define str_18 __dll625_str_18

#endif //_DLL_625_RECOMP_H
