// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_626_RECOMP_H
#define _DLL_626_RECOMP_H

#define dll_626_ctor __dll626_dll_626_ctor
#define dll_626_dtor __dll626_dll_626_dtor
#define dll_626_func_18 __dll626_dll_626_func_18
#define dll_626_func_120 __dll626_dll_626_func_120
#define dll_626_func_A4C __dll626_dll_626_func_A4C
#define dll_626_func_A58 __dll626_dll_626_func_A58
#define dll_626_func_AAC __dll626_dll_626_func_AAC
#define dll_626_func_B58 __dll626_dll_626_func_B58
#define dll_626_func_B68 __dll626_dll_626_func_B68
#define dll_626_func_B7C __dll626_dll_626_func_B7C
#define dll_626_func_11AC __dll626_dll_626_func_11AC
#define dll_626_func_172C __dll626_dll_626_func_172C
#define dll_626_func_1834 __dll626_dll_626_func_1834
#define str_0 __dll626_str_0

#endif //_DLL_626_RECOMP_H
