// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_631_RECOMP_H
#define _DLL_631_RECOMP_H

#define dll_631_ctor __dll631_dll_631_ctor
#define dll_631_dtor __dll631_dll_631_dtor
#define dll_631_func_18 __dll631_dll_631_func_18
#define dll_631_func_134 __dll631_dll_631_func_134
#define dll_631_func_1EC __dll631_dll_631_func_1EC
#define dll_631_func_1F8 __dll631_dll_631_func_1F8
#define dll_631_func_210 __dll631_dll_631_func_210
#define dll_631_func_2A0 __dll631_dll_631_func_2A0
#define dll_631_func_2B0 __dll631_dll_631_func_2B0
#define dll_631_func_2C4 __dll631_dll_631_func_2C4
#define dll_631_func_5E4 __dll631_dll_631_func_5E4
#define dll_631_func_754 __dll631_dll_631_func_754
#define dll_631_func_80C __dll631_dll_631_func_80C
#define _data_0 __dll631__data_0
#define _data_4 __dll631__data_4
#define _data_8 __dll631__data_8
#define _data_C __dll631__data_C
#define _data_18 __dll631__data_18

#endif //_DLL_631_RECOMP_H
