// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_631_RECOMP_H
#define _DLL_631_RECOMP_H

#define dll_631_ctor __dll631_dll_631_ctor
#define dll_631_dtor __dll631_dll_631_dtor
#define dll_631_setup __dll631_dll_631_setup
#define dll_631_control __dll631_dll_631_control
#define dll_631_update __dll631_dll_631_update
#define dll_631_print __dll631_dll_631_print
#define dll_631_free __dll631_dll_631_free
#define dll_631_get_model_flags __dll631_dll_631_get_model_flags
#define dll_631_get_data_size __dll631_dll_631_get_data_size
#define dll_631_func_2C4 __dll631_dll_631_func_2C4
#define dll_631_func_5E4 __dll631_dll_631_func_5E4
#define dll_631_func_754 __dll631_dll_631_func_754
#define dll_631_func_80C __dll631_dll_631_func_80C
#define _data_0 __dll631__data_0
#define _data_4 __dll631__data_4
#define _data_8 __dll631__data_8
#define _data_C __dll631__data_C
#define _data_18 __dll631__data_18

#endif //_DLL_631_RECOMP_H
