// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_633_RECOMP_H
#define _DLL_633_RECOMP_H

#define dll_633_ctor __dll633_dll_633_ctor
#define dll_633_dtor __dll633_dll_633_dtor
#define dll_633_func_18 __dll633_dll_633_func_18
#define dll_633_func_68 __dll633_dll_633_func_68
#define dll_633_func_128 __dll633_dll_633_func_128
#define dll_633_func_16C __dll633_dll_633_func_16C
#define dll_633_func_184 __dll633_dll_633_func_184
#define dll_633_func_194 __dll633_dll_633_func_194
#define dll_633_func_1A4 __dll633_dll_633_func_1A4
#define dll_633_func_1B8 __dll633_dll_633_func_1B8
#define dll_633_func_324 __dll633_dll_633_func_324
#define _data_0 __dll633__data_0

#endif //_DLL_633_RECOMP_H
