// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_634_RECOMP_H
#define _DLL_634_RECOMP_H

#define dll_634_ctor __dll634_dll_634_ctor
#define dll_634_dtor __dll634_dll_634_dtor
#define dll_634_setup __dll634_dll_634_setup
#define dll_634_control __dll634_dll_634_control
#define dll_634_update __dll634_dll_634_update
#define dll_634_print __dll634_dll_634_print
#define dll_634_free __dll634_dll_634_free
#define dll_634_get_model_flags __dll634_dll_634_get_model_flags
#define dll_634_get_data_size __dll634_dll_634_get_data_size
#define dll_634_func_280 __dll634_dll_634_func_280

#endif //_DLL_634_RECOMP_H
