// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_635_RECOMP_H
#define _DLL_635_RECOMP_H

#define dll_635_ctor __dll635_dll_635_ctor
#define dll_635_dtor __dll635_dll_635_dtor
#define dll_635_setup __dll635_dll_635_setup
#define dll_635_control __dll635_dll_635_control
#define dll_635_update __dll635_dll_635_update
#define dll_635_print __dll635_dll_635_print
#define dll_635_free __dll635_dll_635_free
#define dll_635_get_model_flags __dll635_dll_635_get_model_flags
#define dll_635_get_data_size __dll635_dll_635_get_data_size
#define dll_635_func_208 __dll635_dll_635_func_208
#define dll_635_func_224 __dll635_dll_635_func_224
#define _rodata_0 __dll635__rodata_0
#define _rodata_4 __dll635__rodata_4
#define _rodata_8 __dll635__rodata_8
#define _rodata_C __dll635__rodata_C
#define _rodata_10 __dll635__rodata_10
#define _rodata_14 __dll635__rodata_14
#define _data_0 __dll635__data_0
#define _data_14 __dll635__data_14

#endif //_DLL_635_RECOMP_H
