// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_636_RECOMP_H
#define _DLL_636_RECOMP_H

#define dll_636_ctor __dll636_dll_636_ctor
#define dll_636_dtor __dll636_dll_636_dtor
#define dll_636_func_18 __dll636_dll_636_func_18
#define dll_636_func_158 __dll636_dll_636_func_158
#define dll_636_func_2BC __dll636_dll_636_func_2BC
#define dll_636_func_2C8 __dll636_dll_636_func_2C8
#define dll_636_func_2E0 __dll636_dll_636_func_2E0
#define dll_636_func_390 __dll636_dll_636_func_390
#define dll_636_func_3A0 __dll636_dll_636_func_3A0
#define _rodata_0 __dll636__rodata_0
#define _rodata_4 __dll636__rodata_4
#define _data_0 __dll636__data_0

#endif //_DLL_636_RECOMP_H
