// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_637_RECOMP_H
#define _DLL_637_RECOMP_H

#define dll_637_ctor __dll637_dll_637_ctor
#define dll_637_dtor __dll637_dll_637_dtor
#define dll_637_func_18 __dll637_dll_637_func_18
#define dll_637_func_C8 __dll637_dll_637_func_C8
#define dll_637_func_1AC __dll637_dll_637_func_1AC
#define dll_637_func_1B8 __dll637_dll_637_func_1B8
#define dll_637_func_1D0 __dll637_dll_637_func_1D0
#define dll_637_func_1E0 __dll637_dll_637_func_1E0
#define dll_637_func_1F0 __dll637_dll_637_func_1F0
#define dll_637_func_204 __dll637_dll_637_func_204
#define dll_637_func_2E0 __dll637_dll_637_func_2E0
#define _oob_rodata_0 __dll637__oob_rodata_0

#endif //_DLL_637_RECOMP_H
