// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_640_RECOMP_H
#define _DLL_640_RECOMP_H

#define dll_640_ctor __dll640_dll_640_ctor
#define dll_640_dtor __dll640_dll_640_dtor
#define dll_640_obj_Setup __dll640_dll_640_obj_Setup
#define dll_640_obj_Control __dll640_dll_640_obj_Control
#define dll_640_obj_Update __dll640_dll_640_obj_Update
#define dll_640_obj_Print __dll640_dll_640_obj_Print
#define dll_640_obj_Free __dll640_dll_640_obj_Free
#define dll_640_obj_GetModelFlags __dll640_dll_640_obj_GetModelFlags
#define dll_640_obj_GetDataSize __dll640_dll_640_obj_GetDataSize
#define rodata_0 __dll640_rodata_0
#define data_0 __dll640_data_0
#define data_4 __dll640_data_4
#define data_14 __dll640_data_14

#endif //_DLL_640_RECOMP_H
