// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_641_RECOMP_H
#define _DLL_641_RECOMP_H

#define dll_641_ctor __dll641_dll_641_ctor
#define dll_641_dtor __dll641_dll_641_dtor
#define dll_641_func_18 __dll641_dll_641_func_18
#define dll_641_func_9C __dll641_dll_641_func_9C
#define dll_641_func_7EC __dll641_dll_641_func_7EC
#define dll_641_func_7F8 __dll641_dll_641_func_7F8
#define dll_641_func_84C __dll641_dll_641_func_84C
#define dll_641_func_8F8 __dll641_dll_641_func_8F8
#define dll_641_func_908 __dll641_dll_641_func_908
#define dll_641_func_91C __dll641_dll_641_func_91C
#define _rodata_0 __dll641__rodata_0
#define _rodata_18 __dll641__rodata_18
#define _rodata_1C __dll641__rodata_1C

#endif //_DLL_641_RECOMP_H
