// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_644_RECOMP_H
#define _DLL_644_RECOMP_H

#define dll_644_ctor __dll644_dll_644_ctor
#define dll_644_dtor __dll644_dll_644_dtor
#define dll_644_setup __dll644_dll_644_setup
#define dll_644_control __dll644_dll_644_control
#define dll_644_update __dll644_dll_644_update
#define dll_644_print __dll644_dll_644_print
#define dll_644_free __dll644_dll_644_free
#define dll_644_get_model_flags __dll644_dll_644_get_model_flags
#define dll_644_get_data_size __dll644_dll_644_get_data_size
#define dll_644_func_6AC __dll644_dll_644_func_6AC
#define str_0 __dll644_str_0
#define _rodata_C __dll644__rodata_C
#define _rodata_10 __dll644__rodata_10
#define _data_0 __dll644__data_0
#define _data_4 __dll644__data_4

#endif //_DLL_644_RECOMP_H
