// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_644_RECOMP_H
#define _DLL_644_RECOMP_H

#define dll_644_ctor __dll644_dll_644_ctor
#define dll_644_dtor __dll644_dll_644_dtor
#define dll_644_create __dll644_dll_644_create
#define dll_644_update __dll644_dll_644_update
#define dll_644_func_560 __dll644_dll_644_func_560
#define dll_644_draw __dll644_dll_644_draw
#define dll_644_destroy __dll644_dll_644_destroy
#define dll_644_get_setup_flags __dll644_dll_644_get_setup_flags
#define dll_644_get_state_size __dll644_dll_644_get_state_size
#define dll_644_func_6AC __dll644_dll_644_func_6AC
#define str_0 __dll644_str_0
#define _rodata_C __dll644__rodata_C
#define _rodata_10 __dll644__rodata_10
#define _data_0 __dll644__data_0
#define _data_4 __dll644__data_4

#endif //_DLL_644_RECOMP_H
