// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_644_RECOMP_H
#define _DLL_644_RECOMP_H

#define dll_644_ctor __dll644_dll_644_ctor
#define dll_644_dtor __dll644_dll_644_dtor
#define dll_644_func_18 __dll644_dll_644_func_18
#define dll_644_func_F8 __dll644_dll_644_func_F8
#define dll_644_func_560 __dll644_dll_644_func_560
#define dll_644_func_5A0 __dll644_dll_644_func_5A0
#define dll_644_func_640 __dll644_dll_644_func_640
#define dll_644_func_688 __dll644_dll_644_func_688
#define dll_644_func_698 __dll644_dll_644_func_698
#define dll_644_func_6AC __dll644_dll_644_func_6AC
#define str_0 __dll644_str_0
#define _rodata_C __dll644__rodata_C
#define _rodata_10 __dll644__rodata_10
#define _data_0 __dll644__data_0
#define _data_4 __dll644__data_4

#endif //_DLL_644_RECOMP_H
