// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_650_RECOMP_H
#define _DLL_650_RECOMP_H

#define dll_650_ctor __dll650_dll_650_ctor
#define dll_650_dtor __dll650_dll_650_dtor
#define dll_650_func_18 __dll650_dll_650_func_18
#define dll_650_func_2DC __dll650_dll_650_func_2DC
#define dll_650_func_648 __dll650_dll_650_func_648
#define dll_650_func_D74 __dll650_dll_650_func_D74
#define dll_650_func_DEC __dll650_dll_650_func_DEC
#define dll_650_func_E88 __dll650_dll_650_func_E88
#define dll_650_func_E98 __dll650_dll_650_func_E98
#define dll_650_func_EAC __dll650_dll_650_func_EAC
#define str_0 __dll650_str_0
#define _rodata_2C __dll650__rodata_2C
#define _rodata_30 __dll650__rodata_30
#define _rodata_34 __dll650__rodata_34
#define _data_0 __dll650__data_0
#define _data_10 __dll650__data_10
#define _data_1C __dll650__data_1C
#define _data_20 __dll650__data_20

#endif //_DLL_650_RECOMP_H
