// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_650_RECOMP_H
#define _DLL_650_RECOMP_H

#define dll_650_ctor __dll650_dll_650_ctor
#define dll_650_dtor __dll650_dll_650_dtor
#define dll_650_obj_Setup __dll650_dll_650_obj_Setup
#define dll_650_obj_Control __dll650_dll_650_obj_Control
#define dll_650_obj_Update __dll650_dll_650_obj_Update
#define dll_650_obj_Print __dll650_dll_650_obj_Print
#define dll_650_obj_Free __dll650_dll_650_obj_Free
#define dll_650_obj_GetModelFlags __dll650_dll_650_obj_GetModelFlags
#define dll_650_obj_GetDataSize __dll650_dll_650_obj_GetDataSize
#define dll_650_func_EAC __dll650_dll_650_func_EAC
#define str_0 __dll650_str_0
#define rodata_2C __dll650_rodata_2C
#define rodata_30 __dll650_rodata_30
#define rodata_34 __dll650_rodata_34
#define data_0 __dll650_data_0
#define data_10 __dll650_data_10
#define data_1C __dll650_data_1C
#define data_20 __dll650_data_20

#endif //_DLL_650_RECOMP_H
