// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_651_RECOMP_H
#define _DLL_651_RECOMP_H

#define dll_651_ctor __dll651_dll_651_ctor
#define dll_651_dtor __dll651_dll_651_dtor
#define dll_651_setup __dll651_dll_651_setup
#define dll_651_control __dll651_dll_651_control
#define dll_651_update __dll651_dll_651_update
#define dll_651_print __dll651_dll_651_print
#define dll_651_free __dll651_dll_651_free
#define dll_651_get_model_flags __dll651_dll_651_get_model_flags
#define dll_651_get_data_size __dll651_dll_651_get_data_size
#define rodata_0 __dll651_rodata_0
#define rodata_4 __dll651_rodata_4
#define rodata_8 __dll651_rodata_8
#define data_0 __dll651_data_0
#define data_8 __dll651_data_8

#endif //_DLL_651_RECOMP_H
