// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_651_RECOMP_H
#define _DLL_651_RECOMP_H

#define dll_651_ctor __dll651_dll_651_ctor
#define dll_651_dtor __dll651_dll_651_dtor
#define dll_651_create __dll651_dll_651_create
#define dll_651_update __dll651_dll_651_update
#define dll_651_func_7C8 __dll651_dll_651_func_7C8
#define dll_651_draw __dll651_dll_651_draw
#define dll_651_destroy __dll651_dll_651_destroy
#define dll_651_get_model_flags __dll651_dll_651_get_model_flags
#define dll_651_get_state_size __dll651_dll_651_get_state_size
#define _rodata_0 __dll651__rodata_0
#define _rodata_4 __dll651__rodata_4
#define _rodata_8 __dll651__rodata_8
#define _data_0 __dll651__data_0
#define _data_8 __dll651__data_8

#endif //_DLL_651_RECOMP_H
