// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_653_RECOMP_H
#define _DLL_653_RECOMP_H

#define dll_653_ctor __dll653_dll_653_ctor
#define dll_653_dtor __dll653_dll_653_dtor
#define dll_653_setup __dll653_dll_653_setup
#define dll_653_control __dll653_dll_653_control
#define dll_653_update __dll653_dll_653_update
#define dll_653_print __dll653_dll_653_print
#define dll_653_free __dll653_dll_653_free
#define dll_653_get_model_flags __dll653_dll_653_get_model_flags
#define dll_653_get_data_size __dll653_dll_653_get_data_size
#define str_0 __dll653_str_0
#define _data_0 __dll653__data_0

#endif //_DLL_653_RECOMP_H
