// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_654_RECOMP_H
#define _DLL_654_RECOMP_H

#define dll_654_ctor __dll654_dll_654_ctor
#define dll_654_dtor __dll654_dll_654_dtor
#define dll_654_func_18 __dll654_dll_654_func_18
#define dll_654_func_D0 __dll654_dll_654_func_D0
#define dll_654_func_114 __dll654_dll_654_func_114
#define dll_654_func_120 __dll654_dll_654_func_120
#define dll_654_func_138 __dll654_dll_654_func_138
#define dll_654_func_1AC __dll654_dll_654_func_1AC
#define dll_654_func_1BC __dll654_dll_654_func_1BC
#define dll_654_func_1D0 __dll654_dll_654_func_1D0
#define dll_654_func_3A0 __dll654_dll_654_func_3A0
#define _data_0 __dll654__data_0

#endif //_DLL_654_RECOMP_H
