// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_659_RECOMP_H
#define _DLL_659_RECOMP_H

#define dll_659_ctor __dll659_dll_659_ctor
#define dll_659_dtor __dll659_dll_659_dtor
#define dll_659_func_18 __dll659_dll_659_func_18
#define dll_659_func_84 __dll659_dll_659_func_84
#define dll_659_func_330 __dll659_dll_659_func_330
#define dll_659_func_33C __dll659_dll_659_func_33C
#define dll_659_func_390 __dll659_dll_659_func_390
#define dll_659_func_3A0 __dll659_dll_659_func_3A0
#define dll_659_func_3B0 __dll659_dll_659_func_3B0
#define dll_659_func_3C4 __dll659_dll_659_func_3C4
#define dll_659_func_57C __dll659_dll_659_func_57C
#define str_0 __dll659_str_0
#define _data_0 __dll659__data_0

#endif //_DLL_659_RECOMP_H
