// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_663_RECOMP_H
#define _DLL_663_RECOMP_H

#define dll_663_ctor __dll663_dll_663_ctor
#define dll_663_dtor __dll663_dll_663_dtor
#define dll_663_setup __dll663_dll_663_setup
#define dll_663_control __dll663_dll_663_control
#define dll_663_update __dll663_dll_663_update
#define dll_663_print __dll663_dll_663_print
#define dll_663_free __dll663_dll_663_free
#define dll_663_get_model_flags __dll663_dll_663_get_model_flags
#define dll_663_get_data_size __dll663_dll_663_get_data_size
#define str_0 __dll663_str_0
#define _data_0 __dll663__data_0
#define _data_8 __dll663__data_8
#define _data_E __dll663__data_E
#define _data_10 __dll663__data_10
#define _data_18 __dll663__data_18
#define _data_1E __dll663__data_1E
#define _data_20 __dll663__data_20

#endif //_DLL_663_RECOMP_H
