// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_663_RECOMP_H
#define _DLL_663_RECOMP_H

#define dll_663_ctor __dll663_dll_663_ctor
#define dll_663_dtor __dll663_dll_663_dtor
#define dll_663_func_18 __dll663_dll_663_func_18
#define dll_663_func_E4 __dll663_dll_663_func_E4
#define dll_663_func_360 __dll663_dll_663_func_360
#define dll_663_func_36C __dll663_dll_663_func_36C
#define dll_663_func_384 __dll663_dll_663_func_384
#define dll_663_func_3C4 __dll663_dll_663_func_3C4
#define dll_663_func_3D4 __dll663_dll_663_func_3D4
#define str_0 __dll663_str_0
#define _data_0 __dll663__data_0
#define _data_8 __dll663__data_8
#define _data_E __dll663__data_E
#define _data_10 __dll663__data_10
#define _data_18 __dll663__data_18
#define _data_1E __dll663__data_1E
#define _data_20 __dll663__data_20

#endif //_DLL_663_RECOMP_H
