// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_664_RECOMP_H
#define _DLL_664_RECOMP_H

#define dll_664_ctor __dll664_dll_664_ctor
#define dll_664_dtor __dll664_dll_664_dtor
#define dll_664_setup __dll664_dll_664_setup
#define dll_664_control __dll664_dll_664_control
#define dll_664_update __dll664_dll_664_update
#define dll_664_print __dll664_dll_664_print
#define dll_664_free __dll664_dll_664_free
#define dll_664_get_model_flags __dll664_dll_664_get_model_flags
#define dll_664_get_data_size __dll664_dll_664_get_data_size
#define _rodata_0 __dll664__rodata_0

#endif //_DLL_664_RECOMP_H
