// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_664_RECOMP_H
#define _DLL_664_RECOMP_H

#define dll_664_ctor __dll664_dll_664_ctor
#define dll_664_dtor __dll664_dll_664_dtor
#define dll_664_func_18 __dll664_dll_664_func_18
#define dll_664_func_D0 __dll664_dll_664_func_D0
#define dll_664_func_49C __dll664_dll_664_func_49C
#define dll_664_func_4A8 __dll664_dll_664_func_4A8
#define dll_664_func_4C0 __dll664_dll_664_func_4C0
#define dll_664_func_530 __dll664_dll_664_func_530
#define dll_664_func_540 __dll664_dll_664_func_540
#define _rodata_0 __dll664__rodata_0

#endif //_DLL_664_RECOMP_H
