// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_666_RECOMP_H
#define _DLL_666_RECOMP_H

#define dll_666_ctor __dll666_dll_666_ctor
#define dll_666_dtor __dll666_dll_666_dtor
#define dll_666_setup __dll666_dll_666_setup
#define dll_666_control __dll666_dll_666_control
#define dll_666_update __dll666_dll_666_update
#define dll_666_print __dll666_dll_666_print
#define dll_666_free __dll666_dll_666_free
#define dll_666_get_model_flags __dll666_dll_666_get_model_flags
#define dll_666_get_data_size __dll666_dll_666_get_data_size
#define dll_666_func_618 __dll666_dll_666_func_618
#define dll_666_func_630 __dll666_dll_666_func_630
#define dll_666_func_724 __dll666_dll_666_func_724
#define dll_666_func_7F0 __dll666_dll_666_func_7F0
#define dll_666_func_D14 __dll666_dll_666_func_D14
#define dll_666_func_DC8 __dll666_dll_666_func_DC8
#define dll_666_func_E44 __dll666_dll_666_func_E44
#define dll_666_func_FFC __dll666_dll_666_func_FFC
#define str_0 __dll666_str_0
#define rodata_4C __dll666_rodata_4C
#define rodata_50 __dll666_rodata_50
#define rodata_54 __dll666_rodata_54
#define rodata_58 __dll666_rodata_58
#define rodata_5C __dll666_rodata_5C
#define rodata_60 __dll666_rodata_60
#define rodata_64 __dll666_rodata_64
#define rodata_68 __dll666_rodata_68
#define data_0 __dll666_data_0
#define data_C __dll666_data_C
#define data_18 __dll666_data_18
#define data_38 __dll666_data_38
#define data_58 __dll666_data_58
#define data_98 __dll666_data_98
#define data_E8 __dll666_data_E8
#define data_FC __dll666_data_FC
#define data_104 __dll666_data_104
#define data_120 __dll666_data_120
#define data_128 __dll666_data_128
#define data_144 __dll666_data_144
#define data_14C __dll666_data_14C
#define data_154 __dll666_data_154
#define data_16C __dll666_data_16C
#define data_170 __dll666_data_170
#define data_174 __dll666_data_174
#define bss_0 __dll666_bss_0
#define bss_4 __dll666_bss_4
#define bss_8 __dll666_bss_8

#endif //_DLL_666_RECOMP_H
