// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_669_RECOMP_H
#define _DLL_669_RECOMP_H

#define dll_669_ctor __dll669_dll_669_ctor
#define dll_669_dtor __dll669_dll_669_dtor
#define dll_669_setup __dll669_dll_669_setup
#define dll_669_control __dll669_dll_669_control
#define dll_669_func_56C __dll669_dll_669_func_56C
#define dll_669_update __dll669_dll_669_update
#define dll_669_print __dll669_dll_669_print
#define dll_669_free __dll669_dll_669_free
#define dll_669_get_model_flags __dll669_dll_669_get_model_flags
#define dll_669_get_data_size __dll669_dll_669_get_data_size
#define dll_669_func_C70 __dll669_dll_669_func_C70
#define dll_669_func_110C __dll669_dll_669_func_110C
#define dll_669_func_13F4 __dll669_dll_669_func_13F4
#define dll_669_func_17D4 __dll669_dll_669_func_17D4
#define dll_669_func_18EC __dll669_dll_669_func_18EC
#define str_0 __dll669_str_0
#define rodata_FC __dll669_rodata_FC
#define rodata_100 __dll669_rodata_100
#define rodata_104 __dll669_rodata_104
#define rodata_108 __dll669_rodata_108
#define rodata_10C __dll669_rodata_10C
#define rodata_110 __dll669_rodata_110
#define data_0 __dll669_data_0
#define data_2D0 __dll669_data_2D0
#define data_2E0 __dll669_data_2E0
#define data_2E4 __dll669_data_2E4

#endif //_DLL_669_RECOMP_H
