// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_672_RECOMP_H
#define _DLL_672_RECOMP_H

#define dll_672_ctor __dll672_dll_672_ctor
#define dll_672_dtor __dll672_dll_672_dtor
#define dll_672_obj_Setup __dll672_dll_672_obj_Setup
#define dll_672_obj_Control __dll672_dll_672_obj_Control
#define dll_672_obj_Update __dll672_dll_672_obj_Update
#define dll_672_obj_Print __dll672_dll_672_obj_Print
#define dll_672_obj_Free __dll672_dll_672_obj_Free
#define dll_672_obj_GetModelFlags __dll672_dll_672_obj_GetModelFlags
#define dll_672_obj_GetDataSize __dll672_dll_672_obj_GetDataSize
#define dll_672_func_844 __dll672_dll_672_func_844
#define dll_672_func_924 __dll672_dll_672_func_924
#define rodata_0 __dll672_rodata_0
#define rodata_4 __dll672_rodata_4
#define rodata_20 __dll672_rodata_20
#define rodata_24 __dll672_rodata_24
#define rodata_28 __dll672_rodata_28
#define rodata_2C __dll672_rodata_2C
#define data_0 __dll672_data_0

#endif //_DLL_672_RECOMP_H
