// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_672_RECOMP_H
#define _DLL_672_RECOMP_H

#define dll_672_ctor __dll672_dll_672_ctor
#define dll_672_dtor __dll672_dll_672_dtor
#define dll_672_setup __dll672_dll_672_setup
#define dll_672_control __dll672_dll_672_control
#define dll_672_update __dll672_dll_672_update
#define dll_672_print __dll672_dll_672_print
#define dll_672_free __dll672_dll_672_free
#define dll_672_get_model_flags __dll672_dll_672_get_model_flags
#define dll_672_get_data_size __dll672_dll_672_get_data_size
#define dll_672_func_844 __dll672_dll_672_func_844
#define dll_672_func_924 __dll672_dll_672_func_924
#define rodata_0 __dll672_rodata_0
#define rodata_4 __dll672_rodata_4
#define rodata_20 __dll672_rodata_20
#define rodata_24 __dll672_rodata_24
#define rodata_28 __dll672_rodata_28
#define rodata_2C __dll672_rodata_2C
#define data_0 __dll672_data_0

#endif //_DLL_672_RECOMP_H
