// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_675_RECOMP_H
#define _DLL_675_RECOMP_H

#define dll_675_ctor __dll675_dll_675_ctor
#define dll_675_dtor __dll675_dll_675_dtor
#define dll_675_func_18 __dll675_dll_675_func_18
#define dll_675_func_168 __dll675_dll_675_func_168
#define dll_675_func_680 __dll675_dll_675_func_680
#define dll_675_func_68C __dll675_dll_675_func_68C
#define dll_675_func_6E0 __dll675_dll_675_func_6E0
#define dll_675_func_6F0 __dll675_dll_675_func_6F0
#define dll_675_func_700 __dll675_dll_675_func_700
#define dll_675_func_714 __dll675_dll_675_func_714
#define dll_675_func_7F4 __dll675_dll_675_func_7F4
#define str_0 __dll675_str_0
#define _rodata_10 __dll675__rodata_10
#define _rodata_14 __dll675__rodata_14
#define _rodata_30 __dll675__rodata_30
#define _rodata_34 __dll675__rodata_34
#define _data_0 __dll675__data_0
#define _data_214 __dll675__data_214

#endif //_DLL_675_RECOMP_H
