// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_681_RECOMP_H
#define _DLL_681_RECOMP_H

#define dll_681_ctor __dll681_dll_681_ctor
#define dll_681_dtor __dll681_dll_681_dtor
#define dll_681_obj_Setup __dll681_dll_681_obj_Setup
#define dll_681_obj_Control __dll681_dll_681_obj_Control
#define dll_681_obj_Update __dll681_dll_681_obj_Update
#define dll_681_obj_Print __dll681_dll_681_obj_Print
#define dll_681_obj_Free __dll681_dll_681_obj_Free
#define dll_681_obj_GetModelFlags __dll681_dll_681_obj_GetModelFlags
#define dll_681_obj_GetDataSize __dll681_dll_681_obj_GetDataSize
#define str_0 __dll681_str_0
#define rodata_28 __dll681_rodata_28
#define rodata_2C __dll681_rodata_2C
#define data_0 __dll681_data_0
#define data_18 __dll681_data_18

#endif //_DLL_681_RECOMP_H
