// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_681_RECOMP_H
#define _DLL_681_RECOMP_H

#define dll_681_ctor __dll681_dll_681_ctor
#define dll_681_dtor __dll681_dll_681_dtor
#define dll_681_func_18 __dll681_dll_681_func_18
#define dll_681_func_104 __dll681_dll_681_func_104
#define dll_681_func_110 __dll681_dll_681_func_110
#define dll_681_func_39C __dll681_dll_681_func_39C
#define dll_681_func_404 __dll681_dll_681_func_404
#define dll_681_func_460 __dll681_dll_681_func_460
#define dll_681_func_470 __dll681_dll_681_func_470
#define str_0 __dll681_str_0
#define _rodata_28 __dll681__rodata_28
#define _rodata_2C __dll681__rodata_2C
#define _data_0 __dll681__data_0
#define _data_18 __dll681__data_18

#endif //_DLL_681_RECOMP_H
