// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_685_RECOMP_H
#define _DLL_685_RECOMP_H

#define dll_685_ctor __dll685_dll_685_ctor
#define dll_685_dtor __dll685_dll_685_dtor
#define dll_685_func_18 __dll685_dll_685_func_18
#define dll_685_func_B0 __dll685_dll_685_func_B0
#define dll_685_func_488 __dll685_dll_685_func_488
#define dll_685_func_494 __dll685_dll_685_func_494
#define dll_685_func_4F8 __dll685_dll_685_func_4F8
#define dll_685_func_508 __dll685_dll_685_func_508
#define dll_685_func_518 __dll685_dll_685_func_518
#define dll_685_func_52C __dll685_dll_685_func_52C
#define dll_685_func_544 __dll685_dll_685_func_544
#define str_0 __dll685_str_0
#define _rodata_C __dll685__rodata_C
#define _rodata_10 __dll685__rodata_10
#define _rodata_14 __dll685__rodata_14
#define _rodata_18 __dll685__rodata_18

#endif //_DLL_685_RECOMP_H
