// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_686_RECOMP_H
#define _DLL_686_RECOMP_H

#define dll_686_ctor __dll686_dll_686_ctor
#define dll_686_dtor __dll686_dll_686_dtor
#define dll_686_func_18 __dll686_dll_686_func_18
#define dll_686_func_184 __dll686_dll_686_func_184
#define dll_686_func_8B4 __dll686_dll_686_func_8B4
#define dll_686_func_8C0 __dll686_dll_686_func_8C0
#define dll_686_func_918 __dll686_dll_686_func_918
#define dll_686_func_998 __dll686_dll_686_func_998
#define dll_686_func_9A8 __dll686_dll_686_func_9A8
#define dll_686_func_9BC __dll686_dll_686_func_9BC
#define dll_686_func_A24 __dll686_dll_686_func_A24
#define dll_686_func_A50 __dll686_dll_686_func_A50
#define dll_686_func_A68 __dll686_dll_686_func_A68
#define dll_686_func_A8C __dll686_dll_686_func_A8C
#define str_0 __dll686_str_0
#define _rodata_6C __dll686__rodata_6C
#define _rodata_70 __dll686__rodata_70
#define _rodata_74 __dll686__rodata_74
#define _rodata_78 __dll686__rodata_78
#define _rodata_7C __dll686__rodata_7C
#define _rodata_80 __dll686__rodata_80
#define _rodata_84 __dll686__rodata_84

#endif //_DLL_686_RECOMP_H
