// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_687_RECOMP_H
#define _DLL_687_RECOMP_H

#define dll_687_ctor __dll687_dll_687_ctor
#define dll_687_dtor __dll687_dll_687_dtor
#define dll_687_setup __dll687_dll_687_setup
#define dll_687_control __dll687_dll_687_control
#define dll_687_update __dll687_dll_687_update
#define dll_687_print __dll687_dll_687_print
#define dll_687_free __dll687_dll_687_free
#define dll_687_get_model_flags __dll687_dll_687_get_model_flags
#define dll_687_get_data_size __dll687_dll_687_get_data_size
#define dll_687_func_1E0 __dll687_dll_687_func_1E0
#define dll_687_func_3A4 __dll687_dll_687_func_3A4

#endif //_DLL_687_RECOMP_H
