// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_689_RECOMP_H
#define _DLL_689_RECOMP_H

#define dll_689_ctor __dll689_dll_689_ctor
#define dll_689_dtor __dll689_dll_689_dtor
#define dll_689_func_18 __dll689_dll_689_func_18
#define dll_689_func_130 __dll689_dll_689_func_130
#define dll_689_func_38C __dll689_dll_689_func_38C
#define dll_689_func_398 __dll689_dll_689_func_398
#define dll_689_func_404 __dll689_dll_689_func_404
#define dll_689_func_444 __dll689_dll_689_func_444
#define dll_689_func_454 __dll689_dll_689_func_454
#define dll_689_func_468 __dll689_dll_689_func_468
#define str_0 __dll689_str_0

#endif //_DLL_689_RECOMP_H
