// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_689_RECOMP_H
#define _DLL_689_RECOMP_H

#define dll_689_ctor __dll689_dll_689_ctor
#define dll_689_dtor __dll689_dll_689_dtor
#define dll_689_create __dll689_dll_689_create
#define dll_689_update __dll689_dll_689_update
#define dll_689_func_38C __dll689_dll_689_func_38C
#define dll_689_draw __dll689_dll_689_draw
#define dll_689_destroy __dll689_dll_689_destroy
#define dll_689_get_setup_flags __dll689_dll_689_get_setup_flags
#define dll_689_get_state_size __dll689_dll_689_get_state_size
#define dll_689_func_468 __dll689_dll_689_func_468
#define str_0 __dll689_str_0

#endif //_DLL_689_RECOMP_H
