// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_68_RECOMP_H
#define _DLL_68_RECOMP_H

#define dll_68_ctor __dll68_dll_68_ctor
#define dll_68_dtor __dll68_dll_68_dtor
#define dll_68_func_C4 __dll68_dll_68_func_C4
#define dll_68_func_D0 __dll68_dll_68_func_D0
#define dll_68_func_D8 __dll68_dll_68_func_D8
#define data_0 __dll68_data_0
#define bss_0 __dll68_bss_0
#define bss_4 __dll68_bss_4
#define bss_8 __dll68_bss_8
#define bss_C __dll68_bss_C
#define bss_10 __dll68_bss_10

#endif //_DLL_68_RECOMP_H
