// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_690_RECOMP_H
#define _DLL_690_RECOMP_H

#define dll_690_ctor __dll690_dll_690_ctor
#define dll_690_dtor __dll690_dll_690_dtor
#define dll_690_func_18 __dll690_dll_690_func_18
#define dll_690_func_19C __dll690_dll_690_func_19C
#define dll_690_func_2E8 __dll690_dll_690_func_2E8
#define dll_690_func_340 __dll690_dll_690_func_340
#define dll_690_func_53C __dll690_dll_690_func_53C
#define dll_690_func_604 __dll690_dll_690_func_604
#define dll_690_func_614 __dll690_dll_690_func_614
#define dll_690_func_628 __dll690_dll_690_func_628
#define dll_690_func_884 __dll690_dll_690_func_884
#define dll_690_func_934 __dll690_dll_690_func_934
#define str_0 __dll690_str_0
#define _rodata_68 __dll690__rodata_68
#define _rodata_6C __dll690__rodata_6C
#define _data_0 __dll690__data_0
#define _data_24 __dll690__data_24
#define _data_28 __dll690__data_28

#endif //_DLL_690_RECOMP_H
