// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_691_RECOMP_H
#define _DLL_691_RECOMP_H

#define dll_691_ctor __dll691_dll_691_ctor
#define dll_691_dtor __dll691_dll_691_dtor
#define dll_691_func_18 __dll691_dll_691_func_18
#define dll_691_func_A0 __dll691_dll_691_func_A0
#define dll_691_func_AC __dll691_dll_691_func_AC
#define dll_691_func_B8 __dll691_dll_691_func_B8
#define dll_691_func_200 __dll691_dll_691_func_200
#define dll_691_func_210 __dll691_dll_691_func_210
#define dll_691_func_220 __dll691_dll_691_func_220
#define str_0 __dll691_str_0

#endif //_DLL_691_RECOMP_H
