// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_695_RECOMP_H
#define _DLL_695_RECOMP_H

#define dll_695_ctor __dll695_dll_695_ctor
#define dll_695_dtor __dll695_dll_695_dtor
#define dll_695_func_18 __dll695_dll_695_func_18
#define dll_695_func_AC __dll695_dll_695_func_AC
#define dll_695_func_128 __dll695_dll_695_func_128
#define dll_695_func_134 __dll695_dll_695_func_134
#define dll_695_func_14C __dll695_dll_695_func_14C
#define dll_695_func_1A4 __dll695_dll_695_func_1A4
#define dll_695_func_1B4 __dll695_dll_695_func_1B4
#define dll_695_func_1C8 __dll695_dll_695_func_1C8
#define _data_0 __dll695__data_0
#define _data_4 __dll695__data_4
#define _bss_0 __dll695__bss_0

#endif //_DLL_695_RECOMP_H
