// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_696_RECOMP_H
#define _DLL_696_RECOMP_H

#define dll_696_ctor __dll696_dll_696_ctor
#define dll_696_dtor __dll696_dll_696_dtor
#define dll_696_create __dll696_dll_696_create
#define dll_696_update __dll696_dll_696_update
#define dll_696_func_30C __dll696_dll_696_func_30C
#define dll_696_draw __dll696_dll_696_draw
#define dll_696_destroy __dll696_dll_696_destroy
#define dll_696_get_setup_flags __dll696_dll_696_get_setup_flags
#define dll_696_get_state_size __dll696_dll_696_get_state_size
#define dll_696_func_364 __dll696_dll_696_func_364

#endif //_DLL_696_RECOMP_H
