// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_696_RECOMP_H
#define _DLL_696_RECOMP_H

#define dll_696_ctor __dll696_dll_696_ctor
#define dll_696_dtor __dll696_dll_696_dtor
#define dll_696_func_18 __dll696_dll_696_func_18
#define dll_696_func_9C __dll696_dll_696_func_9C
#define dll_696_func_30C __dll696_dll_696_func_30C
#define dll_696_func_318 __dll696_dll_696_func_318
#define dll_696_func_330 __dll696_dll_696_func_330
#define dll_696_func_340 __dll696_dll_696_func_340
#define dll_696_func_350 __dll696_dll_696_func_350
#define dll_696_func_364 __dll696_dll_696_func_364

#endif //_DLL_696_RECOMP_H
