// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_699_RECOMP_H
#define _DLL_699_RECOMP_H

#define dll_699_ctor __dll699_dll_699_ctor
#define dll_699_dtor __dll699_dll_699_dtor
#define dll_699_func_18 __dll699_dll_699_func_18
#define dll_699_func_C0 __dll699_dll_699_func_C0
#define dll_699_func_BB0 __dll699_dll_699_func_BB0
#define dll_699_func_BBC __dll699_dll_699_func_BBC
#define dll_699_func_BD4 __dll699_dll_699_func_BD4
#define dll_699_func_BE4 __dll699_dll_699_func_BE4
#define dll_699_func_BF4 __dll699_dll_699_func_BF4
#define dll_699_func_C08 __dll699_dll_699_func_C08
#define _rodata_0 __dll699__rodata_0
#define _data_0 __dll699__data_0
#define _data_C __dll699__data_C
#define _bss_0 __dll699__bss_0
#define _bss_8 __dll699__bss_8
#define _bss_C __dll699__bss_C
#define _bss_10 __dll699__bss_10
#define _bss_14 __dll699__bss_14

#endif //_DLL_699_RECOMP_H
