// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_699_RECOMP_H
#define _DLL_699_RECOMP_H

#define dll_699_ctor __dll699_dll_699_ctor
#define dll_699_dtor __dll699_dll_699_dtor
#define dll_699_setup __dll699_dll_699_setup
#define dll_699_control __dll699_dll_699_control
#define dll_699_update __dll699_dll_699_update
#define dll_699_print __dll699_dll_699_print
#define dll_699_free __dll699_dll_699_free
#define dll_699_get_model_flags __dll699_dll_699_get_model_flags
#define dll_699_get_data_size __dll699_dll_699_get_data_size
#define dll_699_func_C08 __dll699_dll_699_func_C08
#define _rodata_0 __dll699__rodata_0
#define _data_0 __dll699__data_0
#define _data_C __dll699__data_C
#define _bss_0 __dll699__bss_0
#define _bss_8 __dll699__bss_8
#define _bss_C __dll699__bss_C
#define _bss_10 __dll699__bss_10
#define _bss_14 __dll699__bss_14

#endif //_DLL_699_RECOMP_H
