// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_699_RECOMP_H
#define _DLL_699_RECOMP_H

#define dll_699_ctor __dll699_dll_699_ctor
#define dll_699_dtor __dll699_dll_699_dtor
#define dll_699_obj_Setup __dll699_dll_699_obj_Setup
#define dll_699_obj_Control __dll699_dll_699_obj_Control
#define dll_699_obj_Update __dll699_dll_699_obj_Update
#define dll_699_obj_Print __dll699_dll_699_obj_Print
#define dll_699_obj_Free __dll699_dll_699_obj_Free
#define dll_699_obj_GetModelFlags __dll699_dll_699_obj_GetModelFlags
#define dll_699_obj_GetDataSize __dll699_dll_699_obj_GetDataSize
#define dll_699_func_C08 __dll699_dll_699_func_C08
#define rodata_0 __dll699_rodata_0
#define data_0 __dll699_data_0
#define data_C __dll699_data_C
#define bss_0 __dll699_bss_0
#define bss_8 __dll699_bss_8
#define bss_C __dll699_bss_C
#define bss_10 __dll699_bss_10
#define bss_14 __dll699_bss_14

#endif //_DLL_699_RECOMP_H
