// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_69_RECOMP_H
#define _DLL_69_RECOMP_H

#define dll_69_ctor __dll69_dll_69_ctor
#define dll_69_dtor __dll69_dll_69_dtor
#define dll_69_func_18 __dll69_dll_69_func_18
#define dll_69_func_24 __dll69_dll_69_func_24
#define dll_69_func_2C __dll69_dll_69_func_2C

#endif //_DLL_69_RECOMP_H
