// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_700_RECOMP_H
#define _DLL_700_RECOMP_H

#define dll_700_ctor __dll700_dll_700_ctor
#define dll_700_dtor __dll700_dll_700_dtor
#define dll_700_create __dll700_dll_700_create
#define dll_700_update __dll700_dll_700_update
#define dll_700_func_BC __dll700_dll_700_func_BC
#define dll_700_draw __dll700_dll_700_draw
#define dll_700_destroy __dll700_dll_700_destroy
#define dll_700_get_setup_flags __dll700_dll_700_get_setup_flags
#define dll_700_get_state_size __dll700_dll_700_get_state_size
#define _oob_rodata_0 __dll700__oob_rodata_0

#endif //_DLL_700_RECOMP_H
