// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_708_RECOMP_H
#define _DLL_708_RECOMP_H

#define dll_708_func_0 __dll708_dll_708_func_0
#define dll_708_ctor __dll708_dll_708_ctor
#define dll_708_dtor __dll708_dll_708_dtor
#define dll_708_func_9C __dll708_dll_708_func_9C
#define dll_708_func_1FC __dll708_dll_708_func_1FC
#define dll_708_func_290 __dll708_dll_708_func_290
#define dll_708_func_988 __dll708_dll_708_func_988
#define dll_708_func_994 __dll708_dll_708_func_994
#define dll_708_func_9F4 __dll708_dll_708_func_9F4
#define dll_708_func_A98 __dll708_dll_708_func_A98
#define dll_708_func_AA8 __dll708_dll_708_func_AA8
#define dll_708_func_ABC __dll708_dll_708_func_ABC
#define dll_708_func_FDC __dll708_dll_708_func_FDC
#define dll_708_func_10B4 __dll708_dll_708_func_10B4
#define dll_708_func_12DC __dll708_dll_708_func_12DC
#define dll_708_func_1388 __dll708_dll_708_func_1388
#define _rodata_0 __dll708__rodata_0
#define _rodata_4 __dll708__rodata_4
#define _rodata_8 __dll708__rodata_8
#define _rodata_C __dll708__rodata_C
#define _rodata_10 __dll708__rodata_10
#define _rodata_14 __dll708__rodata_14
#define _rodata_18 __dll708__rodata_18
#define _data_0 __dll708__data_0
#define _data_1C __dll708__data_1C
#define _bss_0 __dll708__bss_0
#define _bss_C __dll708__bss_C

#endif //_DLL_708_RECOMP_H
