// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_71_RECOMP_H
#define _DLL_71_RECOMP_H

#define dll_71_ctor __dll71_dll_71_ctor
#define dll_71_dtor __dll71_dll_71_dtor
#define dll_71_func_34 __dll71_dll_71_func_34
#define dll_71_func_40 __dll71_dll_71_func_40
#define dll_71_func_48 __dll71_dll_71_func_48
#define str_0 __dll71_str_0
#define str_C __dll71_str_C
#define str_14 __dll71_str_14
#define _bss_0 __dll71__bss_0
#define _bss_4 __dll71__bss_4

#endif //_DLL_71_RECOMP_H
