// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_725_RECOMP_H
#define _DLL_725_RECOMP_H

#define dll_725_ctor __dll725_dll_725_ctor
#define dll_725_dtor __dll725_dll_725_dtor
#define dll_725_func_18 __dll725_dll_725_func_18
#define dll_725_func_E0 __dll725_dll_725_func_E0
#define dll_725_func_2A4 __dll725_dll_725_func_2A4
#define dll_725_func_2B0 __dll725_dll_725_func_2B0
#define dll_725_func_2F0 __dll725_dll_725_func_2F0
#define dll_725_func_330 __dll725_dll_725_func_330
#define dll_725_func_340 __dll725_dll_725_func_340
#define dll_725_func_354 __dll725_dll_725_func_354
#define dll_725_func_3A4 __dll725_dll_725_func_3A4
#define dll_725_func_3BC __dll725_dll_725_func_3BC
#define dll_725_func_3D4 __dll725_dll_725_func_3D4
#define _data_0 __dll725__data_0
#define _data_8 __dll725__data_8
#define _data_10 __dll725__data_10

#endif //_DLL_725_RECOMP_H
