// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_726_RECOMP_H
#define _DLL_726_RECOMP_H

#define dll_726_ctor __dll726_dll_726_ctor
#define dll_726_dtor __dll726_dll_726_dtor
#define dll_726_setup __dll726_dll_726_setup
#define dll_726_control __dll726_dll_726_control
#define dll_726_update __dll726_dll_726_update
#define dll_726_print __dll726_dll_726_print
#define dll_726_free __dll726_dll_726_free
#define dll_726_get_model_flags __dll726_dll_726_get_model_flags
#define dll_726_get_data_size __dll726_dll_726_get_data_size
#define dll_726_func_364 __dll726_dll_726_func_364
#define dll_726_func_3F8 __dll726_dll_726_func_3F8
#define dll_726_func_410 __dll726_dll_726_func_410
#define dll_726_func_4F4 __dll726_dll_726_func_4F4
#define dll_726_func_504 __dll726_dll_726_func_504
#define str_0 __dll726_str_0
#define str_40 __dll726_str_40

#endif //_DLL_726_RECOMP_H
