// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_737_RECOMP_H
#define _DLL_737_RECOMP_H

#define dll_737_ctor __dll737_dll_737_ctor
#define dll_737_dtor __dll737_dll_737_dtor
#define dll_737_func_18 __dll737_dll_737_func_18
#define dll_737_func_130 __dll737_dll_737_func_130
#define dll_737_func_170 __dll737_dll_737_func_170
#define dll_737_func_1D8 __dll737_dll_737_func_1D8
#define dll_737_func_1F0 __dll737_dll_737_func_1F0
#define dll_737_func_270 __dll737_dll_737_func_270
#define dll_737_func_280 __dll737_dll_737_func_280
#define dll_737_func_294 __dll737_dll_737_func_294
#define dll_737_func_47C __dll737_dll_737_func_47C
#define dll_737_func_604 __dll737_dll_737_func_604
#define dll_737_func_720 __dll737_dll_737_func_720
#define str_0 __dll737_str_0
#define _data_0 __dll737__data_0
#define _data_8 __dll737__data_8
#define _data_10 __dll737__data_10
#define _data_1C __dll737__data_1C

#endif //_DLL_737_RECOMP_H
