// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_738_RECOMP_H
#define _DLL_738_RECOMP_H

#define dll_738_ctor __dll738_dll_738_ctor
#define dll_738_dtor __dll738_dll_738_dtor
#define dll_738_setup __dll738_dll_738_setup
#define dll_738_control __dll738_dll_738_control
#define dll_738_update __dll738_dll_738_update
#define dll_738_print __dll738_dll_738_print
#define dll_738_free __dll738_dll_738_free
#define dll_738_get_model_flags __dll738_dll_738_get_model_flags
#define dll_738_get_data_size __dll738_dll_738_get_data_size
#define str_0 __dll738_str_0
#define str_8 __dll738_str_8
#define str_14 __dll738_str_14
#define str_58 __dll738_str_58
#define rodata_78 __dll738_rodata_78
#define rodata_7C __dll738_rodata_7C
#define data_0 __dll738_data_0
#define data_10 __dll738_data_10

#endif //_DLL_738_RECOMP_H
