// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_738_RECOMP_H
#define _DLL_738_RECOMP_H

#define dll_738_ctor __dll738_dll_738_ctor
#define dll_738_dtor __dll738_dll_738_dtor
#define dll_738_obj_Setup __dll738_dll_738_obj_Setup
#define dll_738_obj_Control __dll738_dll_738_obj_Control
#define dll_738_obj_Update __dll738_dll_738_obj_Update
#define dll_738_obj_Print __dll738_dll_738_obj_Print
#define dll_738_obj_Free __dll738_dll_738_obj_Free
#define dll_738_obj_GetModelFlags __dll738_dll_738_obj_GetModelFlags
#define dll_738_obj_GetDataSize __dll738_dll_738_obj_GetDataSize
#define str_0 __dll738_str_0
#define str_8 __dll738_str_8
#define str_14 __dll738_str_14
#define str_58 __dll738_str_58
#define rodata_78 __dll738_rodata_78
#define rodata_7C __dll738_rodata_7C
#define data_0 __dll738_data_0
#define data_10 __dll738_data_10

#endif //_DLL_738_RECOMP_H
