// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_738_RECOMP_H
#define _DLL_738_RECOMP_H

#define dll_738_ctor __dll738_dll_738_ctor
#define dll_738_dtor __dll738_dll_738_dtor
#define dll_738_create __dll738_dll_738_create
#define dll_738_update __dll738_dll_738_update
#define dll_738_func_74C __dll738_dll_738_func_74C
#define dll_738_draw __dll738_dll_738_draw
#define dll_738_destroy __dll738_dll_738_destroy
#define dll_738_get_model_flags __dll738_dll_738_get_model_flags
#define dll_738_get_state_size __dll738_dll_738_get_state_size
#define str_0 __dll738_str_0
#define str_8 __dll738_str_8
#define str_14 __dll738_str_14
#define str_58 __dll738_str_58
#define _rodata_78 __dll738__rodata_78
#define _rodata_7C __dll738__rodata_7C
#define _data_0 __dll738__data_0
#define _data_10 __dll738__data_10

#endif //_DLL_738_RECOMP_H
