// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_739_RECOMP_H
#define _DLL_739_RECOMP_H

#define dll_739_ctor __dll739_dll_739_ctor
#define dll_739_dtor __dll739_dll_739_dtor
#define dll_739_setup __dll739_dll_739_setup
#define dll_739_control __dll739_dll_739_control
#define dll_739_update __dll739_dll_739_update
#define dll_739_print __dll739_dll_739_print
#define dll_739_free __dll739_dll_739_free
#define dll_739_get_model_flags __dll739_dll_739_get_model_flags
#define dll_739_get_data_size __dll739_dll_739_get_data_size
#define dll_739_func_7B4 __dll739_dll_739_func_7B4
#define dll_739_func_9C8 __dll739_dll_739_func_9C8
#define dll_739_func_B04 __dll739_dll_739_func_B04
#define dll_739_func_D78 __dll739_dll_739_func_D78
#define str_0 __dll739_str_0
#define rodata_74 __dll739_rodata_74
#define rodata_78 __dll739_rodata_78
#define rodata_7C __dll739_rodata_7C
#define rodata_80 __dll739_rodata_80
#define rodata_84 __dll739_rodata_84
#define rodata_88 __dll739_rodata_88
#define data_0 __dll739_data_0
#define data_8 __dll739_data_8
#define data_10 __dll739_data_10
#define data_18 __dll739_data_18
#define data_24 __dll739_data_24
#define data_30 __dll739_data_30
#define data_38 __dll739_data_38

#endif //_DLL_739_RECOMP_H
