// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_739_RECOMP_H
#define _DLL_739_RECOMP_H

#define dll_739_ctor __dll739_dll_739_ctor
#define dll_739_dtor __dll739_dll_739_dtor
#define dll_739_func_18 __dll739_dll_739_func_18
#define dll_739_func_290 __dll739_dll_739_func_290
#define dll_739_func_68C __dll739_dll_739_func_68C
#define dll_739_func_698 __dll739_dll_739_func_698
#define dll_739_func_71C __dll739_dll_739_func_71C
#define dll_739_func_790 __dll739_dll_739_func_790
#define dll_739_func_7A0 __dll739_dll_739_func_7A0
#define dll_739_func_7B4 __dll739_dll_739_func_7B4
#define dll_739_func_9C8 __dll739_dll_739_func_9C8
#define dll_739_func_B04 __dll739_dll_739_func_B04
#define dll_739_func_D78 __dll739_dll_739_func_D78
#define str_0 __dll739_str_0
#define _rodata_74 __dll739__rodata_74
#define _rodata_78 __dll739__rodata_78
#define _rodata_7C __dll739__rodata_7C
#define _rodata_80 __dll739__rodata_80
#define _rodata_84 __dll739__rodata_84
#define _rodata_88 __dll739__rodata_88
#define _data_0 __dll739__data_0
#define _data_8 __dll739__data_8
#define _data_10 __dll739__data_10
#define _data_18 __dll739__data_18
#define _data_24 __dll739__data_24
#define _data_30 __dll739__data_30
#define _data_38 __dll739__data_38

#endif //_DLL_739_RECOMP_H
