// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_73_RECOMP_H
#define _DLL_73_RECOMP_H

#define dll_73_ctor __dll73_dll_73_ctor
#define dll_73_dtor __dll73_dll_73_dtor
#define dll_73_func_6C __dll73_dll_73_func_6C
#define dll_73_func_118 __dll73_dll_73_func_118
#define dll_73_func_204 __dll73_dll_73_func_204
#define dll_73_func_46C __dll73_dll_73_func_46C
#define dll_73_func_540 __dll73_dll_73_func_540
#define dll_73_func_55C __dll73_dll_73_func_55C
#define dll_73_func_6D0 __dll73_dll_73_func_6D0
#define dll_73_func_764 __dll73_dll_73_func_764
#define dll_73_func_780 __dll73_dll_73_func_780
#define _data_0 __dll73__data_0
#define _bss_0 __dll73__bss_0
#define _bss_1 __dll73__bss_1
#define _bss_2 __dll73__bss_2
#define _bss_4 __dll73__bss_4
#define _bss_8 __dll73__bss_8

#endif //_DLL_73_RECOMP_H
