// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_741_RECOMP_H
#define _DLL_741_RECOMP_H

#define dll_741_ctor __dll741_dll_741_ctor
#define dll_741_dtor __dll741_dll_741_dtor
#define dll_741_create __dll741_dll_741_create
#define dll_741_update __dll741_dll_741_update
#define dll_741_func_144 __dll741_dll_741_func_144
#define dll_741_draw __dll741_dll_741_draw
#define dll_741_destroy __dll741_dll_741_destroy
#define dll_741_get_model_flags __dll741_dll_741_get_model_flags
#define dll_741_get_state_size __dll741_dll_741_get_state_size
#define dll_741_func_1D8 __dll741_dll_741_func_1D8
#define str_0 __dll741_str_0

#endif //_DLL_741_RECOMP_H
