// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_742_RECOMP_H
#define _DLL_742_RECOMP_H

#define dll_742_ctor __dll742_dll_742_ctor
#define dll_742_dtor __dll742_dll_742_dtor
#define dll_742_func_18 __dll742_dll_742_func_18
#define dll_742_func_120 __dll742_dll_742_func_120
#define dll_742_func_244 __dll742_dll_742_func_244
#define dll_742_func_3EC __dll742_dll_742_func_3EC
#define dll_742_func_440 __dll742_dll_742_func_440
#define dll_742_func_450 __dll742_dll_742_func_450
#define dll_742_func_460 __dll742_dll_742_func_460
#define _data_0 __dll742__data_0
#define _data_8 __dll742__data_8

#endif //_DLL_742_RECOMP_H
