// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_743_RECOMP_H
#define _DLL_743_RECOMP_H

#define dll_743_ctor __dll743_dll_743_ctor
#define dll_743_dtor __dll743_dll_743_dtor
#define dll_743_obj_Setup __dll743_dll_743_obj_Setup
#define dll_743_obj_Control __dll743_dll_743_obj_Control
#define dll_743_obj_Update __dll743_dll_743_obj_Update
#define dll_743_obj_Print __dll743_dll_743_obj_Print
#define dll_743_obj_Free __dll743_dll_743_obj_Free
#define dll_743_obj_GetModelFlags __dll743_dll_743_obj_GetModelFlags
#define dll_743_obj_GetDataSize __dll743_dll_743_obj_GetDataSize
#define str_0 __dll743_str_0
#define data_0 __dll743_data_0

#endif //_DLL_743_RECOMP_H
