// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_745_RECOMP_H
#define _DLL_745_RECOMP_H

#define dll_745_ctor __dll745_dll_745_ctor
#define dll_745_dtor __dll745_dll_745_dtor
#define dll_745_func_18 __dll745_dll_745_func_18
#define dll_745_func_108 __dll745_dll_745_func_108
#define dll_745_func_930 __dll745_dll_745_func_930
#define dll_745_func_AE8 __dll745_dll_745_func_AE8
#define dll_745_func_C1C __dll745_dll_745_func_C1C
#define dll_745_func_C88 __dll745_dll_745_func_C88
#define dll_745_func_C98 __dll745_dll_745_func_C98
#define dll_745_func_CAC __dll745_dll_745_func_CAC
#define dll_745_func_DEC __dll745_dll_745_func_DEC
#define str_0 __dll745_str_0
#define str_54 __dll745_str_54
#define _rodata_64 __dll745__rodata_64
#define _rodata_68 __dll745__rodata_68
#define _rodata_6C __dll745__rodata_6C
#define _rodata_70 __dll745__rodata_70
#define _rodata_74 __dll745__rodata_74
#define _data_0 __dll745__data_0

#endif //_DLL_745_RECOMP_H
