// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_746_RECOMP_H
#define _DLL_746_RECOMP_H

#define dll_746_ctor __dll746_dll_746_ctor
#define dll_746_dtor __dll746_dll_746_dtor
#define dll_746_setup __dll746_dll_746_setup
#define dll_746_control __dll746_dll_746_control
#define dll_746_update __dll746_dll_746_update
#define dll_746_print __dll746_dll_746_print
#define dll_746_free __dll746_dll_746_free
#define dll_746_get_model_flags __dll746_dll_746_get_model_flags
#define dll_746_get_data_size __dll746_dll_746_get_data_size
#define dll_746_func_648 __dll746_dll_746_func_648
#define _rodata_0 __dll746__rodata_0

#endif //_DLL_746_RECOMP_H
