// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_748_RECOMP_H
#define _DLL_748_RECOMP_H

#define dll_748_ctor __dll748_dll_748_ctor
#define dll_748_dtor __dll748_dll_748_dtor
#define dll_748_create __dll748_dll_748_create
#define dll_748_update __dll748_dll_748_update
#define dll_748_func_440 __dll748_dll_748_func_440
#define dll_748_draw __dll748_dll_748_draw
#define dll_748_destroy __dll748_dll_748_destroy
#define dll_748_get_model_flags __dll748_dll_748_get_model_flags
#define dll_748_get_state_size __dll748_dll_748_get_state_size
#define str_0 __dll748_str_0
#define _data_0 __dll748__data_0
#define _data_8 __dll748__data_8
#define _data_18 __dll748__data_18
#define _data_1C __dll748__data_1C
#define _data_20 __dll748__data_20

#endif //_DLL_748_RECOMP_H
