// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_748_RECOMP_H
#define _DLL_748_RECOMP_H

#define dll_748_ctor __dll748_dll_748_ctor
#define dll_748_dtor __dll748_dll_748_dtor
#define dll_748_func_18 __dll748_dll_748_func_18
#define dll_748_func_AC __dll748_dll_748_func_AC
#define dll_748_func_440 __dll748_dll_748_func_440
#define dll_748_func_5CC __dll748_dll_748_func_5CC
#define dll_748_func_5E4 __dll748_dll_748_func_5E4
#define dll_748_func_5F4 __dll748_dll_748_func_5F4
#define dll_748_func_604 __dll748_dll_748_func_604
#define str_0 __dll748_str_0
#define _data_0 __dll748__data_0
#define _data_8 __dll748__data_8
#define _data_18 __dll748__data_18
#define _data_1C __dll748__data_1C
#define _data_20 __dll748__data_20

#endif //_DLL_748_RECOMP_H
