// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_751_RECOMP_H
#define _DLL_751_RECOMP_H

#define dll_751_ctor __dll751_dll_751_ctor
#define dll_751_dtor __dll751_dll_751_dtor
#define dll_751_setup __dll751_dll_751_setup
#define dll_751_control __dll751_dll_751_control
#define dll_751_update __dll751_dll_751_update
#define dll_751_print __dll751_dll_751_print
#define dll_751_free __dll751_dll_751_free
#define dll_751_get_model_flags __dll751_dll_751_get_model_flags
#define dll_751_get_data_size __dll751_dll_751_get_data_size
#define rodata_0 __dll751_rodata_0
#define rodata_4 __dll751_rodata_4

#endif //_DLL_751_RECOMP_H
