// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_751_RECOMP_H
#define _DLL_751_RECOMP_H

#define dll_751_ctor __dll751_dll_751_ctor
#define dll_751_dtor __dll751_dll_751_dtor
#define dll_751_create __dll751_dll_751_create
#define dll_751_update __dll751_dll_751_update
#define dll_751_func_7D4 __dll751_dll_751_func_7D4
#define dll_751_draw __dll751_dll_751_draw
#define dll_751_destroy __dll751_dll_751_destroy
#define dll_751_get_setup_flags __dll751_dll_751_get_setup_flags
#define dll_751_get_state_size __dll751_dll_751_get_state_size
#define _rodata_0 __dll751__rodata_0
#define _rodata_4 __dll751__rodata_4

#endif //_DLL_751_RECOMP_H
