// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_753_RECOMP_H
#define _DLL_753_RECOMP_H

#define dll_753_ctor __dll753_dll_753_ctor
#define dll_753_dtor __dll753_dll_753_dtor
#define dll_753_setup __dll753_dll_753_setup
#define dll_753_control __dll753_dll_753_control
#define dll_753_update __dll753_dll_753_update
#define dll_753_print __dll753_dll_753_print
#define dll_753_free __dll753_dll_753_free
#define dll_753_get_model_flags __dll753_dll_753_get_model_flags
#define dll_753_get_data_size __dll753_dll_753_get_data_size
#define str_0 __dll753_str_0
#define str_10 __dll753_str_10
#define str_1C __dll753_str_1C
#define str_24 __dll753_str_24
#define _rodata_38 __dll753__rodata_38
#define _rodata_3C __dll753__rodata_3C
#define _rodata_40 __dll753__rodata_40
#define _rodata_44 __dll753__rodata_44
#define _rodata_48 __dll753__rodata_48
#define _data_0 __dll753__data_0
#define _data_8 __dll753__data_8
#define _data_14 __dll753__data_14
#define _data_24 __dll753__data_24

#endif //_DLL_753_RECOMP_H
