// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_755_RECOMP_H
#define _DLL_755_RECOMP_H

#define dll_755_ctor __dll755_dll_755_ctor
#define dll_755_dtor __dll755_dll_755_dtor
#define dll_755_func_18 __dll755_dll_755_func_18
#define dll_755_func_1C8 __dll755_dll_755_func_1C8
#define dll_755_func_348 __dll755_dll_755_func_348
#define dll_755_func_354 __dll755_dll_755_func_354
#define dll_755_func_3A8 __dll755_dll_755_func_3A8
#define dll_755_func_3B8 __dll755_dll_755_func_3B8
#define dll_755_func_3C8 __dll755_dll_755_func_3C8
#define dll_755_func_3DC __dll755_dll_755_func_3DC
#define str_0 __dll755_str_0
#define str_18 __dll755_str_18

#endif //_DLL_755_RECOMP_H
