// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_757_RECOMP_H
#define _DLL_757_RECOMP_H

#define dll_757_ctor __dll757_dll_757_ctor
#define dll_757_dtor __dll757_dll_757_dtor
#define dll_757_func_18 __dll757_dll_757_func_18
#define dll_757_func_B4 __dll757_dll_757_func_B4
#define dll_757_func_224 __dll757_dll_757_func_224
#define dll_757_func_230 __dll757_dll_757_func_230
#define dll_757_func_248 __dll757_dll_757_func_248
#define dll_757_func_258 __dll757_dll_757_func_258
#define dll_757_func_268 __dll757_dll_757_func_268
#define dll_757_func_27C __dll757_dll_757_func_27C
#define dll_757_func_33C __dll757_dll_757_func_33C
#define str_0 __dll757_str_0

#endif //_DLL_757_RECOMP_H
