// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_760_RECOMP_H
#define _DLL_760_RECOMP_H

#define dll_760_ctor __dll760_dll_760_ctor
#define dll_760_dtor __dll760_dll_760_dtor
#define dll_760_obj_Setup __dll760_dll_760_obj_Setup
#define dll_760_obj_Control __dll760_dll_760_obj_Control
#define dll_760_obj_Update __dll760_dll_760_obj_Update
#define dll_760_obj_Print __dll760_dll_760_obj_Print
#define dll_760_obj_Free __dll760_dll_760_obj_Free
#define dll_760_obj_GetModelFlags __dll760_dll_760_obj_GetModelFlags
#define dll_760_obj_GetDataSize __dll760_dll_760_obj_GetDataSize
#define dll_760_func_2FC __dll760_dll_760_func_2FC
#define str_0 __dll760_str_0
#define rodata_C __dll760_rodata_C
#define rodata_10 __dll760_rodata_10
#define rodata_14 __dll760_rodata_14
#define rodata_18 __dll760_rodata_18

#endif //_DLL_760_RECOMP_H
