// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_760_RECOMP_H
#define _DLL_760_RECOMP_H

#define dll_760_ctor __dll760_dll_760_ctor
#define dll_760_dtor __dll760_dll_760_dtor
#define dll_760_setup __dll760_dll_760_setup
#define dll_760_control __dll760_dll_760_control
#define dll_760_update __dll760_dll_760_update
#define dll_760_print __dll760_dll_760_print
#define dll_760_free __dll760_dll_760_free
#define dll_760_get_model_flags __dll760_dll_760_get_model_flags
#define dll_760_get_data_size __dll760_dll_760_get_data_size
#define dll_760_func_2FC __dll760_dll_760_func_2FC
#define str_0 __dll760_str_0
#define _rodata_C __dll760__rodata_C
#define _rodata_10 __dll760__rodata_10
#define _rodata_14 __dll760__rodata_14
#define _rodata_18 __dll760__rodata_18

#endif //_DLL_760_RECOMP_H
