// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_761_RECOMP_H
#define _DLL_761_RECOMP_H

#define dll_761_ctor __dll761_dll_761_ctor
#define dll_761_dtor __dll761_dll_761_dtor
#define dll_761_func_18 __dll761_dll_761_func_18
#define dll_761_func_17C __dll761_dll_761_func_17C
#define dll_761_func_25C __dll761_dll_761_func_25C
#define dll_761_func_268 __dll761_dll_761_func_268
#define dll_761_func_2BC __dll761_dll_761_func_2BC
#define dll_761_func_2CC __dll761_dll_761_func_2CC
#define dll_761_func_2DC __dll761_dll_761_func_2DC
#define dll_761_func_2F0 __dll761_dll_761_func_2F0
#define dll_761_func_590 __dll761_dll_761_func_590

#endif //_DLL_761_RECOMP_H
