// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_763_RECOMP_H
#define _DLL_763_RECOMP_H

#define dll_763_ctor __dll763_dll_763_ctor
#define dll_763_dtor __dll763_dll_763_dtor
#define dll_763_func_18 __dll763_dll_763_func_18
#define dll_763_func_DC __dll763_dll_763_func_DC
#define dll_763_func_258 __dll763_dll_763_func_258
#define dll_763_func_264 __dll763_dll_763_func_264
#define dll_763_func_550 __dll763_dll_763_func_550
#define dll_763_func_604 __dll763_dll_763_func_604
#define dll_763_func_614 __dll763_dll_763_func_614
#define _data_0 __dll763__data_0

#endif //_DLL_763_RECOMP_H
