// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_765_RECOMP_H
#define _DLL_765_RECOMP_H

#define dll_765_ctor __dll765_dll_765_ctor
#define dll_765_dtor __dll765_dll_765_dtor
#define dll_765_create __dll765_dll_765_create
#define dll_765_update __dll765_dll_765_update
#define dll_765_func_88 __dll765_dll_765_func_88
#define dll_765_draw __dll765_dll_765_draw
#define dll_765_destroy __dll765_dll_765_destroy
#define dll_765_get_setup_flags __dll765_dll_765_get_setup_flags
#define dll_765_get_state_size __dll765_dll_765_get_state_size
#define dll_765_func_144 __dll765_dll_765_func_144
#define dll_765_func_224 __dll765_dll_765_func_224
#define str_0 __dll765_str_0

#endif //_DLL_765_RECOMP_H
