// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_765_RECOMP_H
#define _DLL_765_RECOMP_H

#define dll_765_ctor __dll765_dll_765_ctor
#define dll_765_dtor __dll765_dll_765_dtor
#define dll_765_setup __dll765_dll_765_setup
#define dll_765_control __dll765_dll_765_control
#define dll_765_update __dll765_dll_765_update
#define dll_765_print __dll765_dll_765_print
#define dll_765_free __dll765_dll_765_free
#define dll_765_get_model_flags __dll765_dll_765_get_model_flags
#define dll_765_get_data_size __dll765_dll_765_get_data_size
#define dll_765_func_144 __dll765_dll_765_func_144
#define dll_765_func_224 __dll765_dll_765_func_224
#define str_0 __dll765_str_0

#endif //_DLL_765_RECOMP_H
