// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_767_RECOMP_H
#define _DLL_767_RECOMP_H

#define dll_767_ctor __dll767_dll_767_ctor
#define dll_767_dtor __dll767_dll_767_dtor
#define dll_767_func_18 __dll767_dll_767_func_18
#define dll_767_func_84 __dll767_dll_767_func_84
#define dll_767_func_350 __dll767_dll_767_func_350
#define dll_767_func_35C __dll767_dll_767_func_35C
#define dll_767_func_440 __dll767_dll_767_func_440
#define dll_767_func_450 __dll767_dll_767_func_450
#define dll_767_func_468 __dll767_dll_767_func_468
#define dll_767_func_47C __dll767_dll_767_func_47C
#define dll_767_func_4AC __dll767_dll_767_func_4AC
#define _rodata_0 __dll767__rodata_0

#endif //_DLL_767_RECOMP_H
