// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_76_RECOMP_H
#define _DLL_76_RECOMP_H

#define dll_76_ctor __dll76_dll_76_ctor
#define dll_76_dtor __dll76_dll_76_dtor
#define dll_76_func_148 __dll76_dll_76_func_148
#define dll_76_func_DA4 __dll76_dll_76_func_DA4
#define dll_76_func_18A8 __dll76_dll_76_func_18A8
#define rodata_0 __dll76_rodata_0
#define rodata_4 __dll76_rodata_4
#define rodata_8 __dll76_rodata_8
#define rodata_C __dll76_rodata_C
#define data_0 __dll76_data_0
#define data_A4 __dll76_data_A4
#define data_148 __dll76_data_148
#define data_1EC __dll76_data_1EC
#define data_2AC __dll76_data_2AC
#define data_2B0 __dll76_data_2B0
#define data_2B4 __dll76_data_2B4
#define data_2C0 __dll76_data_2C0
#define bss_0 __dll76_bss_0
#define bss_8 __dll76_bss_8
#define bss_28 __dll76_bss_28

#endif //_DLL_76_RECOMP_H
