// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_771_RECOMP_H
#define _DLL_771_RECOMP_H

#define dll_771_ctor __dll771_dll_771_ctor
#define dll_771_dtor __dll771_dll_771_dtor
#define dll_771_obj_Setup __dll771_dll_771_obj_Setup
#define dll_771_obj_Control __dll771_dll_771_obj_Control
#define dll_771_obj_Update __dll771_dll_771_obj_Update
#define dll_771_obj_Print __dll771_dll_771_obj_Print
#define dll_771_obj_Free __dll771_dll_771_obj_Free
#define dll_771_obj_GetModelFlags __dll771_dll_771_obj_GetModelFlags
#define dll_771_obj_GetDataSize __dll771_dll_771_obj_GetDataSize
#define dll_771_func_6BC __dll771_dll_771_func_6BC
#define dll_771_func_7DC __dll771_dll_771_func_7DC
#define rodata_0 __dll771_rodata_0
#define rodata_20 __dll771_rodata_20
#define rodata_24 __dll771_rodata_24
#define rodata_28 __dll771_rodata_28
#define rodata_2C __dll771_rodata_2C
#define rodata_30 __dll771_rodata_30
#define rodata_34 __dll771_rodata_34
#define rodata_38 __dll771_rodata_38
#define rodata_3C __dll771_rodata_3C
#define rodata_40 __dll771_rodata_40
#define rodata_44 __dll771_rodata_44
#define rodata_48 __dll771_rodata_48
#define data_0 __dll771_data_0
#define data_4 __dll771_data_4

#endif //_DLL_771_RECOMP_H
