// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_773_RECOMP_H
#define _DLL_773_RECOMP_H

#define dll_773_func_0 __dll773_dll_773_func_0
#define dll_773_ctor __dll773_dll_773_ctor
#define dll_773_dtor __dll773_dll_773_dtor
#define dll_773_func_AC __dll773_dll_773_func_AC
#define dll_773_func_188 __dll773_dll_773_func_188
#define dll_773_func_290 __dll773_dll_773_func_290
#define dll_773_func_29C __dll773_dll_773_func_29C
#define dll_773_func_324 __dll773_dll_773_func_324
#define dll_773_func_334 __dll773_dll_773_func_334
#define dll_773_func_344 __dll773_dll_773_func_344
#define dll_773_func_358 __dll773_dll_773_func_358
#define dll_773_func_434 __dll773_dll_773_func_434
#define dll_773_func_44C __dll773_dll_773_func_44C
#define dll_773_func_4B8 __dll773_dll_773_func_4B8
#define dll_773_func_4D0 __dll773_dll_773_func_4D0
#define dll_773_func_564 __dll773_dll_773_func_564
#define _rodata_0 __dll773__rodata_0
#define _data_0 __dll773__data_0
#define _data_4 __dll773__data_4
#define _bss_0 __dll773__bss_0
#define _bss_8 __dll773__bss_8

#endif //_DLL_773_RECOMP_H
