// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_781_RECOMP_H
#define _DLL_781_RECOMP_H

#define dll_781_ctor __dll781_dll_781_ctor
#define dll_781_dtor __dll781_dll_781_dtor
#define dll_781_func_18 __dll781_dll_781_func_18
#define dll_781_func_150 __dll781_dll_781_func_150
#define dll_781_func_4B4 __dll781_dll_781_func_4B4
#define dll_781_func_4C0 __dll781_dll_781_func_4C0
#define dll_781_func_514 __dll781_dll_781_func_514
#define dll_781_func_594 __dll781_dll_781_func_594
#define dll_781_func_5C8 __dll781_dll_781_func_5C8
#define dll_781_func_5DC __dll781_dll_781_func_5DC
#define dll_781_func_648 __dll781_dll_781_func_648
#define dll_781_func_6CC __dll781_dll_781_func_6CC
#define str_0 __dll781_str_0
#define str_34 __dll781_str_34
#define _rodata_44 __dll781__rodata_44
#define _rodata_48 __dll781__rodata_48

#endif //_DLL_781_RECOMP_H
