// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_782_RECOMP_H
#define _DLL_782_RECOMP_H

#define dll_782_ctor __dll782_dll_782_ctor
#define dll_782_dtor __dll782_dll_782_dtor
#define dll_782_func_18 __dll782_dll_782_func_18
#define dll_782_func_58 __dll782_dll_782_func_58
#define dll_782_func_F38 __dll782_dll_782_func_F38
#define dll_782_func_F44 __dll782_dll_782_func_F44
#define dll_782_func_F98 __dll782_dll_782_func_F98
#define dll_782_func_FA8 __dll782_dll_782_func_FA8
#define dll_782_func_FDC __dll782_dll_782_func_FDC
#define dll_782_func_FF0 __dll782_dll_782_func_FF0
#define _rodata_0 __dll782__rodata_0
#define _rodata_20 __dll782__rodata_20
#define _rodata_24 __dll782__rodata_24
#define _rodata_28 __dll782__rodata_28
#define _rodata_2C __dll782__rodata_2C

#endif //_DLL_782_RECOMP_H
