// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_785_RECOMP_H
#define _DLL_785_RECOMP_H

#define dll_785_ctor __dll785_dll_785_ctor
#define dll_785_dtor __dll785_dll_785_dtor
#define dll_785_func_18 __dll785_dll_785_func_18
#define dll_785_func_148 __dll785_dll_785_func_148
#define dll_785_func_554 __dll785_dll_785_func_554
#define dll_785_func_5AC __dll785_dll_785_func_5AC
#define dll_785_func_600 __dll785_dll_785_func_600
#define dll_785_func_610 __dll785_dll_785_func_610
#define dll_785_func_620 __dll785_dll_785_func_620
#define dll_785_func_634 __dll785_dll_785_func_634
#define str_0 __dll785_str_0
#define _data_0 __dll785__data_0

#endif //_DLL_785_RECOMP_H
