// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_785_RECOMP_H
#define _DLL_785_RECOMP_H

#define dll_785_ctor __dll785_dll_785_ctor
#define dll_785_dtor __dll785_dll_785_dtor
#define dll_785_setup __dll785_dll_785_setup
#define dll_785_control __dll785_dll_785_control
#define dll_785_update __dll785_dll_785_update
#define dll_785_print __dll785_dll_785_print
#define dll_785_free __dll785_dll_785_free
#define dll_785_get_model_flags __dll785_dll_785_get_model_flags
#define dll_785_get_data_size __dll785_dll_785_get_data_size
#define dll_785_func_634 __dll785_dll_785_func_634
#define str_0 __dll785_str_0
#define _data_0 __dll785__data_0

#endif //_DLL_785_RECOMP_H
