// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_786_RECOMP_H
#define _DLL_786_RECOMP_H

#define dll_786_ctor __dll786_dll_786_ctor
#define dll_786_dtor __dll786_dll_786_dtor
#define dll_786_func_18 __dll786_dll_786_func_18
#define dll_786_func_30 __dll786_dll_786_func_30
#define dll_786_func_284 __dll786_dll_786_func_284
#define dll_786_func_290 __dll786_dll_786_func_290
#define dll_786_func_2E4 __dll786_dll_786_func_2E4
#define dll_786_func_2F4 __dll786_dll_786_func_2F4
#define dll_786_func_304 __dll786_dll_786_func_304
#define _oob_rodata_0 __dll786__oob_rodata_0

#endif //_DLL_786_RECOMP_H
