// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_787_RECOMP_H
#define _DLL_787_RECOMP_H

#define dll_787_ctor __dll787_dll_787_ctor
#define dll_787_dtor __dll787_dll_787_dtor
#define dll_787_func_18 __dll787_dll_787_func_18
#define dll_787_func_FC __dll787_dll_787_func_FC
#define dll_787_func_358 __dll787_dll_787_func_358
#define dll_787_func_364 __dll787_dll_787_func_364
#define dll_787_func_3E4 __dll787_dll_787_func_3E4
#define dll_787_func_3F4 __dll787_dll_787_func_3F4
#define dll_787_func_428 __dll787_dll_787_func_428
#define dll_787_func_43C __dll787_dll_787_func_43C
#define dll_787_func_490 __dll787_dll_787_func_490
#define str_0 __dll787_str_0

#endif //_DLL_787_RECOMP_H
