// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_790_RECOMP_H
#define _DLL_790_RECOMP_H

#define dll_790_ctor __dll790_dll_790_ctor
#define dll_790_dtor __dll790_dll_790_dtor
#define dll_790_setup __dll790_dll_790_setup
#define dll_790_control __dll790_dll_790_control
#define dll_790_update __dll790_dll_790_update
#define dll_790_print __dll790_dll_790_print
#define dll_790_free __dll790_dll_790_free
#define dll_790_get_model_flags __dll790_dll_790_get_model_flags
#define dll_790_get_data_size __dll790_dll_790_get_data_size
#define dll_790_func_500 __dll790_dll_790_func_500
#define dll_790_func_644 __dll790_dll_790_func_644
#define dll_790_func_7A4 __dll790_dll_790_func_7A4
#define _rodata_0 __dll790__rodata_0
#define _rodata_4 __dll790__rodata_4

#endif //_DLL_790_RECOMP_H
