// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_796_RECOMP_H
#define _DLL_796_RECOMP_H

#define dll_796_ctor __dll796_dll_796_ctor
#define dll_796_dtor __dll796_dll_796_dtor
#define dll_796_func_18 __dll796_dll_796_func_18
#define dll_796_func_B8 __dll796_dll_796_func_B8
#define dll_796_func_154 __dll796_dll_796_func_154
#define dll_796_func_160 __dll796_dll_796_func_160
#define dll_796_func_1B4 __dll796_dll_796_func_1B4
#define dll_796_func_1C4 __dll796_dll_796_func_1C4
#define dll_796_func_1D4 __dll796_dll_796_func_1D4
#define dll_796_func_1E8 __dll796_dll_796_func_1E8
#define _data_0 __dll796__data_0
#define _data_C __dll796__data_C
#define _data_18 __dll796__data_18

#endif //_DLL_796_RECOMP_H
