// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_796_RECOMP_H
#define _DLL_796_RECOMP_H

#define dll_796_ctor __dll796_dll_796_ctor
#define dll_796_dtor __dll796_dll_796_dtor
#define dll_796_setup __dll796_dll_796_setup
#define dll_796_control __dll796_dll_796_control
#define dll_796_update __dll796_dll_796_update
#define dll_796_print __dll796_dll_796_print
#define dll_796_free __dll796_dll_796_free
#define dll_796_get_model_flags __dll796_dll_796_get_model_flags
#define dll_796_get_data_size __dll796_dll_796_get_data_size
#define dll_796_func_1E8 __dll796_dll_796_func_1E8
#define _data_0 __dll796__data_0
#define _data_C __dll796__data_C
#define _data_18 __dll796__data_18

#endif //_DLL_796_RECOMP_H
