// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_796_RECOMP_H
#define _DLL_796_RECOMP_H

#define dll_796_ctor __dll796_dll_796_ctor
#define dll_796_dtor __dll796_dll_796_dtor
#define dll_796_create __dll796_dll_796_create
#define dll_796_update __dll796_dll_796_update
#define dll_796_func_154 __dll796_dll_796_func_154
#define dll_796_draw __dll796_dll_796_draw
#define dll_796_destroy __dll796_dll_796_destroy
#define dll_796_get_setup_flags __dll796_dll_796_get_setup_flags
#define dll_796_get_state_size __dll796_dll_796_get_state_size
#define dll_796_func_1E8 __dll796_dll_796_func_1E8
#define _data_0 __dll796__data_0
#define _data_C __dll796__data_C
#define _data_18 __dll796__data_18

#endif //_DLL_796_RECOMP_H
