// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_84_RECOMP_H
#define _DLL_84_RECOMP_H

#define dll_84_ctor __dll84_dll_84_ctor
#define dll_84_dtor __dll84_dll_84_dtor
#define dll_84_func_A8 __dll84_dll_84_func_A8
#define dll_84_func_860 __dll84_dll_84_func_860
#define dll_84_func_B70 __dll84_dll_84_func_B70
#define dll_84_func_BD4 __dll84_dll_84_func_BD4
#define dll_84_func_ED4 __dll84_dll_84_func_ED4
#define dll_84_func_11F0 __dll84_dll_84_func_11F0
#define dll_84_func_12E8 __dll84_dll_84_func_12E8
#define dll_84_func_19E8 __dll84_dll_84_func_19E8
#define dll_84_func_1A58 __dll84_dll_84_func_1A58
#define dll_84_func_1DEC __dll84_dll_84_func_1DEC
#define dll_84_func_1FFC __dll84_dll_84_func_1FFC
#define dll_84_func_22D0 __dll84_dll_84_func_22D0
#define dll_84_func_2388 __dll84_dll_84_func_2388
#define dll_84_func_24F0 __dll84_dll_84_func_24F0
#define dll_84_func_250C __dll84_dll_84_func_250C
#define dll_84_func_26E4 __dll84_dll_84_func_26E4
#define dll_84_func_29B4 __dll84_dll_84_func_29B4
#define dll_84_func_2A5C __dll84_dll_84_func_2A5C
#define str_0 __dll84_str_0
#define _rodata_20 __dll84__rodata_20
#define _rodata_24 __dll84__rodata_24
#define _rodata_28 __dll84__rodata_28
#define _rodata_2C __dll84__rodata_2C
#define _rodata_30 __dll84__rodata_30
#define _rodata_34 __dll84__rodata_34
#define _rodata_38 __dll84__rodata_38
#define _rodata_3C __dll84__rodata_3C
#define _rodata_40 __dll84__rodata_40
#define _rodata_44 __dll84__rodata_44
#define _rodata_48 __dll84__rodata_48
#define _rodata_4C __dll84__rodata_4C
#define _rodata_50 __dll84__rodata_50
#define _rodata_54 __dll84__rodata_54
#define _rodata_58 __dll84__rodata_58
#define _rodata_5C __dll84__rodata_5C
#define _rodata_60 __dll84__rodata_60
#define _rodata_64 __dll84__rodata_64
#define _rodata_68 __dll84__rodata_68
#define _rodata_6C __dll84__rodata_6C
#define _rodata_70 __dll84__rodata_70
#define _rodata_74 __dll84__rodata_74
#define _rodata_78 __dll84__rodata_78
#define _rodata_7C __dll84__rodata_7C
#define _rodata_80 __dll84__rodata_80
#define _rodata_84 __dll84__rodata_84
#define _rodata_88 __dll84__rodata_88
#define _data_0 __dll84__data_0
#define _bss_0 __dll84__bss_0
#define _bss_4 __dll84__bss_4

#endif //_DLL_84_RECOMP_H
