// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_89_RECOMP_H
#define _DLL_89_RECOMP_H

#define dll_89_ctor __dll89_dll_89_ctor
#define dll_89_dtor __dll89_dll_89_dtor
#define dll_89_func_18 __dll89_dll_89_func_18
#define dll_89_func_588 __dll89_dll_89_func_588
#define dll_89_func_DF0 __dll89_dll_89_func_DF0
#define dll_89_func_E30 __dll89_dll_89_func_E30
#define dll_89_func_E40 __dll89_dll_89_func_E40
#define dll_89_func_1004 __dll89_dll_89_func_1004
#define dll_89_func_14D8 __dll89_dll_89_func_14D8
#define dll_89_func_17A0 __dll89_dll_89_func_17A0
#define dll_89_func_19AC __dll89_dll_89_func_19AC
#define dll_89_func_1E5C __dll89_dll_89_func_1E5C
#define dll_89_func_1F9C __dll89_dll_89_func_1F9C
#define str_0 __dll89_str_0
#define rodata_34 __dll89_rodata_34
#define rodata_38 __dll89_rodata_38
#define rodata_3C __dll89_rodata_3C
#define rodata_40 __dll89_rodata_40
#define rodata_44 __dll89_rodata_44
#define rodata_48 __dll89_rodata_48
#define rodata_4C __dll89_rodata_4C
#define bss_0 __dll89_bss_0

#endif //_DLL_89_RECOMP_H
