// AUTOGENERATED FILE - PLEASE DO NOT MODIFY

#ifndef _DLL_95_RECOMP_H
#define _DLL_95_RECOMP_H

#define dll_95_ctor __dll95_dll_95_ctor
#define dll_95_dtor __dll95_dll_95_dtor
#define dll_95_func_18 __dll95_dll_95_func_18
#define dll_95_func_320 __dll95_dll_95_func_320
#define dll_95_func_544 __dll95_dll_95_func_544
#define dll_95_func_584 __dll95_dll_95_func_584
#define str_0 __dll95_str_0
#define _rodata_28 __dll95__rodata_28
#define _bss_0 __dll95__bss_0

#endif //_DLL_95_RECOMP_H
